using System.Numerics;
using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class ShuttleConsoleWindow : FancyWindow,
    IComputerWindow<ShuttleBoundUserInterfaceState>
{
    [Dependency] private IEntityManager _entManager = default!;

    private ShuttleConsoleMode _mode = ShuttleConsoleMode.Nav;

    public event Action<MapCoordinates, Angle>? RequestFTL;
    public event Action<NetEntity, Angle>? RequestBeaconFTL;

    // Mono
    public event Action<MapCoordinates, Angle>? RequestAutopilot;

    public event Action<NetEntity, NetEntity>? DockRequest;
    public event Action<NetEntity>? UndockRequest;
    public event Action<List<NetEntity>>? UndockAllRequest;
    public event Action<List<NetEntity>, bool>? ToggleFTLLockRequest;

    public ShuttleConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Mode switching
        NavModeButton.OnPressed += NavPressed;
        ShipModeButton.OnPressed += ShipPressed; // WOLFGATE(Shuttles)
        MapModeButton.OnPressed += MapPressed;
        DockModeButton.OnPressed += DockPressed;

        // Modes are exclusive
        var group = new ButtonGroup();

        NavModeButton.Group = group;
        ShipModeButton.Group = group; // WOLFGATE(Shuttles)
        MapModeButton.Group = group;
        DockModeButton.Group = group;

        NavModeButton.Pressed = true;
        SetupMode(_mode);

        MapContainer.RequestFTL += (coords, angle) =>
        {
            RequestFTL?.Invoke(coords, angle);
        };

        MapContainer.RequestBeaconFTL += (ent, angle) =>
        {
            RequestBeaconFTL?.Invoke(ent, angle);
        };

        // Mono
        MapContainer.RequestAutopilot += (coords, angle) =>
        {
            RequestAutopilot?.Invoke(coords, angle);
        };

        DockContainer.DockRequest += (entity, netEntity) =>
        {
            DockRequest?.Invoke(entity, netEntity);
        };

        DockContainer.UndockRequest += entity =>
        {
            UndockRequest?.Invoke(entity);
        };

        DockContainer.UndockAllRequest += dockEntities =>
        {
            UndockAllRequest?.Invoke(dockEntities);
        };

        DockContainer.ToggleFTLLockRequest += (dockEntities, enabled) =>
        {
            ToggleFTLLockRequest?.Invoke(dockEntities, enabled);
        };

        NfInitialize(); // Frontier Initialization for the ShuttleConsoleWindow
        WfInitialize(); // WOLFGATE(Shuttles)
    }

    private void ClearModes(ShuttleConsoleMode mode)
    {
        if (mode != ShuttleConsoleMode.Nav)
        {
            NavContainer.Visible = false;
        }

        // WOLFGATE(Shuttles) START: ship mode
        if (mode != ShuttleConsoleMode.Ship)
        {
            WfSetShipMode(false);
        }
        // WOLFGATE END

        if (mode != ShuttleConsoleMode.Map)
        {
            MapContainer.Visible = false;
            MapContainer.SetMap(MapId.Nullspace, Vector2.Zero);
        }

        if (mode != ShuttleConsoleMode.Dock)
        {
            DockContainer.Visible = false;
        }
    }

    private void NavPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Nav);
    }

    // WOLFGATE(Shuttles) START: ship mode
    private void ShipPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Ship);
    }
    // WOLFGATE END

    private void MapPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Map);
    }

    private void DockPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Dock);
    }

    private void SetupMode(ShuttleConsoleMode mode)
    {
        switch (mode)
        {
            case ShuttleConsoleMode.Nav:
                NavContainer.Visible = true;
                break;
            // WOLFGATE(Shuttles) START: ship mode
            case ShuttleConsoleMode.Ship:
                WfSetShipMode(true);
                break;
            // WOLFGATE END
            case ShuttleConsoleMode.Map:
                MapContainer.Visible = true;
                MapContainer.Startup();
                break;
            case ShuttleConsoleMode.Dock:
                DockContainer.Visible = true;
                break;
            default:
                throw new NotImplementedException();
        }
    }

    public void SwitchMode(ShuttleConsoleMode mode)
    {
        if (_mode == mode)
            return;

        _mode = mode;
        ClearModes(mode);
        SetupMode(_mode);
    }

    public enum ShuttleConsoleMode : byte
    {
        Nav,
        Ship, // WOLFGATE(Shuttles)
        Map,
        Dock,
    }

    public void UpdateState(EntityUid owner, ShuttleBoundUserInterfaceState cState)
    {
        var coordinates = _entManager.GetCoordinates(cState.NavState.Coordinates);
        NavContainer.SetShuttle(coordinates?.EntityId);
        NavContainer.SetConsole(owner);
        MapContainer.SetShuttle(coordinates?.EntityId);
        MapContainer.SetConsole(owner);
        // WOLFGATE(Shuttles) START: ship screen, collision and tractor state
        ShipContainer.SetShuttle(coordinates?.EntityId);
        ShipContainer.SetConsole(owner);
        CollisionBanner.SetShuttle(coordinates?.EntityId);
        WfUpdateTractorCapture(cState.TractorSources);
        // WOLFGATE END

        NavContainer.UpdateState(cState.NavState);
        MapContainer.UpdateState(cState.MapState);
        DockContainer.UpdateState(coordinates?.EntityId, cState.DockState);
    }
}
