# Generated by Tools/_WF/genitals/gen_genital_shapes.py; do not edit by hand.

## Penis
wf-genitals-shape-penis-human = Human
wf-genitals-shape-penis-human-examine = human
wf-genitals-shape-penis-nondescript = Nondescript
wf-genitals-shape-penis-knotted = Knotted
wf-genitals-shape-penis-knotted-examine = knotted
wf-genitals-shape-penis-flared = Flared
wf-genitals-shape-penis-flared-examine = flared
wf-genitals-shape-penis-barbknot = Barbed, knotted
wf-genitals-shape-penis-barbknot-examine = barbed and knotted
wf-genitals-shape-penis-tapered = Tapered
wf-genitals-shape-penis-tapered-examine = tapered
wf-genitals-shape-penis-hemi = Hemipenes
wf-genitals-shape-penis-hemi-examine = paired (hemipenes)
wf-genitals-shape-penis-hemiknot = Hemipenes, knotted
wf-genitals-shape-penis-hemiknot-examine = paired and knotted
wf-genitals-shape-penis-tipknotted = Tip-knotted
wf-genitals-shape-penis-tipknotted-examine = tip-knotted
wf-genitals-shape-penis-tentacle = Tentacular
wf-genitals-shape-penis-tentacle-examine = tentacular

## Testicles
wf-genitals-shape-testicles-pair = Pair

## Vagina
wf-genitals-shape-vagina-human = Human
wf-genitals-shape-vagina-open = Open
wf-genitals-shape-vagina-open-examine = open
wf-genitals-shape-vagina-tentacle = Tentacular
wf-genitals-shape-vagina-tentacle-examine = tentacular
wf-genitals-shape-vagina-dentate = Dentate
wf-genitals-shape-vagina-dentate-examine = dentate
wf-genitals-shape-vagina-haired = With hair
wf-genitals-shape-vagina-haired-examine = with visible hair
wf-genitals-shape-vagina-furred = Furred
wf-genitals-shape-vagina-furred-examine = furred
wf-genitals-shape-vagina-spade = Spade-shaped
wf-genitals-shape-vagina-spade-examine = spade-shaped

## Breasts
wf-genitals-shape-breasts-pair = Pair
wf-genitals-shape-breasts-pair-examine = a pair of breasts
wf-genitals-shape-breasts-pairround = Pair, rounded
wf-genitals-shape-breasts-pairround-examine = a rounded pair of breasts
wf-genitals-shape-breasts-quad = Four
wf-genitals-shape-breasts-quad-examine = four breasts
wf-genitals-shape-breasts-quadlite = Four, compact
wf-genitals-shape-breasts-quadlite-examine = four breasts (compact)
wf-genitals-shape-breasts-quadplus = Four, extended
wf-genitals-shape-breasts-quadplus-examine = four breasts (extended)
wf-genitals-shape-breasts-sextuple = Six
wf-genitals-shape-breasts-sextuple-examine = six breasts
wf-genitals-shape-breasts-udders = Udders
wf-genitals-shape-breasts-udders-examine = udders

## Hand-written shapes (shapes_extra.yml)
wf-genitals-shape-vagina-slit = Slit (cloacal)
wf-genitals-shape-vagina-slit-examine = slit-shaped
