using Content.Client._WF.Stylesheets;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.CCVar;
using Content.Shared._WF.PlanetCracker.Survey.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._WF.PlanetCracker.Survey;

/// <summary>
/// The sector survey console: one table line per star-system body, with its distance, legal status, crack state and
/// vein rating, and the destination name a pilot types into the shuttle console shown for whichever line is selected.
/// Everything comes out of one <see cref="WFSurveyConsoleState"/>, and the only strings that are not locale keys are
/// entity names that already exist in the world. Nothing on this window sends a message; selection is a client-local
/// highlight.
/// The rows are reused rather than rebuilt: the server pushes a state once a second, and dropping every control each
/// time threw away the scroll position and reallocated the whole list for values that had usually not moved.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WFSurveyConsoleWindow : FancyWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;

    /// <summary>
    /// Right gutter on the column titles, matching the vertical scrollbar the rows lose width to once the list is
    /// long enough to scroll. ScrollContainer only subtracts the bar when it is actually needed, so with a short list
    /// the titles sit this far inboard of their columns; that is the whole of the residual error.
    /// </summary>
    private const float ScrollGutter = StyleBase.DefaultGrabberSize;

    /// <summary>The rows on screen, in state order; index i draws state.Planets[i].</summary>
    private readonly List<WFSurveyPlanetRow> _rows = new();

    /// <summary>The highlighted row, kept purely client-side; the server is never told which row anyone is reading.</summary>
    private NetEntity? _selected;

    /// <summary>The row controls currently on screen. For the headless window test, which asserts they are reused.</summary>
    public IReadOnlyList<WFSurveyPlanetRow> Rows => _rows;

    public WFSurveyConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        WFSurveyPlanetRow.ApplyColumns(ColBody, ColDistance, ColStatus, ColCrack, ColVeins);

        // The titles start where a row's first cell starts, and end where a scrolling row's last cell ends.
        ColumnHeader.Margin = new Thickness(
            WFSurveyPlanetRow.RowInset,
            0f,
            WFSurveyPlanetRow.RowInset + ScrollGutter,
            2f);
    }

    /// <summary>Pushes one server state into every control on the window.</summary>
    public void UpdateState(WFSurveyConsoleState state)
    {
        // Re-read the skin each update so a mid-round style change takes effect on the next push.
        var skin = WolfgateSkins.Get(_cfg.GetCVar(WolfgateCVars.UiStyle));

        HeaderSystem.Text = Loc.GetString("wf-survey-console-system", ("system", state.SystemName));
        HeaderSystem.FontColorOverride = skin.Text;

        HeaderCount.Text = Loc.GetString("wf-survey-console-count", ("count", state.Planets.Count));
        HeaderCount.FontColorOverride = skin.TextMuted;

        HeaderHint.Text = Loc.GetString("wf-survey-console-hint");
        HeaderHint.FontColorOverride = skin.TextMuted;

        var empty = state.Planets.Count == 0;
        PlanetScroll.Visible = !empty;
        ColumnHeader.Visible = !empty;
        EmptyLabel.Visible = empty;
        EmptyLabel.Text = Loc.GetString("wf-survey-console-empty");
        EmptyLabel.FontColorOverride = skin.TextMuted;

        // Drop the highlight when the body it pointed at is no longer in the list.
        if (_selected is { } selected && !Contains(state, selected))
            _selected = null;

        Resize(state.Planets.Count);

        for (var i = 0; i < state.Planets.Count; i++)
        {
            _rows[i].SetData(state.Planets[i], skin);
        }

        ApplySelection(skin);
    }

    /// <summary>Grows or shrinks the row list to the state's length, keeping the controls that are already there.</summary>
    private void Resize(int count)
    {
        while (_rows.Count > count)
        {
            var last = _rows[^1];
            _rows.RemoveAt(_rows.Count - 1);
            last.OnClicked -= OnRowClicked;
            Planets.RemoveChild(last);
            last.Dispose();
        }

        while (_rows.Count < count)
        {
            var row = new WFSurveyPlanetRow();
            row.OnClicked += OnRowClicked;
            _rows.Add(row);
            Planets.AddChild(row);
        }
    }

    /// <summary>Moves the client-local highlight; clicking the selected row again clears it.</summary>
    private void OnRowClicked(NetEntity planet)
    {
        _selected = _selected == planet ? null : planet;
        ApplySelection(WolfgateSkins.Get(_cfg.GetCVar(WolfgateCVars.UiStyle)));
    }

    /// <summary>Paints the highlight onto whichever row owns it and fills the detail line from that row.</summary>
    private void ApplySelection(WolfgateSkin skin)
    {
        WFSurveyPlanetRow? chosen = null;

        foreach (var row in _rows)
        {
            var selected = row.Planet is { } body && body == _selected;
            row.SetSelected(selected);

            if (selected)
                chosen = row;
        }

        if (chosen is null)
        {
            DetailName.Text = Loc.GetString("wf-survey-detail-none");
            DetailName.FontColorOverride = skin.TextMuted;
            DetailBeacon.Text = string.Empty;
            return;
        }

        DetailName.Text = chosen.BodyName;
        DetailName.FontColorOverride = skin.Text;
        DetailBeacon.Text = chosen.BeaconLine;
        DetailBeacon.FontColorOverride = skin.Accent;
    }

    /// <summary>True when the state still carries a row for this body.</summary>
    private static bool Contains(WFSurveyConsoleState state, NetEntity planet)
    {
        foreach (var row in state.Planets)
        {
            if (row.Planet == planet)
                return true;
        }

        return false;
    }
}
