using System.Numerics;
using Content.Client._WF.Administration.RadarTeleport;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Timing;

namespace Content.Client._WF.Administration.UI.AdminRadar;

/// <summary>
/// The mass scanner window an admin in a ghost gets: the display follows the window's size, zooms out across the
/// sector, and a click on it can teleport the ghost there.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AdminRadarWindow : FancyWindow
{
    private Vector2 _restorePosition;
    private Vector2 _restoreSize;

    public AdminRadarWindow()
    {
        RobustXamlLoader.Load(this);
        LayoutContainer.SetAnchorPreset(RadarScreen, LayoutContainer.LayoutPreset.Wide);

        IffToggle.OnToggled += args => RadarScreen.ShowIFF = args.Pressed;
        IffDetailedToggle.OnToggled += args => RadarScreen.ShowIFFDetailed = args.Pressed;
        MaximizeToggle.OnToggled += OnMaximizeToggled;

        var teleport = IoCManager.Resolve<IEntityManager>().System<RadarTeleportSystem>();
        AdminTeleportToggle.Pressed = teleport.Enabled;
        AdminTeleportToggle.OnToggled += args => teleport.Enabled = args.Pressed;
        RadarScreen.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.UIClick)
                teleport.RequestTeleport(RadarScreen.GetMouseCoordinatesFromCenter());
        };
    }

    /// <summary>
    /// Opens this window for a mass scanner if the local player is an admin in a ghost. Null for anyone else.
    /// </summary>
    public static AdminRadarWindow? OpenFor(BoundUserInterface bui)
    {
        if (!IoCManager.Resolve<IEntityManager>().System<RadarTeleportSystem>().CanTeleport())
            return null;

        var window = bui.CreateWindow<AdminRadarWindow>();
        window.RadarScreen.SetConsole(bui.Owner);
        return window;
    }

    public void UpdateState(NavInterfaceState state)
    {
        RadarScreen.UpdateAdminState(state);
    }

    /// <summary>True while the window sits in the game window. Popped out, the OS window does the sizing.</summary>
    private bool InGameWindow => Parent != null && Parent == UserInterfaceManager.WindowRoot;

    private void OnMaximizeToggled(BaseButton.ButtonToggledEventArgs args)
    {
        if (!InGameWindow)
            return;

        if (args.Pressed)
        {
            _restorePosition = Position;
            _restoreSize = SetSize;
            Maximize();
        }
        else
        {
            LayoutContainer.SetPosition(this, _restorePosition);
            SetSize = _restoreSize;
        }
    }

    private void Maximize()
    {
        LayoutContainer.SetPosition(this, Vector2.Zero);
        SetSize = Parent!.Size;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        MaximizeToggle.Visible = InGameWindow;

        // Follow the game window while maximized.
        if (MaximizeToggle.Pressed && InGameWindow && (Position != Vector2.Zero || SetSize != Parent!.Size))
            Maximize();
    }
}
