using System.Numerics;
using Content.Client._WF.Administration.AdminRadar;
using Content.Client._WF.Administration.RadarTeleport;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.Administration.AdminRadar;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Timing;

namespace Content.Client._WF.Administration.UI.AdminRadar;

/// <summary>
/// The mass scanner window an admin in a ghost gets: the display follows the window's size, zooms out across the
/// sector, sees past IFF, marks players, and can put the ghost on a clicked spot or a picked player.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AdminRadarWindow : FancyWindow
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPlayerManager _playerManager = default!;

    private readonly AdminRadarSystem _radar;

    /// <summary>The players the jump list has rows for, in row order.</summary>
    private readonly List<AdminRadarPlayer> _jumpRows = new();
    private readonly List<AdminRadarPlayer> _jumpMatches = new();

    private Vector2 _restorePosition;
    private Vector2 _restoreSize;

    public AdminRadarWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        LayoutContainer.SetAnchorPreset(RadarScreen, LayoutContainer.LayoutPreset.Wide);

        _radar = _entManager.System<AdminRadarSystem>();

        IffToggle.OnToggled += args => RadarScreen.ShowIFF = args.Pressed;
        IffDetailedToggle.OnToggled += args => RadarScreen.ShowIFFDetailed = args.Pressed;
        MaximizeToggle.OnToggled += OnMaximizeToggled;

        TrueIffToggle.Pressed = _radar.TrueIff;
        TrueIffToggle.OnToggled += args => _radar.TrueIff = args.Pressed;

        PlayersToggle.Pressed = _radar.ShowPlayers;
        PlayersToggle.OnToggled += args =>
        {
            _radar.ShowPlayers = args.Pressed;
            if (args.Pressed)
                _radar.RequestPlayers(true);
        };

        JumpToggle.OnToggled += args => SetJumpOpen(args.Pressed);
        JumpSearch.OnTextChanged += _ => PopulateJumpList();
        JumpSearch.OnTextEntered += _ =>
        {
            if (_jumpRows.Count > 0)
                JumpTo(_jumpRows[0]);
        };

        var teleport = _entManager.System<RadarTeleportSystem>();
        AdminTeleportToggle.Pressed = teleport.Enabled;
        AdminTeleportToggle.OnToggled += args => teleport.Enabled = args.Pressed;
        RadarScreen.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.UIClick)
                teleport.RequestTeleport(RadarScreen.GetMouseCoordinatesFromCenter());
        };
    }

    /// <summary>
    /// Opens this window for a mass scanner if the local player is an admin in a ghost. Null for anyone else.
    /// </summary>
    public static AdminRadarWindow? OpenFor(BoundUserInterface bui)
    {
        if (!IoCManager.Resolve<IEntityManager>().System<RadarTeleportSystem>().CanTeleport())
            return null;

        var window = bui.CreateWindow<AdminRadarWindow>();
        window.RadarScreen.SetConsole(bui.Owner);
        return window;
    }

    public void UpdateState(NavInterfaceState state)
    {
        RadarScreen.UpdateAdminState(state);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _radar.PlayersUpdated += PopulateJumpList;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _radar.PlayersUpdated -= PopulateJumpList;
    }

    /// <summary>
    /// Shows or hides the jump list. Opening it asks for fresh players and puts the cursor in the search box.
    /// </summary>
    private void SetJumpOpen(bool open)
    {
        JumpToggle.Pressed = open;
        JumpPanel.Visible = open;

        if (!open)
        {
            JumpSearch.Text = string.Empty;
            JumpSearch.ReleaseKeyboardFocus();
            return;
        }

        _radar.RequestPlayers(true);
        PopulateJumpList();
        JumpSearch.GrabKeyboardFocus();
    }

    /// <summary>
    /// Fills the jump list with the players matching the search, bodies before ghosts.
    /// </summary>
    private void PopulateJumpList()
    {
        if (!JumpPanel.Visible)
            return;

        var search = JumpSearch.Text.Trim().ToLowerInvariant();
        _jumpMatches.Clear();
        foreach (var player in _radar.Players)
        {
            // Not the admin's own ghost.
            if (_entManager.TryGetEntity(player.Entity, out var uid) && uid == _playerManager.LocalEntity)
                continue;

            if (search.Length > 0
                && !player.Name.ToLowerInvariant().Contains(search)
                && !player.Username.ToLowerInvariant().Contains(search))
                continue;

            _jumpMatches.Add(player);
        }

        _jumpMatches.Sort((a, b) => a.Ghost != b.Ghost
            ? a.Ghost.CompareTo(b.Ghost)
            : string.Compare(a.Name, b.Name, StringComparison.CurrentCultureIgnoreCase));

        // A new list comes every second with new positions; the rows only change when the players do, and
        // rebuilding them under the cursor would swallow a click.
        if (SameRows())
            return;

        _jumpRows.Clear();
        _jumpRows.AddRange(_jumpMatches);
        JumpList.RemoveAllChildren();
        JumpEmpty.Visible = _jumpRows.Count == 0;

        foreach (var player in _jumpRows)
        {
            var row = new Button
            {
                Text = Loc.GetString(player.Ghost ? "wf-admin-radar-jump-entry-ghost" : "wf-admin-radar-jump-entry",
                    ("name", player.Name),
                    ("username", player.Username)),
                StyleClasses = { "ButtonSquare" },
                ClipText = true,
                HorizontalExpand = true,
            };
            row.OnPressed += _ => JumpTo(player);
            JumpList.AddChild(row);
        }
    }

    private bool SameRows()
    {
        if (_jumpMatches.Count != _jumpRows.Count || JumpList.ChildCount != _jumpRows.Count)
            return false;

        for (var i = 0; i < _jumpRows.Count; i++)
        {
            var (shown, match) = (_jumpRows[i], _jumpMatches[i]);
            if (shown.Entity != match.Entity || shown.Ghost != match.Ghost || shown.Name != match.Name || shown.Username != match.Username)
                return false;
        }

        return true;
    }

    /// <summary>
    /// Warps the ghost to a player and brings the scanner back to the ghost.
    /// </summary>
    private void JumpTo(AdminRadarPlayer player)
    {
        _radar.JumpTo(player.Entity);
        RadarScreen.Recentre();
        SetJumpOpen(false);
    }

    /// <summary>True while the window sits in the game window. Popped out, the OS window does the sizing.</summary>
    private bool InGameWindow => Parent != null && Parent == UserInterfaceManager.WindowRoot;

    private void OnMaximizeToggled(BaseButton.ButtonToggledEventArgs args)
    {
        if (!InGameWindow)
            return;

        if (args.Pressed)
        {
            _restorePosition = Position;
            _restoreSize = SetSize;
            Maximize();
        }
        else
        {
            LayoutContainer.SetPosition(this, _restorePosition);
            SetSize = _restoreSize;
        }
    }

    private void Maximize()
    {
        LayoutContainer.SetPosition(this, Vector2.Zero);
        SetSize = Parent!.Size;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        MaximizeToggle.Visible = InGameWindow;

        // Follow the game window while maximized.
        if (MaximizeToggle.Pressed && InGameWindow && (Position != Vector2.Zero || SetSize != Parent!.Size))
            Maximize();

        if (_radar.ShowPlayers || JumpPanel.Visible)
            _radar.RequestPlayers();
    }
}
