using Content.Shared._WF.Administration.GhostOffer;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._WF.Administration.UI.GhostOffer;

/// <summary>
/// Shown to every ghost when an admin offers a ghost role: what it is, its rules, and buttons to sign up or look.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GhostOfferPromptWindow : DefaultWindow
{
    [Dependency] private IClientConsoleHost _console = default!;

    public event Action? SignUpPressed;
    public event Action? FollowPressed;

    public int OfferId { get; }

    public GhostOfferPromptWindow(GhostOfferEvent offer)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        OfferId = offer.OfferId;
        RoleNameLabel.Text = offer.Name;
        DescriptionLabel.SetMessage(FormattedMessage.FromMarkupPermissive(offer.Description));
        RulesLabel.SetMessage(FormattedMessage.FromMarkupPermissive(offer.Rules));
        HowLabel.Text = Loc.GetString(offer.Raffled
            ? "wf-ghost-offer-prompt-raffle"
            : "wf-ghost-offer-prompt-first-come");

        SignUpButton.OnPressed += _ => SignUpPressed?.Invoke();
        FollowButton.OnPressed += _ => FollowPressed?.Invoke();
        RolesButton.OnPressed += _ => _console.ExecuteCommand("ghostroles");
    }

    /// <summary>
    /// Shows the server's answer to a sign-up; a successful one can't be repeated.
    /// </summary>
    public void SetStatus(string message, bool isError)
    {
        StatusLabel.Text = message;
        StatusLabel.FontColorOverride = isError ? Color.Red : null;
        if (!isError)
            SignUpButton.Disabled = true;
    }
}
