using System.Globalization;
using System.Linq;
using Content.Shared._WF.PlanetCracker.Administration;
using Content.Shared.Weather;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WF.PlanetCracker.Administration;

/// <summary>Admin panel for a world's clock, weather, gravity and sanction.</summary>
[GenerateTypedNameReferences]
public sealed partial class PlanetControlWindow : DefaultWindow
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    private readonly PlanetControlSystem _planets;

    private List<PlanetControlInfo> _list = new();
    private readonly List<string> _weatherIds = new();
    private NetEntity? _selected;

    /// <summary>True while the controls are being filled in, so the checkbox does not answer its own update.</summary>
    private bool _filling;

    public PlanetControlWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _planets = _entMan.System<PlanetControlSystem>();
        _planets.ListReceived += OnList;

        WeatherOption.AddItem(Loc.GetString("wf-planet-control-weather-clear"), 0);
        _weatherIds.Add(string.Empty);

        foreach (var weather in _proto.EnumeratePrototypes<WeatherPrototype>().OrderBy(w => w.ID))
        {
            WeatherOption.AddItem(weather.ID, _weatherIds.Count);
            _weatherIds.Add(weather.ID);
        }

        WeatherOption.OnItemSelected += args => WeatherOption.SelectId(args.Id);
        PlanetList.OnItemSelected += args =>
        {
            _selected = (NetEntity?) PlanetList[args.ItemIndex].Metadata;
            Fill();
        };

        RefreshButton.OnPressed += _ => _planets.RequestList();
        TimeButton.OnPressed += _ => SendTime(TimeEdit.Text);
        TimeEdit.OnTextEntered += args => SendTime(args.Text);
        DawnButton.OnPressed += _ => SendMinute(6 * 60);
        NoonButton.OnPressed += _ => SendMinute(12 * 60);
        DuskButton.OnPressed += _ => SendMinute(18 * 60);
        MidnightButton.OnPressed += _ => SendMinute(0);
        WeatherButton.OnPressed += _ => SendWeather();
        GravityButton.OnPressed += _ => SendGravity(GravityEdit.Text);
        GravityEdit.OnTextEntered += args => SendGravity(args.Text);
        SanctionedCheck.OnToggled += args =>
        {
            if (!_filling && _selected is { } planet)
                _planets.Send(new PlanetControlSetEvent { Planet = planet, Sanctioned = args.Pressed });
        };

        Fill();
        _planets.RequestList();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
            _planets.ListReceived -= OnList;
    }

    private void OnList(List<PlanetControlInfo> list)
    {
        _list = list;
        PlanetList.Clear();

        if (_selected is null || list.All(p => p.Planet != _selected))
            _selected = list.Count > 0 ? list[0].Planet : null;

        foreach (var info in list)
        {
            var item = PlanetList.AddItem(info.Name);
            item.Metadata = info.Planet;

            if (info.Planet == _selected)
                item.Selected = true;
        }

        Fill();
    }

    /// <summary>Shows the selected world. The edit boxes are only overwritten when nobody is typing in them.</summary>
    private void Fill()
    {
        var info = _list.FirstOrDefault(p => p.Planet == _selected);
        var built = info?.Built ?? false;

        _filling = true;

        PlanetLabel.Text = info?.Name ?? Loc.GetString("wf-planet-control-none");
        StatusLabel.Text = info == null
            ? string.Empty
            : built
                ? Loc.GetString("wf-planet-control-status",
                    ("time", $"{info.MinuteOfDay / 60:00}:{info.MinuteOfDay % 60:00}"),
                    ("weather", info.Weather.Length == 0 ? Loc.GetString("wf-planet-control-weather-clear") : info.Weather),
                    ("seconds", info.WeatherSeconds.ToString("F0")),
                    ("gravity", info.Gravity.ToString("F2")))
                : Loc.GetString("wf-planet-control-not-built");

        foreach (var control in new Control[] { TimeEdit, TimeButton, DawnButton, NoonButton, DuskButton, MidnightButton, WeatherButton, GravityButton })
        {
            if (control is Button button)
                button.Disabled = !built;
            else if (control is LineEdit edit)
                edit.Editable = built;
        }

        GravityEdit.Editable = built;
        WeatherSecondsEdit.Editable = built;
        WeatherOption.Disabled = !built;
        SanctionedCheck.Disabled = info == null;

        if (info != null)
        {
            SanctionedCheck.Pressed = info.Sanctioned;

            if (built && !TimeEdit.HasKeyboardFocus())
                TimeEdit.Text = $"{info.MinuteOfDay / 60:00}:{info.MinuteOfDay % 60:00}";

            if (built && !GravityEdit.HasKeyboardFocus())
                GravityEdit.Text = info.Gravity.ToString("F2", CultureInfo.InvariantCulture);

            var weather = _weatherIds.IndexOf(info.Weather);
            if (weather >= 0)
                WeatherOption.SelectId(weather);
        }

        _filling = false;
    }

    private void SendTime(string text)
    {
        if (TimeSpan.TryParseExact(text.Trim(), @"h\:mm", CultureInfo.InvariantCulture, out var time))
            SendMinute((int) time.TotalMinutes % 1440);
    }

    private void SendMinute(int minute)
    {
        if (_selected is { } planet)
            _planets.Send(new PlanetControlSetEvent { Planet = planet, MinuteOfDay = minute });
    }

    private void SendWeather()
    {
        if (_selected is not { } planet)
            return;

        if (!float.TryParse(WeatherSecondsEdit.Text, NumberStyles.Float, CultureInfo.InvariantCulture, out var seconds))
            seconds = 600f;

        var id = _weatherIds[WeatherOption.SelectedId];
        _planets.Send(new PlanetControlSetEvent
        {
            Planet = planet,
            SetWeather = true,
            Weather = id.Length == 0 ? null : id,
            WeatherSeconds = seconds,
        });
    }

    private void SendGravity(string text)
    {
        if (_selected is { } planet
            && float.TryParse(text.Trim(), NumberStyles.Float, CultureInfo.InvariantCulture, out var gravity))
        {
            _planets.Send(new PlanetControlSetEvent { Planet = planet, Gravity = gravity });
        }
    }
}
