using System.Linq;
using Content.Client._WF.Audio.InternetSound;
using Content.Shared._WF.Administration;
using Content.Shared._WF.Audio.InternetSound;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client._WF.Administration.UI.InternetSound;

/// <summary>
/// Admin panel for internet sounds: paste a link, play it to everyone, or stop it. Shows what's playing and
/// blocks a second sound until the first is stopped or finishes.
/// </summary>
[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class InternetSoundAdminWindow : DefaultWindow
{
    [Dependency] private IClientConsoleHost _consoleHost = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    private readonly InternetSoundSystem _internetSound;

    public InternetSoundAdminWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _internetSound = _entityManager.System<InternetSoundSystem>();
        _internetSound.StatusReceived += OnStatus;
        _internetSound.StateReceived += OnState;
        OnClose += () =>
        {
            _internetSound.StatusReceived -= OnStatus;
            _internetSound.StateReceived -= OnState;
        };

        PlayButton.OnPressed += _ => Play();
        UrlEdit.OnTextEntered += _ => Play();
        GridEdit.OnTextEntered += _ => Play();
        StopButton.OnPressed += _ => _consoleHost.ExecuteCommand(WolfgateAdminCommands.StopInternetSound);

        PaCheck.OnToggled += _ => UpdatePaControls();
        UpdatePaControls();

        // Show the last known state straight away, then ask the server in case it's stale.
        OnState(_internetSound.State);
        _internetSound.RequestState();
    }

    private void UpdatePaControls()
    {
        GridEdit.Editable = PaCheck.Pressed;
        PaHintLabel.Visible = PaCheck.Pressed;
        OnState(_internetSound.State);
    }

    private void Play()
    {
        // Quotes would break the command line; links never need them.
        var url = UrlEdit.Text.Trim().Replace("\"", string.Empty);
        if (url.Length == 0)
            return;

        if (!PaCheck.Pressed)
        {
            _consoleHost.ExecuteCommand($"{WolfgateAdminCommands.PlayInternetSound} \"{url}\"");
            return;
        }

        var grid = GridEdit.Text.Trim();
        if (!IsValidGridInput(grid))
        {
            OnStatus(Loc.GetString("wf-internet-sound-admin-need-grid"), true);
            return;
        }

        _consoleHost.ExecuteCommand($"{WolfgateAdminCommands.PlayInternetSoundPa} {grid} \"{url}\"");
    }

    internal static bool IsValidGridInput(string grid)
    {
        return grid.Length != 0
            && !grid.Any(char.IsWhiteSpace)
            && !grid.Contains('"')
            && NetEntity.TryParse(grid, out var netGrid)
            && netGrid.IsValid();
    }

    private void OnState(InternetSoundStateEvent? state)
    {
        // Only a global sound blocks the plain Play button; a ship can always take over its own PA.
        PlayButton.Disabled = state is { GlobalBusy: true } && !PaCheck.Pressed;

        if (state == null || state.Tracks.Count == 0)
        {
            NowPlayingLabel.Text = Loc.GetString("wf-internet-sound-admin-idle");
            return;
        }

        var lines = state.Tracks.Select(track =>
        {
            var what = track switch
            {
                { Fetching: true } => Loc.GetString("wf-internet-sound-admin-fetching"),
                { Sending: true } => Loc.GetString("wf-internet-sound-admin-sending"),
                _ => track.Title,
            };

            return track.Ship is { } ship
                ? Loc.GetString("wf-internet-sound-admin-entry-pa", ("title", what), ("admin", track.Requester), ("ship", ship))
                : Loc.GetString("wf-internet-sound-admin-entry", ("title", what), ("admin", track.Requester));
        });

        NowPlayingLabel.Text = string.Join('\n', lines);
    }

    private void OnStatus(string message, bool isError)
    {
        StatusLabel.Text = message;
        StatusLabel.FontColorOverride = isError ? Color.Red : null;
    }
}
