using System.Linq;
using Content.Client._Common.Consent;
using Content.Client._Common.Consent.UI;
using Content.Shared._Common.CCVar;
using Content.Shared._Common.Consent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._WF.Options.UI.Tabs;

/// <summary>
/// The OOC consent preferences, as a tab in Game Options instead of a window of their own.
/// Consent is stored per player on the server rather than in a CVar, so this tab keeps its own Save
/// button rather than joining the options window's shared Apply row.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WolfgateConsentTab : Control
{
    [Dependency] private IClientConsentManager _consentManager = default!;
    [Dependency] private IConfigurationManager _configManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    /// <summary>Indent, in pixels, per Requires level.</summary>
    private const float RequiresIndent = 14f;

    /// <summary>Longest Requires chain followed; guards against cycles.</summary>
    private const int MaxRequiresDepth = 8;

    private static readonly Color DisabledModulate = Color.White.WithAlpha(0.5f);

    private readonly List<ConsentToggleControl> _toggles = new();

    public WolfgateConsentTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SaveConsentSettings.OnPressed += _ =>
        {
            SaveConsentSettings.Disabled = true;
            _consentManager.UpdateConsent(GetSettings());
        };

        ConsentFreetext.Placeholder = new Rope.Leaf(Loc.GetString("consent-window-freetext-placeholder"));
        ConsentFreetext.OnTextChanged += _ => UnsavedChanges();

        _consentManager.OnServerDataLoaded += Refresh;
    }

    /// <summary>
    /// Rebuilds the toggles and reloads the saved values. Called whenever the options window opens, so a
    /// toggle prototype added by a different server still shows up.
    /// </summary>
    public void Refresh()
    {
        var loaded = _consentManager.HasLoaded;
        ConsentContent.Visible = loaded;
        UnavailableLabel.Visible = !loaded;

        if (!loaded)
            return;

        BuildToggles();
        LoadValues();
    }

    private void BuildToggles()
    {
        var wanted = _prototypeManager.EnumeratePrototypes<ConsentTogglePrototype>()
            .OrderBy(x => x.SortKey)
            .ToList();

        if (_toggles.Count == wanted.Count &&
            _toggles.Select(t => t.ConsentToggleProtoId).SequenceEqual(wanted.Select(p => (ProtoId<ConsentTogglePrototype>) p.ID)))
        {
            return;
        }

        ConsentSettings.DisposeAllChildren();
        _toggles.Clear();

        foreach (var toggle in wanted)
        {
            var control = new ConsentToggleControl(toggle)
            {
                // A toggle that needs another one sits indented under it.
                Margin = new Thickness(RequiresIndent * RequiresDepth(toggle), 0, 0, 0),
            };
            control.OnStateChange += _ =>
            {
                UpdateRequirements();
                UnsavedChanges();
            };
            _toggles.Add(control);
            ConsentSettings.AddChild(control);
        }
    }

    /// <summary>Number of Requires links above a toggle; bounded so a cyclic chain cannot hang the tab.</summary>
    private int RequiresDepth(ConsentTogglePrototype toggle)
    {
        var depth = 0;
        while (depth < MaxRequiresDepth
               && toggle.Requires is { } required
               && _prototypeManager.TryIndex(required, out var next))
        {
            depth++;
            toggle = next;
        }

        return depth;
    }

    /// <summary>Disables every toggle whose Requires chain is not all on in the unsaved state. Its own value is kept.</summary>
    private void UpdateRequirements()
    {
        var states = new Dictionary<ProtoId<ConsentTogglePrototype>, string>();
        foreach (var toggle in _toggles)
            states[toggle.ConsentToggleProtoId] = toggle.State;

        foreach (var toggle in _toggles)
        {
            var met = RequirementsMet(toggle.ConsentToggleProtoId, states);
            toggle.ConsentToggleOnButton.Disabled = !met;
            toggle.ConsentToggleOffButton.Disabled = !met;
            toggle.Modulate = met ? Color.White : DisabledModulate;
        }
    }

    /// <summary>Every toggle up the Requires chain is on. A required toggle missing from the tab counts as off.</summary>
    private bool RequirementsMet(ProtoId<ConsentTogglePrototype> id, Dictionary<ProtoId<ConsentTogglePrototype>, string> states)
    {
        var current = id;
        for (var i = 0; i < MaxRequiresDepth; i++)
        {
            if (!_prototypeManager.TryIndex(current, out var proto) || proto.Requires is not { } required)
                return true;

            if (!states.TryGetValue(required, out var state) || state != "on")
                return false;

            current = required;
        }

        return true;
    }

    private void LoadValues()
    {
        var consent = _consentManager.GetConsentSettings();
        ConsentFreetext.TextRope = new Rope.Leaf(consent.Freetext);

        foreach (var toggle in _toggles)
        {
            // The server only stores toggles that are on, so anything absent is off.
            toggle.SetState(consent.Toggles.TryGetValue(toggle.ConsentToggleProtoId, out var state) ? state : "off");
        }

        UpdateRequirements();
        SaveConsentSettings.Disabled = true;
        SaveLabel.Text = string.Empty;
    }

    private PlayerConsentSettings GetSettings()
    {
        var toggles = new Dictionary<ProtoId<ConsentTogglePrototype>, string>();
        foreach (var toggle in _toggles)
            toggles[toggle.ConsentToggleProtoId] = toggle.State;

        return new PlayerConsentSettings(Rope.Collapse(ConsentFreetext.TextRope), toggles);
    }

    private void UnsavedChanges()
    {
        var maxLength = _configManager.GetCVar(ConsentSystemCCVars.ConsentFreetextMaxLength);
        var length = Rope.Collapse(ConsentFreetext.TextRope).Length;

        if (length > maxLength)
        {
            SaveLabel.Text = Loc.GetString("consent-window-char-limit-warning", ("length", length), ("maxLength", maxLength));
            SaveConsentSettings.Disabled = true;
            return;
        }

        SaveLabel.Text = Loc.GetString("consent-window-unsaved-changes");
        SaveConsentSettings.Disabled = false;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            _consentManager.OnServerDataLoaded -= Refresh;

        base.Dispose(disposing);
    }
}
