using System.Collections.Concurrent;
using System.Linq;
using System.Numerics;
using Content.Client._Mono.MonoCoins;
using Content.Client._WF.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._WF.Loadouts;

/// <summary>
/// Loadout picker of the character creator, opened in place of the stock one-tab-per-group window. A rail on
/// the left lists every group under a few categories with what is picked there; the right side shows the open
/// group as a grid of tiles, or search results from all groups. Selecting only re-reads state: the rail and
/// the grid are not rebuilt, so nothing scrolls or jumps.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WolfgateLoadoutWindow : FancyWindow
{
    /// <summary>A search starts at this many characters; one letter matches nearly everything.</summary>
    private const int MinSearchLength = 2;

    /// <summary>Frames a scroll request is repeated for, as the scroll range only catches up in the next layout.</summary>
    private const int ScrollFrames = 3;

    /// <summary>Screen width left clear on the right, where the editor draws the character.</summary>
    private const float PreviewClearance = 360;

    /// <summary>Group last open for each role, so reopening the window lands where the player left it.</summary>
    private static readonly ConcurrentDictionary<string, string> LastGroup = new();

    [Dependency] private MonoCoinsManager _coins = default!;

    public event Action<string>? OnNameChanged;
    public event Action<ProtoId<LoadoutGroupPrototype>, ProtoId<LoadoutPrototype>>? OnLoadoutPressed;
    public event Action<ProtoId<LoadoutGroupPrototype>, ProtoId<LoadoutPrototype>>? OnLoadoutUnpressed;

    public HumanoidCharacterProfile Profile;

    private readonly RoleLoadoutPrototype _role;
    private readonly LoadoutIconCache _icons;
    private readonly LoadoutDetailStrip _detail;
    private readonly List<LoadoutRailRow> _rows = new();
    private readonly List<LoadoutTile> _tiles = new();

    /// <summary>What the grid lists; null stands for the "Nothing" tile of the open group.</summary>
    private readonly List<LoadoutEntry?> _results = new();
    private readonly Dictionary<LoadoutGroupView, int> _hits = new();
    private readonly Dictionary<LoadoutGroupView, float> _scrolls = new();

    private RoleLoadout _loadout;
    private LoadoutGroupView? _group;
    private LoadoutTile? _hovered;
    private string _query = string.Empty;
    private string? _hint;
    private bool _updating;
    private bool _sized;
    private bool _cleaned;

    private int _scrollFrames;
    private int? _scrollIndex;
    private float _scrollOffset;
    private int _revealFrames;

    /// <summary>The role's groups and entries as the window lists them.</summary>
    public LoadoutCatalog Catalog { get; }

    /// <summary>Group shown in the grid, also the one a search returns to.</summary>
    public LoadoutGroupView? OpenedGroup => _group;

    /// <summary>Preview entities currently alive for icons.</summary>
    public int IconCount => _icons.Count;

    private bool Searching => _query.Length >= MinSearchLength;

    public WolfgateLoadoutWindow(
        HumanoidCharacterProfile profile,
        RoleLoadout loadout,
        RoleLoadoutPrototype proto,
        ICommonSession session,
        IDependencyCollection collection)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Profile = profile;
        _loadout = loadout;
        _role = proto;
        _icons = new LoadoutIconCache(collection.Resolve<IEntityManager>());
        Catalog = new LoadoutCatalog(profile, loadout, proto, session, collection);

        _detail = new LoadoutDetailStrip(_icons);
        _detail.OnRemove += entry => TrySelect(entry);
        Locker.AddChild(_detail);

        SetupName(loadout, proto);

        PickLink.AddStyleClass(StyleWolfgate.StyleClassLoadoutAttention);
        AffordLink.AddStyleClass(StyleWolfgate.StyleClassLoadoutAttention);
        PickLink.OnPressed += _ => OpenFirst(g => g.NeedsPick);
        AffordLink.OnPressed += _ =>
        {
            OpenFirst(g => g.UnaffordableCount > 0);
            ScrollToFirst(e => e.Unaffordable);
        };

        SearchBar.OnTextChanged += args => SetQuery(args.Text);
        SearchBar.OnTextEntered += _ => PickSoleMatch();
        SearchBar.OnCleared += () => SetQuery(string.Empty);
        ClearButton.OnPressed += _ => ClearSearch();
        EmptyClearButton.OnPressed += _ => ClearSearch();

        GridScroll.OnScrolled += UpdateGrid;
        GridScroll.OnResized += UpdateGrid;
        Grid.OnResized += UpdateGrid;

        _coins.BalanceUpdated += OnBalanceUpdated;
        OnClose += Cleanup;

        if (Catalog.Groups.Count == 0)
        {
            ShowNoGroups(proto);
            return;
        }

        foreach (var group in Catalog.Groups)
        {
            if (_rows.Count == 0 || _rows[^1].Group.Category != group.Category)
            {
                Rail.AddChild(new Label
                {
                    Text = Loc.GetString(LoadoutCategorizer.NameKey(group.Category)),
                    Margin = new Thickness(0, _rows.Count == 0 ? 0 : 6, 0, 0),
                    StyleClasses = { StyleWolfgate.StyleClassLoadoutRailHeading },
                });
            }

            var row = new LoadoutRailRow(group, _icons);
            row.OnPressed += _ => OnRowPressed(row);
            _rows.Add(row);
            Rail.AddChild(row);
        }

        Catalog.Sync(loadout, Balance());

        // Land on whatever needs the player first, else where they last were for this role.
        var first = Catalog.Groups.FirstOrDefault(g => g.NeedsPick || g.UnaffordableCount > 0);
        if (first == null && LastGroup.TryGetValue(proto.ID, out var last))
            first = Catalog.Groups.FirstOrDefault(g => g.Id == last);

        OpenGroup(first ?? Catalog.Groups[0]);
    }

    private void SetupName(RoleLoadout loadout, RoleLoadoutPrototype proto)
    {
        if (!proto.CanCustomizeName)
        {
            RoleNameBox.Visible = false;
            return;
        }

        var explanation = Loc.GetString(proto.NameDataset == null
            ? "loadout-name-edit-label"
            : "loadout-name-edit-label-dataset");
        var limit = Loc.GetString("loadout-name-edit-tooltip", ("max", HumanoidCharacterProfile.MaxLoadoutNameLength));

        RoleNameEdit.IsValid = text => text.Length <= HumanoidCharacterProfile.MaxLoadoutNameLength;
        RoleNameEdit.PlaceHolder = Loc.GetString(proto.NameDataset == null
            ? "wf-loadout-name-placeholder"
            : "wf-loadout-name-placeholder-dataset");
        RoleNameEdit.ToolTip = $"{explanation}\n{limit}";
        RoleNameEdit.Text = loadout.EntityName ?? string.Empty;
        RoleNameEdit.OnTextChanged += args => OnNameChanged?.Invoke(args.Text);
    }

    /// <summary>Roles such as borgs have nothing to pick: only the name field is left, in a small window.</summary>
    private void ShowNoGroups(RoleLoadoutPrototype proto)
    {
        SearchBar.Visible = false;
        ClearButton.Visible = false;
        BudgetBox.Visible = false;
        AttentionRow.Visible = false;
        Body.Visible = false;
        NoOptionsLabel.Visible = !proto.CanCustomizeName;
        RoleNameEdit.HorizontalExpand = true;
        RoleNameBox.HorizontalExpand = true;

        _sized = true;
        MinSize = new Vector2(360, 110);
        SetSize = new Vector2(460, 120);
    }

    /// <summary>Updates the window in place after the loadout changed; the scroll stays put.</summary>
    public void RefreshLoadouts(RoleLoadout loadout, ICommonSession session, IDependencyCollection collection)
    {
        _loadout = loadout;
        Sync();
    }

    private void Sync()
    {
        if (Catalog.Groups.Count == 0)
            return;

        Catalog.Sync(_loadout, Balance());
        RefreshRail();
        RefreshHeader();
        RefreshGroupHeader();
        UpdateGrid();
        UpdateDetail();
    }

    /// <summary>What the server pays from at spawn: the character's balance plus account savings.</summary>
    private long Balance()
    {
        return Profile.BankBalance + Math.Max(0, _coins.GetLastKnownBalance());
    }

    private void OnBalanceUpdated(long balance)
    {
        Sync();
    }

    #region Selecting

    /// <summary>
    /// Selects a loadout, or drops it if it is already selected, through the events the editor listens to.
    /// Returns false and says why in the hint line when the group's limits don't allow it.
    /// </summary>
    public bool TrySelect(LoadoutEntry entry)
    {
        var group = entry.Group;
        if (!_loadout.SelectedLoadouts.TryGetValue(group.Id, out var held))
            return false;

        if (held.Any(l => l.Prototype == entry.Id))
        {
            if (held.Count <= group.Min)
            {
                if (group.Fixed)
                    SetHint(Loc.GetString("wf-loadout-hint-fixed"));
                else if (group.Single)
                    SetHint(Loc.GetString("wf-loadout-hint-required"));
                else
                    SetHint(Loc.GetString("wf-loadout-hint-required-multi", ("min", group.Min)));

                return false;
            }

            _hint = null;
            OnLoadoutUnpressed?.Invoke(group.Id, entry.Id);
            return true;
        }

        // Checked after the removal above, so a locked pick that is held can still be dropped.
        if (entry.Locked)
            return false;

        // A single-pick group swaps; a full multi-pick one would silently drop its oldest pick instead.
        if (!group.Single && held.Count >= group.Max)
        {
            SetHint(Loc.GetString("wf-loadout-hint-full", ("max", group.Max)));
            return false;
        }

        _hint = null;
        OnLoadoutPressed?.Invoke(group.Id, entry.Id);
        return true;
    }

    private bool CanRemove(LoadoutEntry entry)
    {
        return _loadout.SelectedLoadouts.TryGetValue(entry.Group.Id, out var held) && held.Count > entry.Group.Min;
    }

    private void OnTilePressed(LoadoutTile tile)
    {
        if (tile.NothingFor is { } group)
        {
            _hint = null;
            foreach (var pick in group.Picks.ToList())
            {
                OnLoadoutUnpressed?.Invoke(group.Id, pick.Id);
            }
        }
        else if (tile.Entry is { } entry)
        {
            TrySelect(entry);
        }

        // The click took keyboard focus; hand it back so the player can keep typing.
        if (_query.Length > 0)
            SearchBar.GrabKeyboardFocus();
    }

    private void SetHint(string text)
    {
        _hint = text;
        RefreshGroupHeader();
    }

    #endregion

    #region Navigation

    /// <summary>Shows a group in the grid, ending any search.</summary>
    public void OpenGroup(LoadoutGroupView group)
    {
        if (Searching)
        {
            SearchBar.Clear();
            _query = string.Empty;
            ClearButton.Disabled = true;
        }
        else
        {
            RememberScroll();
        }

        _group = group;
        _hint = null;
        LastGroup[_role.ID] = group.Id;
        _revealFrames = ScrollFrames;

        ShowResults();

        // A group opens where the player left it, or the first time on a pick: one that can't be paid for if
        // there is one, as that is what brought the player here.
        if (_scrolls.TryGetValue(group, out var offset))
            ScrollTo(null, offset);
        else if (!ScrollToFirst(e => e.Unaffordable) && !ScrollToFirst(e => e.Selected))
            ScrollTo(null, 0);
    }

    private void OpenFirst(Func<LoadoutGroupView, bool> predicate)
    {
        if (Catalog.Groups.FirstOrDefault(predicate) is { } group)
            OpenGroup(group);
    }

    /// <summary>Scrolls the grid to the first listed entry that matches. Returns false when none does.</summary>
    private bool ScrollToFirst(Func<LoadoutEntry, bool> predicate)
    {
        var index = _results.FindIndex(e => e != null && predicate(e));
        if (index < 0)
            return false;

        ScrollTo(index, 0);
        return true;
    }

    private void OnRowPressed(LoadoutRailRow row)
    {
        // A row always opens its group. Clicked during a search, it lands on the group's best match.
        var match = Searching ? _results.FirstOrDefault(e => e?.Group == row.Group) : null;

        OpenGroup(row.Group);

        if (match != null)
            ScrollToFirst(e => e == match);
    }

    /// <summary>Sets the search text. Two characters or more list matches from every group.</summary>
    public void SetQuery(string text)
    {
        var was = Searching;
        if (!was)
            RememberScroll();

        _query = text.Trim().ToLowerInvariant();
        _hint = null;
        ClearButton.Disabled = text.Length == 0;

        if (!was && !Searching)
            return;

        ShowResults();

        if (Searching || _group == null)
            ScrollTo(null, 0);
        else
            ScrollTo(null, _scrolls.GetValueOrDefault(_group));
    }

    private void ClearSearch()
    {
        SearchBar.Clear();
        SetQuery(string.Empty);

        // The button took keyboard focus; whoever clears a search is about to type another.
        SearchBar.GrabKeyboardFocus();
    }

    /// <summary>Enter picks a match only when exactly one could be picked, so it never does something unexpected.</summary>
    private void PickSoleMatch()
    {
        if (!Searching)
            return;

        var open = _results.Where(e => e is { Locked: false, Selected: false }).ToList();
        if (open.Count == 1)
            TrySelect(open[0]!);
    }

    private void RememberScroll()
    {
        // A scroll request still pending means the bar has not reached where the player will be.
        if (_group != null && !Searching && _scrollFrames == 0)
            _scrolls[_group] = GridScroll.GetScrollValue().Y;
    }

    /// <summary>Asks for the grid to scroll to an entry's row, or to an offset when no index is given.</summary>
    private void ScrollTo(int? index, float offset)
    {
        _scrollIndex = index;
        _scrollOffset = offset;
        _scrollFrames = ScrollFrames;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_scrollFrames > 0)
        {
            _scrollFrames--;
            var offset = _scrollIndex is { } index ? Grid.OffsetOf(index) : _scrollOffset;
            GridScroll.SetScrollValue(new Vector2(0, offset));
        }

        if (_revealFrames > 0 && --_revealFrames == 0)
            RevealRow();

        // Hover ends here rather than when the pointer leaves a tile: the gaps between tiles are not tiles, and
        // the strip would flicker back to the picks on every crossing.
        if (_hovered != null && UserInterfaceManager.CurrentlyHovered is not LoadoutTile && UserInterfaceManager.CurrentlyHovered != GridScroll)
        {
            _hovered = null;
            UpdateDetail();
        }
    }

    /// <summary>Scrolls the rail so the open group's row is on screen.</summary>
    private void RevealRow()
    {
        if (_rows.FirstOrDefault(r => r.Group == _group) is not { } row)
            return;

        // A row that is first under its heading brings the heading along.
        var index = row.GetPositionInParent();
        var top = index > 0 && Rail.GetChild(index - 1) is Label heading ? heading.Position.Y : row.Position.Y;
        var bottom = row.Position.Y + row.Height;
        var scroll = RailScroll.GetScrollValue().Y;

        if (top < scroll)
            RailScroll.SetScrollValue(new Vector2(0, top));
        else if (bottom > scroll + RailScroll.Height)
            RailScroll.SetScrollValue(new Vector2(0, bottom - RailScroll.Height));
    }

    #endregion

    #region Refreshing

    /// <summary>Fills the list the grid shows: search matches, or the open group's entries.</summary>
    private void ShowResults()
    {
        _results.Clear();
        _hits.Clear();

        if (Searching)
        {
            foreach (var entry in Catalog.Search(_query))
            {
                _results.Add(entry);
                _hits[entry.Group] = _hits.GetValueOrDefault(entry.Group) + 1;
            }
        }
        else if (_group != null)
        {
            if (_group.HasNothingTile)
                _results.Add(null);

            _results.AddRange(_group.Entries);
        }

        Grid.CellHeight = Searching ? LoadoutTile.CaptionedHeight : LoadoutTile.TileHeight;
        Grid.TotalItemCount = _results.Count;

        GridScroll.Visible = _results.Count > 0;
        EmptyBox.Visible = _results.Count == 0;
        EmptyLabel.Text = Loc.GetString("wf-loadout-search-empty", ("query", _query));

        RefreshRail();
        RefreshHeader();
        RefreshGroupHeader();
        UpdateGrid();
        UpdateDetail();
    }

    private void RefreshRail()
    {
        foreach (var row in _rows)
        {
            row.Refresh(Searching ? _hits.GetValueOrDefault(row.Group) : null);
            row.Pressed = !Searching && row.Group == _group;
        }
    }

    private void RefreshHeader()
    {
        var unaffordable = Catalog.Groups.Sum(g => g.UnaffordableCount);
        var needs = Catalog.Groups.Count(g => g.NeedsPick);

        if (Catalog.Cost <= 0)
        {
            BudgetLabel.Text = Loc.GetString("wf-loadout-budget-free");
            BudgetBar.Value = 0;
            LoadoutTones.Set(BudgetLabel, LoadoutTone.Muted);
        }
        else
        {
            BudgetLabel.Text = Loc.GetString("wf-loadout-budget",
                ("cost", BankSystemExtensions.ToSpesoString(Catalog.Cost)),
                ("balance", BankSystemExtensions.ToSpesoString(Catalog.Balance)));
            BudgetBar.Value = Catalog.Balance > 0 ? Math.Clamp((float) Catalog.Cost / Catalog.Balance, 0, 1) : 1;
            LoadoutTones.Set(BudgetLabel, Catalog.Cost > Catalog.Balance ? LoadoutTone.Danger : LoadoutTone.Normal);
        }

        var breakdown = Loc.GetString("frontier-loadout-balance",
            ("balance", BankSystemExtensions.ToSpesoString(Profile.BankBalance)),
            ("savings", BankSystemExtensions.ToSpesoString(Math.Max(0, _coins.GetLastKnownBalance()))));
        BudgetBox.ToolTip = $"{Loc.GetString("wf-loadout-budget-tooltip")}\n{breakdown}";

        PickLink.Visible = needs > 0;
        PickLink.Text = Loc.GetString("wf-loadout-attention-pick", ("count", needs));
        AffordLink.Visible = unaffordable > 0;
        AffordLink.Text = Loc.GetString("wf-loadout-attention-unaffordable", ("count", unaffordable));
        ReadyLabel.Visible = needs == 0 && unaffordable == 0;

        PointsLabel.Visible = _role.Points != null && _loadout.Points != null;
        if (PointsLabel.Visible)
        {
            PointsLabel.Text = Loc.GetString("wf-loadout-points",
                ("count", _loadout.Points!.Value),
                ("max", _role.Points!.Value));
        }
    }

    private void RefreshGroupHeader()
    {
        HintLabel.Text = _hint ?? string.Empty;
        LoadoutTones.Set(HintLabel, _hint != null ? LoadoutTone.Caution : LoadoutTone.Muted);

        if (Searching)
        {
            GroupHeading.Text = Loc.GetString("wf-loadout-search-heading");
            GroupLimit.Text = string.Empty;
            GroupCount.Text = Loc.GetString("wf-loadout-search-count", ("count", _results.Count));

            if (_hint == null && _results.Count > 0)
                HintLabel.Text = Loc.GetString("wf-loadout-search-hint");

            return;
        }

        if (_group is not { } group)
            return;

        GroupHeading.Text = group.Label;

        if (group.Fixed)
            GroupLimit.Text = Loc.GetString("wf-loadout-limit-fixed");
        else if (group.Single)
            GroupLimit.Text = Loc.GetString(group.Optional ? "wf-loadout-limit-optional" : "wf-loadout-limit-required");
        else
        {
            GroupLimit.Text = Loc.GetString(group.Optional ? "wf-loadout-limit-upto" : "wf-loadout-limit-atleast",
                ("min", group.Min),
                ("max", group.Max),
                ("count", group.Picks.Count));
        }

        var locked = group.Entries.Count(e => e.Locked);
        GroupCount.Text = locked == 0
            ? Loc.GetString("wf-loadout-group-count", ("count", group.Entries.Count))
            : Loc.GetString("wf-loadout-group-count-locked", ("count", group.Entries.Count), ("locked", locked));

        // A group locked as a whole says why once here, rather than on every tile.
        if (_hint == null && group.AllLocked)
        {
            var reasons = group.Entries.Select(e => e.Reason?.ToString()).Distinct().ToList();
            if (reasons.Count == 1 && reasons[0] is { } reason)
                HintLabel.Text = Loc.GetString("wf-loadout-hint-all-locked", ("reason", reason));
        }
    }

    /// <summary>Points the pooled tiles at the rows on screen.</summary>
    private void UpdateGrid()
    {
        if (_updating)
            return;

        _updating = true;
        try
        {
            var columns = Math.Max(1, Grid.Columns);
            var offset = Math.Max(-Grid.Position.Y, 0);
            var startRow = (int) (offset / Grid.RowHeight);
            var rows = (int) Math.Ceiling(GridScroll.Height / Grid.RowHeight) + 1;
            var capacity = Math.Max(columns, rows * columns);

            while (_tiles.Count < capacity)
            {
                var tile = new LoadoutTile(_icons);
                tile.OnPressed += _ => OnTilePressed(tile);
                tile.OnMouseEntered += _ =>
                {
                    _hovered = tile;
                    UpdateDetail();
                };
                _tiles.Add(tile);
                Grid.AddChild(tile);
            }

            var start = startRow * columns;
            Grid.StartRow = startRow;

            for (var i = 0; i < _tiles.Count; i++)
            {
                var tile = _tiles[i];
                var index = start + i;

                if (i >= capacity || index >= _results.Count)
                    tile.Unbind();
                else if (_results[index] is not { } entry)
                    tile.BindNothing(_group!);
                else
                    tile.Bind(entry, Searching ? entry.Group.Label : null, Full(entry));
            }

            // The tile under the pointer may show another item now.
            if (_hovered != null)
                UpdateDetail();
        }
        finally
        {
            _updating = false;
        }
    }

    /// <summary>Whether an entry can't be added because its multi-pick group is at its limit.</summary>
    private static bool Full(LoadoutEntry entry)
    {
        var group = entry.Group;
        return !group.Single && !entry.Selected && !entry.Locked && group.Picks.Count + group.Stale >= group.Max;
    }

    private void UpdateDetail()
    {
        if (_hovered is { Visible: true, Entry: { } entry })
        {
            _detail.ShowEntry(entry);
            return;
        }

        if (Searching)
            _detail.ShowPicks(null, Loc.GetString("wf-loadout-detail-idle"), CanRemove);
        else
            _detail.ShowPicks(_group, null, CanRemove);
    }

    #endregion

    /// <summary>Sizes the window to the screen once, keeping the editor's character preview clear.</summary>
    protected override void Opened()
    {
        base.Opened();

        if (_sized || Parent == null)
            return;

        _sized = true;
        SetSize = new Vector2(
            Math.Clamp(Parent.Width - PreviewClearance, MinSize.X, SetSize.X),
            Math.Clamp(Parent.Height - 40, MinSize.Y, SetSize.Y));

        // The caller centres the window from its desired size right after this.
        Measure(Vector2Helpers.Infinity);
    }

    /// <summary>
    /// Deletes the preview entities. Run on close and on dispose, since the editor disposes without closing,
    /// and never on leaving the tree, since popping the window out re-parents it.
    /// </summary>
    private void Cleanup()
    {
        if (_cleaned)
            return;

        _cleaned = true;
        _coins.BalanceUpdated -= OnBalanceUpdated;
        _icons.Clear();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
            Cleanup();
    }
}
