using System.Linq;
using System.Numerics;
using Content.Client._WF.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client._WF.Spawning;

/// <summary>
/// Categorised entity spawn menu in the style of SS13's spawn panel: a folder tree on the left, a virtualised
/// grid of results on the right, and the engine's placement controls along the bottom.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WolfgateSpawnWindow : FancyWindow
{
    /// <summary>How many entries the Recent folder remembers.</summary>
    private const int RecentLimit = 40;

    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private IComponentFactory _factory = default!;

    private readonly WolfgateSpawnCatalog _catalog;
    private readonly List<WolfgateSpawnNodeButton> _nodes = new();
    private readonly List<WolfgateSpawnTile> _tiles = new();
    private readonly List<WolfgateSpawnEntry> _results = new();
    private readonly int[] _matchCounts = new int[Enum.GetValues<WfSpawnCategory>().Length];

    /// <summary>Groups start collapsed, and stay how the player left them for the session.</summary>
    private static readonly HashSet<WfSpawnGroup> Expanded = new();

    private readonly HashSet<string> _favourites = new();
    private readonly List<string> _recent = new();
    private readonly HashSet<string> _recentSet = new();

    private WolfgateSkin _skin;
    private WfSpawnNode _node = WfSpawnNode.All;
    private string _search = string.Empty;
    private string? _selectedId;
    private bool _updating;

    /// <summary>Raised when a tile is picked, with null when the selection is cleared.</summary>
    public event Action<WolfgateSpawnEntry?>? OnEntrySelected;

    /// <summary>Raised when the replace button is toggled.</summary>
    public event Action<bool>? OnReplaceToggled;

    /// <summary>Raised when the erase button is toggled.</summary>
    public event Action<bool>? OnEraseToggled;

    /// <summary>Raised with the placement mode index picked in the override dropdown.</summary>
    public event Action<int>? OnOverrideSelected;

    public WolfgateSpawnWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _skin = WolfgateSkins.Get(_cfg.GetCVar(WolfgateCVars.UiStyle));
        _catalog = new WolfgateSpawnCatalog(_cfg, _proto, _factory);

        foreach (var id in _cfg.GetCVar(WolfgateCVars.SpawnFavourites)
                     .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            _favourites.Add(id);
        }

        SearchBar.OnTextChanged += args =>
        {
            var previous = _search;
            _search = args.Text.Trim().ToLowerInvariant();
            ClearButton.Disabled = _search.Length == 0;

            // Starting a search looks everywhere: nobody types into a search box hoping to be told the thing they
            // want is not in the folder they happen to have open. Narrowing afterwards is still a click away, and
            // refining the query keeps whatever folder they narrowed to.
            if (previous.Length == 0 && _search.Length > 0)
                _node = WfSpawnNode.All;

            GridScroll.SetScrollValue(Vector2.Zero);
            Refresh();
        };
        SearchBar.OnTextEntered += _ => SelectFirstResult();
        ClearButton.OnPressed += _ =>
        {
            SearchBar.Clear();
            _search = string.Empty;
            ClearButton.Disabled = true;
            GridScroll.SetScrollValue(Vector2.Zero);
            Refresh();
        };

        FavouriteButton.OnPressed += _ =>
        {
            if (_selectedId != null && _catalog.Find(_selectedId) is { } entry)
                ToggleFavourite(entry);
        };

        ReplaceButton.OnToggled += args => OnReplaceToggled?.Invoke(args.Pressed);
        EraseButton.OnToggled += args => OnEraseToggled?.Invoke(args.Pressed);
        OverrideMenu.OnItemSelected += args =>
        {
            OverrideMenu.SelectId(args.Id);
            OnOverrideSelected?.Invoke(args.Id);
        };

        GridScroll.OnScrolled += UpdateGrid;
        Grid.OnResized += UpdateGrid;

        BuildTree();
        Refresh();
        UpdateSelectionPanel();
    }

    /// <summary>Placement mode the override dropdown currently shows.</summary>
    public int OverrideId => OverrideMenu.SelectedId;

    /// <summary>Fills the override dropdown with the placement mode names, indexed by position.</summary>
    public void SetPlacementModes(string[] modes)
    {
        OverrideMenu.Clear();
        for (var i = 0; i < modes.Length; i++)
        {
            OverrideMenu.AddItem(modes[i], i);
        }
    }

    /// <summary>Shows the current placement direction.</summary>
    public void SetRotation(string text) => RotationLabel.Text = text;

    /// <summary>Sets the replace button without raising its event.</summary>
    public void SetReplace(bool pressed) => ReplaceButton.Pressed = pressed;

    /// <summary>Sets the erase button without raising its event; erasing disables the override dropdown.</summary>
    public void SetErase(bool pressed)
    {
        EraseButton.Pressed = pressed;
        OverrideMenu.Disabled = pressed;
    }

    /// <summary>Drops the highlight without telling the controller, for when placement was cleared elsewhere.</summary>
    public void ClearSelection()
    {
        _selectedId = null;
        UpdateGrid();
        UpdateSelectionPanel();
    }

    /// <summary>Gives the search bar keyboard focus.</summary>
    public void FocusSearch() => SearchBar.GrabKeyboardFocus();

    /// <summary>Re-reads the prototypes, for example after a prototype hot reload.</summary>
    public void Reload()
    {
        _catalog.Invalidate();
        Refresh();

        // A reload can delete whatever was selected, and placing a prototype that no longer exists does nothing.
        if (_selectedId != null && _catalog.Find(_selectedId) == null)
        {
            _selectedId = null;
            OnEntrySelected?.Invoke(null);
            UpdateGrid();
        }

        UpdateSelectionPanel();
    }

    protected override void Opened()
    {
        base.Opened();

        var skin = WolfgateSkins.Get(_cfg.GetCVar(WolfgateCVars.UiStyle));
        if (skin != _skin)
        {
            _skin = skin;
            foreach (var tile in _tiles)
            {
                tile.SetSkin(skin);
            }

            // Node buttons bake their palette in at construction, so the tree has to be rebuilt to restyle.
            BuildTree();
            Refresh();
            UpdateSelectionPanel();
            return;
        }

        UpdateGrid();
    }

    private void BuildTree()
    {
        NodeList.RemoveAllChildren();
        _nodes.Clear();

        AddNode(WfSpawnNode.All, Loc.GetString("wf-spawn-node-all"), _skin.Accent, folder: true);
        AddNode(WfSpawnNode.Favourites, Loc.GetString("wf-spawn-node-favourites"), _skin.Caution, folder: true);
        AddNode(WfSpawnNode.Recent, Loc.GetString("wf-spawn-node-recent"), _skin.TextMuted, folder: true);

        foreach (var (group, categories) in WfSpawnCategories.Tree)
        {
            var accent = WfSpawnCategories.GroupColor(group, _skin);
            AddNode(WfSpawnNode.Of(group), WfSpawnCategories.GroupName(group), accent, folder: true);

            foreach (var category in categories)
            {
                AddNode(WfSpawnNode.Of(category), WfSpawnCategories.CategoryName(category), accent, folder: false);
            }
        }
    }

    private void AddNode(WfSpawnNode node, string text, Color accent, bool folder)
    {
        var button = new WolfgateSpawnNodeButton(node, text, accent, folder, _skin);
        button.OnPressed += _ => OnNodePressed(button);
        _nodes.Add(button);
        NodeList.AddChild(button);
    }

    private void OnNodePressed(WolfgateSpawnNodeButton button)
    {
        var node = button.Node;

        // A folder that is already selected collapses; otherwise selecting one opens it.
        if (node.Kind == WfSpawnNodeKind.Group && _node == node)
        {
            if (!Expanded.Remove(node.Group))
                Expanded.Add(node.Group);
        }
        else if (node.Kind == WfSpawnNodeKind.Group)
        {
            Expanded.Add(node.Group);
        }

        _node = node;
        GridScroll.SetScrollValue(Vector2.Zero);
        Refresh();
    }

    /// <summary>Recomputes the result set, the sidebar counts and the grid.</summary>
    private void Refresh()
    {
        var searching = _search.Length > 0;

        Array.Clear(_matchCounts);
        var favouriteMatches = 0;
        var recentMatches = 0;
        var totalMatches = 0;

        foreach (var entry in _catalog.All)
        {
            if (searching && !entry.Search.Contains(_search, StringComparison.Ordinal))
                continue;

            _matchCounts[(int) entry.Category]++;
            totalMatches++;

            if (_favourites.Contains(entry.Id))
                favouriteMatches++;
            if (_recentSet.Contains(entry.Id))
                recentMatches++;
        }

        var groupCounts = new int[Enum.GetValues<WfSpawnGroup>().Length];
        foreach (var (group, categories) in WfSpawnCategories.Tree)
        {
            foreach (var category in categories)
            {
                groupCounts[(int) group] += _matchCounts[(int) category];
            }
        }

        _results.Clear();
        foreach (var entry in Source())
        {
            if (!searching || entry.Search.Contains(_search, StringComparison.Ordinal))
                _results.Add(entry);
        }

        foreach (var button in _nodes)
        {
            var node = button.Node;
            var count = node.Kind switch
            {
                WfSpawnNodeKind.All => totalMatches,
                WfSpawnNodeKind.Favourites => favouriteMatches,
                WfSpawnNodeKind.Recent => recentMatches,
                WfSpawnNodeKind.Group => groupCounts[(int) node.Group],
                _ => _matchCounts[(int) node.Category],
            };

            button.SetCount(count, searching);
            button.SetActive(node == _node);

            // A search opens every folder that has something in it, so matches are never hidden behind a fold.
            var expanded = Expanded.Contains(node.Group) || (searching && groupCounts[(int) node.Group] > 0);
            if (node.Kind == WfSpawnNodeKind.Group)
                button.SetExpanded(expanded);
            else if (node.Kind == WfSpawnNodeKind.Category)
                button.Visible = expanded;
        }

        HeadingLabel.Text = NodeName(_node);
        CountLabel.Text = searching
            ? Loc.GetString("wf-spawn-count-search", ("count", _results.Count))
            : Loc.GetString("wf-spawn-count", ("count", _results.Count));

        EmptyLabel.Visible = _results.Count == 0;
        EmptyLabel.Text = EmptyText();

        Grid.TotalItemCount = _results.Count;
        UpdateGrid();
    }

    private IEnumerable<WolfgateSpawnEntry> Source()
    {
        switch (_node.Kind)
        {
            case WfSpawnNodeKind.Favourites:
                return _catalog.All.Where(e => _favourites.Contains(e.Id));
            case WfSpawnNodeKind.Recent:
                // Most recent first, which is the one order the player actually wants here.
                return _recent.Select(_catalog.Find).Where(e => e != null).Select(e => e!);
            case WfSpawnNodeKind.Group:
                return _catalog.Group(_node.Group);
            case WfSpawnNodeKind.Category:
                return _catalog.Category(_node.Category);
            default:
                return _catalog.All;
        }
    }

    private string NodeName(WfSpawnNode node)
    {
        return node.Kind switch
        {
            WfSpawnNodeKind.All => Loc.GetString("wf-spawn-node-all"),
            WfSpawnNodeKind.Favourites => Loc.GetString("wf-spawn-node-favourites"),
            WfSpawnNodeKind.Recent => Loc.GetString("wf-spawn-node-recent"),
            WfSpawnNodeKind.Group => WfSpawnCategories.GroupName(node.Group),
            _ => $"{WfSpawnCategories.GroupName(node.Group)} / {WfSpawnCategories.CategoryName(node.Category)}",
        };
    }

    private string EmptyText()
    {
        if (_search.Length > 0)
            return Loc.GetString("wf-spawn-empty-search", ("search", _search));

        return _node.Kind switch
        {
            WfSpawnNodeKind.Favourites => Loc.GetString("wf-spawn-empty-favourites"),
            WfSpawnNodeKind.Recent => Loc.GetString("wf-spawn-empty-recent"),
            _ => Loc.GetString("wf-spawn-empty"),
        };
    }

    /// <summary>Points the pooled tiles at the rows currently on screen.</summary>
    private void UpdateGrid()
    {
        if (_updating)
            return;

        _updating = true;
        try
        {
            var columns = Math.Max(1, Grid.Columns);
            var rowHeight = WolfgateSpawnGrid.RowHeight;
            var viewHeight = Grid.Parent?.Height ?? 0;
            var offset = Math.Max(-Grid.Position.Y, 0);

            var startRow = (int) (offset / rowHeight);
            var rows = (int) Math.Ceiling(viewHeight / rowHeight) + 1;
            var capacity = Math.Max(columns, rows * columns);

            while (_tiles.Count < capacity)
            {
                var tile = new WolfgateSpawnTile(_skin);
                tile.OnPressed += _ => OnTilePressed(tile);
                tile.OnFavouriteToggled += ToggleFavourite;
                _tiles.Add(tile);
                Grid.AddChild(tile);
            }

            var start = startRow * columns;
            Grid.StartRow = startRow;

            for (var i = 0; i < _tiles.Count; i++)
            {
                var index = start + i;
                if (i >= capacity || index >= _results.Count)
                {
                    _tiles[i].SetEntry(null, null, Color.White, false, false);
                    continue;
                }

                var entry = _results[index];
                var accent = WfSpawnCategories.GroupColor(WfSpawnCategories.GroupFor(entry.Category), _skin);
                _tiles[i].SetEntry(
                    entry,
                    Icon(entry),
                    accent,
                    _favourites.Contains(entry.Id),
                    entry.Id == _selectedId);
            }
        }
        finally
        {
            _updating = false;
        }
    }

    private void OnTilePressed(WolfgateSpawnTile tile)
    {
        if (tile.Entry is not { } entry)
            return;

        if (_selectedId == entry.Id)
        {
            _selectedId = null;
            OnEntrySelected?.Invoke(null);
        }
        else
        {
            _selectedId = entry.Id;
            RememberRecent(entry.Id);
            OnEntrySelected?.Invoke(entry);
        }

        UpdateGrid();
        UpdateSelectionPanel();
    }

    private void SelectFirstResult()
    {
        if (_results.Count == 0)
            return;

        var entry = _results[0];
        _selectedId = entry.Id;
        RememberRecent(entry.Id);
        OnEntrySelected?.Invoke(entry);
        UpdateGrid();
        UpdateSelectionPanel();
    }

    private void RememberRecent(string id)
    {
        _recent.Remove(id);
        _recent.Insert(0, id);
        _recentSet.Add(id);

        if (_recent.Count > RecentLimit)
        {
            foreach (var dropped in _recent.GetRange(RecentLimit, _recent.Count - RecentLimit))
            {
                _recentSet.Remove(dropped);
            }

            _recent.RemoveRange(RecentLimit, _recent.Count - RecentLimit);
        }
    }

    private void ToggleFavourite(WolfgateSpawnEntry entry)
    {
        if (!_favourites.Remove(entry.Id))
            _favourites.Add(entry.Id);

        _cfg.SetCVar(WolfgateCVars.SpawnFavourites, string.Join(',', _favourites));
        _cfg.SaveToFile();

        Refresh();
        UpdateSelectionPanel();
    }

    /// <summary>Cached prototype icon. Null before the sprite system exists, which only happens outside a game.</summary>
    private Texture? Icon(WolfgateSpawnEntry entry)
    {
        if (!_entMan.EntitySysManager.TryGetEntitySystem<SpriteSystem>(out var sprite))
            return null;

        return sprite.GetPrototypeIcon(entry.Prototype).Default;
    }

    private void UpdateSelectionPanel()
    {
        var entry = _selectedId == null ? null : _catalog.Find(_selectedId);

        FavouriteButton.Disabled = entry == null;
        SelectionIcon.Texture = entry == null ? null : Icon(entry);

        SelectionName.Text = entry?.Name ?? Loc.GetString("wf-spawn-nothing-selected");
        SelectionName.FontColorOverride = entry == null ? _skin.TextMuted : _skin.Text;
        SelectionId.Text = entry?.Id ?? string.Empty;

        FavouriteButton.Text = entry != null && _favourites.Contains(entry.Id)
            ? Loc.GetString("wf-spawn-unfavourite")
            : Loc.GetString("wf-spawn-favourite");
    }
}
