using Content.Client.Message;
using Content.Shared._WF.Roadmap;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Roadmap;

/// <summary>
/// A roadmap item: a button that expands its description, with a bar coloured by state.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RoadmapItem : Control
{
    private RoadmapItemState _itemState;
    private string? _description;

    /// <summary>Sets the colour bar and the status line.</summary>
    public RoadmapItemState ItemState
    {
        get => _itemState;
        set
        {
            _itemState = value;
            var color = StateColorFor(value);
            ((StyleBoxFlat) StateColor.PanelOverride!).BackgroundColor = color;
            StateText.Text = Loc.GetString(StateLocFor(value));
            StateText.FontColorOverride = color;
        }
    }

    /// <summary>Title on the item's button.</summary>
    public string? HeaderText
    {
        get => HeaderButton.Text;
        set => HeaderButton.Text = value;
    }

    /// <summary>Description markup, shown when the item is expanded.</summary>
    public string? Description
    {
        get => _description;
        set
        {
            _description = value;
            Contents.SetMarkupPermissive($"[font size=11]{value ?? string.Empty}[/font]");
        }
    }

    /// <summary>Whether the description is showing.</summary>
    public bool Expanded => Details.Visible;

    public RoadmapItem()
    {
        RobustXamlLoader.Load(this);
        HeaderButton.OnPressed += _ => Details.Visible = !Details.Visible;
        ItemState = RoadmapItemState.Planned;
    }

    /// <summary>Colour of the bar and status line for a state.</summary>
    public static Color StateColorFor(RoadmapItemState state)
    {
        return state switch
        {
            RoadmapItemState.Planned => Color.Red,
            RoadmapItemState.InProgress => Color.FromHex("#20C9FF"),
            RoadmapItemState.Partial => Color.Yellow,
            RoadmapItemState.Complete => Color.Green,
            _ => Color.Transparent,
        };
    }

    /// <summary>Fluent ID of the status line for a state.</summary>
    public static string StateLocFor(RoadmapItemState state)
    {
        return state switch
        {
            RoadmapItemState.InProgress => "wf-roadmap-state-in-progress",
            RoadmapItemState.Partial => "wf-roadmap-state-partial",
            RoadmapItemState.Complete => "wf-roadmap-state-complete",
            _ => "wf-roadmap-state-planned",
        };
    }
}
