using System.Globalization;
using System.Linq;
using Content.Client.Credits;
using Content.Client.Message;
using Content.Client.Stylesheets;
using Content.Shared._WF.Roadmap;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client._WF.Roadmap;

/// <summary>
/// The roadmap: server links, then one column per <see cref="RoadmapColumnPrototype"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class RoadmapWindow : DefaultWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private IUriOpener _uri = default!;

    public RoadmapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var year = DateTime.UtcNow.Year.ToString(CultureInfo.InvariantCulture);
        Header.SetMarkup(Loc.GetString("wf-roadmap-header", ("year", year)));

        SetUpLink(DiscordButton, CCVars.InfoLinksDiscord);
        SetUpLink(PatreonButton, CCVars.InfoLinksPatreon);
        CreditsButton.StyleClasses.Add(StyleBase.ButtonCaution);
        CreditsButton.OnPressed += _ => new CreditsWindow().OpenCentered();

        var columns = _proto.EnumeratePrototypes<RoadmapColumnPrototype>()
            .OrderBy(c => c.Order)
            .ThenBy(c => c.ID, StringComparer.Ordinal);

        foreach (var column in columns)
        {
            Columns.AddChild(CreateColumn(column));
        }
    }

    /// <summary>Shows a link button only when the server sets its cvar.</summary>
    private void SetUpLink(Button button, CVarDef<string> cvar)
    {
        var link = _cfg.GetCVar(cvar);
        if (link.Length == 0)
            return;

        button.StyleClasses.Add(StyleBase.ButtonCaution);
        button.Visible = true;
        button.OnPressed += _ => _uri.OpenUri(link);
    }

    private static BoxContainer CreateColumn(RoadmapColumnPrototype column)
    {
        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 20, 0),
        };

        box.AddChild(new RoadmapVersionHeader { Text = Loc.GetString(column.Name) });

        foreach (var entry in column.Items)
        {
            box.AddChild(new RoadmapItem
            {
                HeaderText = Loc.GetString(entry.Name),
                Description = entry.Description is { } description ? Loc.GetString(description) : null,
                ItemState = entry.State,
            });
        }

        return box;
    }
}
