using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Audio.InternetSound;

/// <summary>
/// Small radio shown at the top of every player's screen for an admin internet sound: what it is, who sent it,
/// volume and stop. Opens in a loading state until the audio has arrived.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class InternetSoundPopup : DefaultWindow
{
    /// <summary>
    /// New volume, 0 to 1, while the slider moves.
    /// </summary>
    public event Action<float>? VolumeChanged;

    public event Action? VolumeReleased;
    public event Action? StopPressed;

    private readonly string _admin;

    public InternetSoundPopup(string title, string admin, float volume)
    {
        RobustXamlLoader.Load(this);
        _admin = admin;

        SoundLabel.Text = title;
        SoundLabel.ToolTip = title;
        StatusLabel.Text = Status("wf-internet-sound-popup-loading");

        SetVolume(volume);
        VolumeSlider.OnValueChanged += _ =>
        {
            UpdateVolumeLabel();
            VolumeChanged?.Invoke(VolumeSlider.Value / 100f);
        };
        VolumeSlider.OnReleased += _ => VolumeReleased?.Invoke();
        StopButton.OnPressed += _ => StopPressed?.Invoke();
    }

    /// <summary>
    /// Switches the status line from loading to playing.
    /// </summary>
    public void SetPlaying()
    {
        StatusLabel.Text = Status("wf-internet-sound-popup-played");
    }

    /// <summary>
    /// A stealth sound has no admin name, so it gets the line that doesn't credit anyone.
    /// </summary>
    private string Status(string key)
    {
        return _admin.Length > 0
            ? Loc.GetString(key, ("admin", _admin))
            : Loc.GetString($"{key}-stealth");
    }

    /// <summary>
    /// Moves the slider without echoing a change back.
    /// </summary>
    public void SetVolume(float volume)
    {
        VolumeSlider.SetValueWithoutEvent(volume * 100f);
        UpdateVolumeLabel();
    }

    private void UpdateVolumeLabel()
    {
        VolumeLabel.Text = $"{VolumeSlider.Value:0}%";
    }
}
