#!/usr/bin/env python3
"""Generates the Wolfgate module docs and checks the modularity rules in AGENTS.md.

A module is a first-level folder under one of the _WF roots, or an external module listed in modules.yml. Each module
README gets a generated section listing the module's files and the files outside _WF its WOLFGATE markers (and its
unmarked entries) edit; Docs/_WF/NONMODULAR.md lists the standalone edits: untagged markers and unmarked entries
without a module.

    python Tools/_WF/Ci/modules.py --write            regenerate the docs, creating missing READMEs
    python Tools/_WF/Ci/modules.py --check            fail if the docs are stale or a rule is broken
    python Tools/_WF/Ci/modules.py --pr-check <ref>   fail if a file changed since <ref> outside _WF has no marker

Reports are cut to 20 lines per section; --all prints everything. Needs PyYAML (pip install pyyaml).
"""
from __future__ import annotations

import argparse
import bisect
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import quote

REPO = Path(__file__).resolve().parents[3]
CONFIG = "Tools/_WF/Ci/modules.yml"
NONMODULAR = "Docs/_WF/NONMODULAR.md"
WRITE_COMMAND = "python Tools/_WF/Ci/modules.py --write"
GEN_START = "<!-- WOLFGATE-GENERATED START -->"
GEN_END = "<!-- WOLFGATE-GENERATED END -->"
GEN_NOTE = f"<!-- Generated by {WRITE_COMMAND}. Don't edit by hand. -->"

# The module roots from the table in AGENTS.md.
ROOTS = (
    "Content.Client/_WF",
    "Content.Server/_WF",
    "Content.Shared/_WF",
    "Content.IntegrationTests/Tests/_WF",
    "Content.Tests/_WF",
    "Resources/Prototypes/_WF",
    "Resources/Locale/en-US/_WF",
    "Resources/Textures/_WF",
    "Resources/Audio/_WF",
    "Resources/Maps/_WF",
    "Resources/SharedMaps/_WF",
    "Resources/ServerInfo/_WF",
    "Tools/_WF",
    "Docs/_WF",
)
# Where a module README goes, first root the module has files in; Docs/_WF when it has no C#.
README_ROOTS = ("Content.Server/_WF", "Content.Shared/_WF", "Content.Client/_WF", "Docs/_WF")

# File list headings, by path prefix, in output order.
AREAS = (
    ("Content.Server/", "Server"),
    ("Content.Shared/", "Shared"),
    ("Content.Client/", "Client"),
    ("Content.IntegrationTests/", "Integration tests"),
    ("Content.Tests/", "Unit tests"),
    ("Resources/Prototypes/", "Prototypes"),
    ("Resources/Locale/", "Localization"),
    ("Resources/Textures/", "Textures"),
    ("Resources/Audio/", "Audio"),
    ("Resources/Maps/", "Maps"),
    ("Resources/SharedMaps/", "Shared maps"),
    ("Resources/ServerInfo/", "Guidebook"),
    ("Tools/", "Tools"),
    ("Docs/", "Docs"),
)
AREA_ORDER = [name for _, name in AREAS] + ["Other"]

# Never scanned for markers: they describe the markers rather than carry them.
NOT_SCANNED = {"AGENTS.md", "CLAUDE.md"}
# Changed files the pull request check ignores: generated files and the agent guidelines.
PR_EXEMPT_PREFIXES = ("Resources/Changelog/", "Content.Server.Database/Migrations/")
PR_EXEMPT_FILES = {"AGENTS.md", "CLAUDE.md"}

MODULE_NAME = re.compile(r"[A-Z][A-Za-z0-9]*")
WORD = re.compile(r"(?<![\w-])WOLFGATE(?![\w-])")
# What follows WOLFGATE: an optional (Module), START or END, ": reason", then the end of the line or of the comment
# (guidebook XML puts content right after "-->").
GRAMMAR = re.compile(
    r"(?:\((?P<module>[^()]*)\))?(?:\s+(?P<kind>START|END))?(?:\s*:\s*(?P<reason>.*?))?\s*(?:(?:-->|\*/).*)?")
# A comment opener somewhere before WOLFGATE on the line.
IN_COMMENT = re.compile(r"//|#|<!--|/\*|^\s*\*|^\s*;|(?:^|\s)--\s")
# What may sit right before a marker: a comment opener, or a separator after another fork's note ("HL change; ").
LEAD = re.compile(r"(?:(?:^|\s)(?://+|#+|<!--|/\*+|\*|;|--)|[,;>])\s*$")
# WOLFGATE right after a comment opener (or an old "End WOLFGATE"), so a remainder that doesn't parse is broken.
AFTER_OPENER = re.compile(r"(?:^|\s)(?://+|#+|<!--|/\*+)\s*(?:(?i:end|start)\s+)?$")

REPORT_LIMIT = 20
UNTRACKED_SCAN_LIMIT = 5 * 1024 * 1024
# How far an XML marker's reason may run on past its line before the comment must close.
XML_CONTINUATION_LIMIT = 20
TODO_OVERVIEW = "TODO: what the module does, how players or admins use it and its main entry points."


@dataclass
class Module:
    name: str
    files: list = field(default_factory=list)
    folders: set = field(default_factory=set)
    readme: str | None = None
    globs: re.Pattern | None = None


@dataclass
class Unmarked:
    path: str
    module: str | None
    reason: str
    pattern: re.Pattern | None


class Report:
    """Problems grouped into titled sections, printed in the order of HINTS."""

    HINTS = {
        "Files outside a module folder": "Every _WF file goes in <root>/<Module>/, a root from the table in AGENTS.md.",
        "Module folders": "Module folders are PascalCase and name the module the same way in every area.",
        "Markers": ("Grammar: WOLFGATE[(<Module>)][ START| END][: reason]; END carries no module, and an untagged "
                    "marker needs a reason."),
        "modules.yml": None,
        "Module READMEs": f"{WRITE_COMMAND} creates missing READMEs with a TODO overview; replace it by hand.",
        "Stale generated docs": f"Run {WRITE_COMMAND} and commit the result.",
        "Changed files outside _WF without a marker": (
            "Mark the edit (// WOLFGATE(<Module>): reason) or, if the file can't hold a comment, list it under "
            f"unmarked in {CONFIG}."),
    }

    def __init__(self):
        self.sections: dict[str, list[tuple[str, str | None, int | None]]] = {}

    def add(self, section, text, path=None, line=None):
        self.sections.setdefault(section, []).append((text, path, line))

    def count(self):
        return sum(len(items) for items in self.sections.values())

    def print(self, limit):
        annotate = os.environ.get("GITHUB_ACTIONS") == "true"
        order = list(self.HINTS)
        for title, items in sorted(self.sections.items(), key=lambda s: order.index(s[0])):
            print(f"\n{title} ({len(items)}):")
            if self.HINTS.get(title):
                print(f"  {self.HINTS[title]}")
            shown = items if limit is None else items[:limit]
            for text, path, line in shown:
                print(f"  {text}")
            if len(shown) < len(items):
                print(f"  ... and {len(items) - len(shown)} more (--all lists them)")
            if annotate:
                for text, path, line in shown:
                    where = f" file={escape(path, True)}" + (f",line={line}" if line else "") if path else ""
                    print(f"::error{where}::{escape(f'{title}: {text}')}")


def escape(value, prop=False):
    """Escapes a GitHub Actions workflow command message, or a property value when prop is set."""
    value = value.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")
    return value.replace(",", "%2C").replace(":", "%3A") if prop else value


def fatal(message):
    print(f"modules.py: {message}", file=sys.stderr)
    sys.exit(2)


def git(*args):
    return subprocess.Popen(["git", *args], cwd=REPO, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def finish(proc, allowed=(0,)):
    out, err = proc.communicate()
    if proc.returncode not in allowed:
        fatal(f"{' '.join(proc.args)} failed:\n{err.decode('utf-8', 'replace').strip()}")
    return out


def glob_regex(pattern):
    """Translates a path glob (** crosses folders, * and ? don't) into a regex."""
    out, i = [], 0
    while i < len(pattern):
        if pattern.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
        elif pattern.startswith("**", i):
            out.append(".*")
            i += 2
        elif pattern[i] == "*":
            out.append("[^/]*")
            i += 1
        elif pattern[i] == "?":
            out.append("[^/]")
            i += 1
        else:
            out.append(re.escape(pattern[i]))
            i += 1
    return "".join(out)


def is_glob(path):
    return any(c in path for c in "*?[")


def in_wf(path):
    return "/_WF/" in f"/{path}"


def sort_key(path):
    return path.lower(), path


def read_text(path):
    data = (REPO / path).read_bytes().decode("utf-8-sig", "replace")
    return re.sub(r"\r+\n", "\n", data)


def write_text(path, text):
    """Writes with the file's existing line endings; a new file gets the checkout's usual ones."""
    full = REPO / path
    if full.exists():
        newline = "\r\n" if b"\r\n" in full.read_bytes() else "\n"
    else:
        newline = "\r\n" if sys.platform == "win32" else "\n"
        full.parent.mkdir(parents=True, exist_ok=True)
    full.write_bytes(text.replace("\n", newline).encode("utf-8"))


def relative_link(path, base_dir):
    """A markdown link to a repo path, relative to base_dir; folders keep their trailing slash."""
    target = path.rstrip("/").split("/")
    base = base_dir.split("/") if base_dir else []
    common = 0
    while common < min(len(target), len(base)) and target[common] == base[common]:
        common += 1
    rel = "/".join([".."] * (len(base) - common) + target[common:])
    if path.endswith("/"):
        rel += "/"
    return f"[`{path}`]({quote(rel)})"


def parse_marker(text):
    """The first marker on a line as (module, kind, reason), "broken" for an unparseable one, or None."""
    for match in WORD.finditer(text):
        prefix, rest = text[:match.start()], text[match.end():]
        grammar = GRAMMAR.fullmatch(rest)
        if grammar and LEAD.search(prefix) and IN_COMMENT.search(prefix):
            return grammar["module"], grammar["kind"], (grammar["reason"] or "").strip()
        if AFTER_OPENER.search(prefix):
            return "broken"
    return None


def opens_xml_comment(text):
    """Whether the marker on this line sits in an XML comment that closes on a later line."""
    match = WORD.search(text)
    prefix, rest = text[:match.start()], text[match.end():]
    return prefix.rfind("<!--") > prefix.rfind("-->") and "-->" not in rest


def xml_continuation(file_lines, number):
    """The rest of the XML comment opened on line number, up to its "-->", or "" when it doesn't close nearby."""
    parts = []
    for line in file_lines[number:number + XML_CONTINUATION_LIMIT]:
        end = line.find("-->")
        parts.append((line if end < 0 else line[:end]).strip())
        if end >= 0:
            return " ".join(p for p in parts if p)
    return ""


class Modules:
    """Everything modules.py knows about the checkout: modules, markers, unmarked entries and problems."""

    def __init__(self, report):
        self.report = report
        self.modules: dict[str, Module] = {}
        self.files: list[str] = []
        self.marked: set[str] = set()
        # Module name, or None for standalone edits -> path -> de-duplicated reasons.
        self.edits: dict[str | None, dict[str, list[str]]] = {}
        self.unmarked: list[Unmarked] = []
        self.external: list[Module] = []

        # One listing and one grep, run side by side; untracked files outside modules are scanned in Python.
        listing = git("ls-files", "-z", "-t", "--cached", "--others", "--exclude-standard")
        grep = git("grep", "-n", "-z", "-I", "-F", "--no-color", "-e", "WOLFGATE", "--", ".",
                   ":(exclude,glob)**/_WF/**", ":(exclude)RobustToolbox",
                   *(f":(exclude){p}" for p in sorted(NOT_SCANNED)))
        config = self.load_config()
        entries = finish(listing).decode("utf-8").split("\0")
        hits = finish(grep, allowed=(0, 1))

        self.load_external(config)
        untracked = self.classify(entries)
        self.check_names()
        self.place_readmes()
        self.scan(hits, untracked)
        self.load_unmarked(config)

    # Config

    def load_config(self):
        try:
            import yaml
        except ImportError:
            fatal("PyYAML is required: pip install pyyaml")
        try:
            config = yaml.safe_load(read_text(CONFIG)) or {}
        except (OSError, yaml.YAMLError) as e:
            fatal(f"can't read {CONFIG}: {e}")
        if not isinstance(config, dict):
            fatal(f"{CONFIG} must be a mapping")
        return config

    def load_external(self, config):
        external = config.get("external") or {}
        if not isinstance(external, dict):
            self.report.add("modules.yml", "external: must map module names to {readme, paths}", CONFIG)
            return
        for name, spec in external.items():
            paths = spec.get("paths") if isinstance(spec, dict) else None
            readme = spec.get("readme") if isinstance(spec, dict) else None
            if not isinstance(readme, str) or not isinstance(paths, list) or not paths:
                self.report.add("modules.yml", f"external module {name}: needs a readme path and a paths list", CONFIG)
                continue
            module = self.modules.setdefault(name, Module(name))
            module.readme = readme
            module.globs = re.compile("|".join(f"(?:{glob_regex(str(p))})" for p in paths))
            self.external.append(module)

    def load_unmarked(self, config):
        entries = config.get("unmarked") or []
        if not isinstance(entries, list):
            self.report.add("modules.yml", "unmarked: must be a list of {path, module, reason}", CONFIG)
            return
        sorted_files = sorted(self.files)
        for entry in entries:
            if not isinstance(entry, dict) or not isinstance(entry.get("path"), str):
                self.report.add("modules.yml", f"unmarked entry without a path: {entry}", CONFIG)
                continue
            path, module, reason = entry["path"], entry.get("module"), str(entry.get("reason") or "").strip()
            problem = None
            if module is not None and module not in self.modules:
                problem = f"unknown module {module}"
            elif not reason:
                problem = "no reason"
            elif in_wf(path) or self.external_module(path.rstrip("/")):
                problem = "inside a module, needs no entry"
            item = Unmarked(path, module, reason, re.compile(glob_regex(path)) if is_glob(path) else None)
            if problem is None and not self.any_file_matches(item, sorted_files):
                problem = "matches no file"
            if problem:
                self.report.add("modules.yml", f"unmarked {path}: {problem}", CONFIG)
                continue
            self.unmarked.append(item)
            self.add_edit(module, path, reason)

    @staticmethod
    def unmarked_matches(item, path):
        if item.pattern:
            return item.pattern.fullmatch(path) is not None
        return path == item.path or path.startswith(item.path.rstrip("/") + "/")

    def any_file_matches(self, item, sorted_files):
        if item.pattern:
            return any(item.pattern.fullmatch(f) for f in sorted_files)
        prefix = item.path.rstrip("/")
        i = bisect.bisect_left(sorted_files, prefix)
        return i < len(sorted_files) and (sorted_files[i] == prefix or sorted_files[i].startswith(prefix + "/"))

    # Files

    def external_module(self, path):
        for module in self.external:
            if module.globs.fullmatch(path):
                return module
        return None

    def classify(self, entries):
        """Sorts every file into its module, reports _WF files outside a module folder, returns untracked others."""
        untracked, stray_roots = [], {}
        for entry in entries:
            if not entry:
                continue
            path = entry[2:]
            if path == "RobustToolbox" or path.startswith("RobustToolbox/"):
                continue
            if in_wf(path):
                if not os.path.lexists(REPO / path):
                    continue
                self.files.append(path)
                if path == NONMODULAR:
                    continue
                root = next((r for r in ROOTS if path.startswith(r + "/")), None)
                if root is None:
                    stray = path[:path.index("/_WF/") + 5] if "/_WF/" in path else "_WF/"
                    stray_roots[stray] = stray_roots.get(stray, 0) + 1
                    continue
                rest = path[len(root) + 1:]
                if "/" not in rest:
                    self.report.add("Files outside a module folder", f"{path}: directly at the _WF root", path)
                    continue
                name = rest.split("/", 1)[0]
                module = self.modules.setdefault(name, Module(name))
                module.files.append(path)
                module.folders.add(f"{root}/{name}")
                continue
            module = self.external_module(path)
            if module:
                if os.path.lexists(REPO / path):
                    self.files.append(path)
                    module.files.append(path)
                continue
            self.files.append(path)
            if entry[0] == "?":
                untracked.append(path)
        for stray, count in sorted(stray_roots.items()):
            files = f"{count} file{'s' if count != 1 else ''}"
            self.report.add("Files outside a module folder", f"{stray} ({files}): not a module root", stray)
        return untracked

    def check_names(self):
        by_lower = {}
        for name, module in sorted(self.modules.items()):
            if not module.globs and not MODULE_NAME.fullmatch(name):
                folders = ", ".join(sorted(module.folders))
                self.report.add("Module folders", f"{folders}: {name} is not PascalCase", sorted(module.folders)[0])
            by_lower.setdefault(name.lower(), []).append(name)
        for names in by_lower.values():
            if len(names) > 1:
                self.report.add("Module folders", f"{' and '.join(names)} differ only in case")

    def valid(self, module):
        return bool(module.globs) or MODULE_NAME.fullmatch(module.name) is not None

    def place_readmes(self):
        for module in self.modules.values():
            if module.readme is None:
                readmes = {f"{root}/{module.name}/README.md" for root in README_ROOTS}
                has_code = [root for root in README_ROOTS[:-1]
                            if any(f.startswith(f"{root}/{module.name}/") and f not in readmes for f in module.files)]
                module.readme = f"{(has_code or ['Docs/_WF'])[0]}/{module.name}/README.md"
            module.files = [f for f in module.files if f != module.readme]

    # Markers

    def scan(self, hits, untracked):
        """Parses the grep hits and the untracked files' lines into markers, validates them and collects the edits."""
        lines: dict[str, list[tuple[int, str]]] = {}
        # Whole files, read only for XML markers whose comment runs on past their line.
        texts: dict[str, list[str]] = {}
        for record in hits.split(b"\n"):
            if not record:
                continue
            path, number, text = record.split(b"\0", 2)
            path = path.decode("utf-8")
            if self.external_module(path):
                continue
            text = text.decode("utf-8", "replace").rstrip("\r").lstrip("\ufeff")
            lines.setdefault(path, []).append((int(number), text))
        for path in untracked:
            if path in NOT_SCANNED:
                continue
            try:
                full = REPO / path
                if full.stat().st_size > UNTRACKED_SCAN_LIMIT:
                    continue
                data = full.read_bytes()
            except OSError:
                continue
            if b"WOLFGATE" not in data or b"\0" in data[:8000]:
                continue
            texts[path] = [t.rstrip("\r").lstrip("\ufeff") for t in data.decode("utf-8", "replace").split("\n")]
            lines[path] = [(i + 1, t) for i, t in enumerate(texts[path]) if "WOLFGATE" in t]

        for path in sorted(lines, key=sort_key):
            open_start = None
            for number, text in lines[path]:
                parsed = parse_marker(text)
                if parsed is None:
                    continue
                where = f"{path}:{number}"
                if parsed == "broken":
                    self.report.add("Markers", f"{where}: can't parse the marker: {text.strip()[:100]}", path, number)
                    continue
                module, kind, reason = parsed
                if opens_xml_comment(text):
                    if path not in texts:
                        texts[path] = read_text(path).split("\n")
                    reason = f"{reason} {xml_continuation(texts[path], number)}".strip()
                self.marked.add(path)
                if module is None and kind != "END" and not reason:
                    self.report.add("Markers", f"{where}: a standalone marker needs a reason", path, number)
                if kind == "END":
                    if module is not None:
                        self.report.add("Markers", f"{where}: END carries no module", path, number)
                    if open_start is None:
                        self.report.add("Markers", f"{where}: END without a START", path, number)
                    open_start = None
                    continue
                if kind == "START":
                    if open_start is not None:
                        self.report.add("Markers", f"{where}: START inside the block opened at line {open_start}",
                                        path, number)
                    open_start = number
                if module is not None and module not in self.modules:
                    self.report.add("Markers", f"{where}: unknown module ({module})", path, number)
                    continue
                self.add_edit(module, path, reason)
            if open_start is not None:
                self.report.add("Markers", f"{path}:{open_start}: START without an END", path, open_start)

    def add_edit(self, module, path, reason):
        reasons = self.edits.setdefault(module, {}).setdefault(path, [])
        if reason and reason not in reasons:
            reasons.append(reason)

    # Docs

    def render_edits(self, edits, base_dir):
        out = []
        for path in sorted(edits, key=sort_key):
            target = f"`{path}`" if is_glob(path) else relative_link(path, base_dir)
            reasons = [r.replace("<", "\\<") for r in edits[path]]
            if len(reasons) == 1:
                out.append(f"- {target}: {reasons[0]}")
            else:
                out.append(f"- {target}")
                out.extend(f"  - {r}" for r in reasons)
        return out or ["None."]

    def render_block(self, module):
        base_dir = module.readme.rsplit("/", 1)[0]
        areas: dict[str, set[str]] = {}
        for path in module.files:
            area = next((name for prefix, name in AREAS if path.startswith(prefix)), "Other")
            # An RSI is one asset: list its folder, not every state.
            rsi = path.find(".rsi/")
            areas.setdefault(area, set()).add(path[:rsi + 5] if rsi >= 0 else path)
        out = [GEN_START, GEN_NOTE, "", "## Files", ""]
        for area in AREA_ORDER:
            if area in areas:
                out += [f"### {area}", ""]
                out += [f"- {relative_link(p, base_dir)}" for p in sorted(areas[area], key=sort_key)]
                out.append("")
        if not areas:
            out += ["None.", ""]
        out += ["## Non-modular edits", ""]
        out += self.render_edits(self.edits.get(module.name, {}), base_dir)
        out += ["", GEN_END]
        return "\n".join(out)

    def render_nonmodular(self):
        out = [
            "# Non-modular edits",
            "",
            GEN_NOTE,
            "",
            "Standalone edits outside `_WF` that serve no module: files with an untagged `WOLFGATE` marker, and",
            f"`unmarked` entries without a module in `{CONFIG}`. Edits that serve a module are listed in its README.",
            "",
        ]
        out += self.render_edits(self.edits.get(None, {}), NONMODULAR.rsplit("/", 1)[0])
        return "\n".join(out) + "\n"

    def docs(self):
        """(path, current text or None, generated text) for every generated file; READMEs that can't be spliced are
        reported and left out."""
        result = []
        for name in sorted(self.modules):
            module = self.modules[name]
            if not self.valid(module):
                continue
            block = self.render_block(module)
            if not (REPO / module.readme).exists():
                elsewhere = [f"{root}/{name}/README.md" for root in README_ROOTS]
                elsewhere = [p for p in elsewhere if p != module.readme and (REPO / p).exists()]
                if elsewhere and not module.globs:
                    self.report.add("Module READMEs", f"{name}: move {elsewhere[0]} to {module.readme}", elsewhere[0])
                    continue
                result.append((module.readme, None, f"# {name}\n\n{TODO_OVERVIEW}\n\n{block}\n"))
                continue
            current = read_text(module.readme)
            start, end = current.find(GEN_START), current.find(GEN_END)
            if TODO_OVERVIEW in (current if start < 0 else current[:start]):
                self.report.add("Module READMEs", f"{module.readme}: overview is still the TODO placeholder",
                                module.readme)
            if start < 0 and end < 0:
                text = f"{current.rstrip()}\n\n{block}\n"
            elif start < 0 or end < start or current.count(GEN_START) > 1 or current.count(GEN_END) > 1:
                self.report.add("Module READMEs", f"{module.readme}: broken WOLFGATE-GENERATED comments", module.readme)
                continue
            else:
                text = current[:start] + block + current[end + len(GEN_END):]
                if not text.endswith("\n"):
                    text += "\n"
            result.append((module.readme, current, text))
        current = read_text(NONMODULAR) if (REPO / NONMODULAR).exists() else None
        result.append((NONMODULAR, current, self.render_nonmodular()))
        return result

    # Pull request check

    def pr_check(self, base, report):
        changed = finish(git("diff", "--name-only", "-z", "--no-renames", "--diff-filter=d", f"{base}...HEAD"))
        merge_base = None
        for path in changed.decode("utf-8").split("\0"):
            if (not path or in_wf(path) or path in PR_EXEMPT_FILES or path.startswith(PR_EXEMPT_PREFIXES)
                    or path == "RobustToolbox" or self.external_module(path)):
                continue
            if path in self.marked or any(self.unmarked_matches(u, path) for u in self.unmarked):
                continue
            if merge_base is None:
                merge_base = finish(git("merge-base", base, "HEAD")).decode("utf-8").strip()
            if self.reverted(base, merge_base, path):
                continue
            report.add("Changed files outside _WF without a marker", path, path)

    @staticmethod
    def reverted(base, merge_base, path):
        """Whether the pull request only removed lines from a file that had a marker: a Wolfgate edit taken out."""
        numstat = finish(git("diff", "--numstat", "--no-renames", f"{base}...HEAD", "--", path)).decode("utf-8")
        added = numstat.split("\t", 1)[0] if numstat else ""
        if added != "0":
            return False
        grep = git("grep", "-q", "-F", "WOLFGATE", merge_base, "--", path)
        finish(grep, allowed=(0, 1))
        return grep.returncode == 0


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="regenerate the module READMEs and NONMODULAR.md")
    mode.add_argument("--check", action="store_true", help="fail if the docs are stale or a rule is broken")
    parser.add_argument("--pr-check", metavar="BASE",
                        help="fail if a file changed since BASE outside _WF has no marker")
    parser.add_argument("--all", action="store_true", help="list every problem instead of the first 20 per section")
    args = parser.parse_args()
    if not (args.write or args.check or args.pr_check):
        parser.error("pass --write, --check or --pr-check BASE")

    report = Report()
    # --pr-check on its own reports only its own problems; --check covers the rest.
    repo = Modules(report if args.write or args.check else Report())

    if args.write or args.check:
        for path, current, text in repo.docs():
            if current == text:
                continue
            if args.write:
                write_text(path, text)
                print(f"{'Updated' if current is not None else 'Created'} {path}")
            elif current is None and path != NONMODULAR:
                report.add("Module READMEs", f"missing {path}", path)
            else:
                report.add("Stale generated docs", path + (" (missing)" if current is None else ""), path)
    if args.pr_check:
        repo.pr_check(args.pr_check, report)

    report.print(None if args.all else REPORT_LIMIT)
    problems = report.count()
    print(f"\nmodules.py: {problems} problem{'s' if problems != 1 else ''}." if problems else "modules.py: OK.")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
