"""Generates the genitalShape prototypes and their locale keys from the genital RSI meta.json files.

Run from anywhere:  python Tools/_WF/genitals/gen_genital_shapes.py
Writes Resources/Prototypes/_WF/Genitals/shapes_{penis,testicles,vagina,breasts}.yml and
Resources/Locale/en-US/_WF/genitals/shapes.ftl (which also carries the keys of the hand-written shapes_extra.yml).

Size lists come only from state existence, so art added later is picked up by rerunning. Only plain greyscale
states are used: skin-tone (_s / -s) states, testicle alts, fused sheath testicles and the amputated/BRC states are
never referenced. BEHIND states whose every frame lasts FLICKER_DELAY or less are left out (they flicker).
Names, examine words, sheaths, regions and sort order come from the tables below. Output uses CRLF and a file is only
rewritten when its content changes, so a second run is a no-op.
"""
import json
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", ".."))
TEXTURES = os.path.join(ROOT, "Resources", "Textures")
RSI_DIR = "Mobs/Customization/Markings/Genital"
PROTO_OUT = os.path.join(ROOT, "Resources", "Prototypes", "_WF", "Genitals")
LOC_OUT = os.path.join(ROOT, "Resources", "Locale", "en-US", "_WF", "genitals", "shapes.ftl")
HEADER = "# Generated by Tools/_WF/genitals/gen_genital_shapes.py; do not edit by hand."
FLICKER_DELAY = 0.1
NEWLINE = "\r\n"

BREAST_TOKENS = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o",
                 "huge", "massive", "giga", "impossible"]
STEPS = [1, 2, 3, 4, 5]

# (id suffix, art token, display name, examine word or None to omit, allowed sheaths, sort order)
PENIS = [
    ("Human", "human", "Human", "human", [], 10),
    ("Nondescript", "nondescript", "Nondescript", None, ["Sheath", "Slit"], 20),
    ("Knotted", "knotted", "Knotted", "knotted", ["Sheath", "Slit"], 30),
    ("Flared", "flared", "Flared", "flared", ["Sheath", "Slit"], 40),
    ("BarbKnot", "barbknot", "Barbed, knotted", "barbed and knotted", ["Sheath", "Slit"], 50),
    ("Tapered", "tapered", "Tapered", "tapered", ["Sheath", "Slit"], 60),
    ("Hemi", "hemi", "Hemipenes", "paired (hemipenes)", ["Slit"], 70),  # hemipenes retract into a slit
    ("HemiKnot", "hemiknot", "Hemipenes, knotted", "paired and knotted", ["Slit"], 80),
    ("TipKnotted", "tipknotted", "Tip-knotted", "tip-knotted", ["Sheath", "Slit"], 90),
    ("Tentacle", "tentacle", "Tentacular", "tentacular", ["Sheath", "Slit"], 100),
]

# (id suffix, art token, display name, examine word or None, sort order)
TESTICLES = [
    ("Pair", "single", "Pair", None, 10),
]

VAGINA = [
    ("Human", "human", "Human", None, 10),
    ("Open", "gaping", "Open", "open", 20),
    ("Tentacle", "tentacle", "Tentacular", "tentacular", 30),
    ("Dentate", "dentata", "Dentate", "dentate", 40),
    ("Haired", "hairy", "With hair", "with visible hair", 50),
    ("Furred", "furred", "Furred", "furred", 60),
    ("Spade", "spade", "Spade-shaped", "spade-shaped", 70),
]

# (id suffix, art token, display name, examine phrase, region, sort order)
BREASTS = [
    ("Pair", "pair", "Pair", "a pair of breasts", "Chest", 10),
    ("PairRound", "pairround", "Pair, rounded", "a rounded pair of breasts", "Chest", 20),
    ("Quad", "quad", "Four", "four breasts", "Chest", 30),
    ("QuadLite", "quadlite", "Four, compact", "four breasts (compact)", "Chest", 40),
    ("QuadPlus", "quadplus", "Four, extended", "four breasts (extended)", "Chest", 50),
    ("Sextuple", "sextuple", "Six", "six breasts", "Chest", 60),
    ("Udders", "udders", "Udders", "udders", "Groin", 70),  # abdominal; the art sits at rows 17-23
]

# Hand-written shapes (shapes_extra.yml) whose keys live in the generated locale file:
# (slot, id suffix, display name, examine word or None)
EXTRA_LOC = [
    ("Vagina", "Slit", "Slit (cloacal)", "slit-shaped"),
]


class Rsi:
    """State names and frame delays of one RSI."""

    def __init__(self, name):
        self.name = name
        path = os.path.join(TEXTURES, *RSI_DIR.split("/"), name, "meta.json")
        with open(path, encoding="utf-8-sig") as f:
            meta = json.load(f)
        self.delays = {s["name"]: s.get("delays") for s in meta["states"]}
        self.lower = {}
        for state in self.delays:
            self.lower.setdefault(state.lower(), state)

    @property
    def sprite(self):
        return f"{RSI_DIR}/{self.name}"

    def find(self, state):
        """The real state name (case-insensitive fallback for upstream typos), or None."""
        if state in self.delays:
            return state
        return self.lower.get(state.lower())

    def flickers(self, state):
        delays = self.delays.get(state)
        return bool(delays) and all(d <= FLICKER_DELAY for row in delays for d in row)


class Shape:
    """Collects one shape's lists while scanning the art."""

    def __init__(self, slot, suffix, rsi, template, legacy, sort, region="Groin"):
        self.slot = slot
        self.suffix = suffix
        self.rsi = rsi
        self.template = template
        self.legacy = legacy
        self.sort = sort
        self.region = region
        self.examine = False
        self.size_tokens = None
        self.sizes, self.aroused, self.behind, self.behind_aroused = [], [], [], []
        self.overrides = {}
        self.sheaths = None

    @property
    def id(self):
        return f"GenitalShape{self.slot}{self.suffix}"

    @property
    def loc(self):
        return loc_key(self.slot, self.suffix)

    def probe(self, target, step, formatted, behind=False):
        """Adds step to target if the state exists (and does not flicker when BEHIND); records case fixes."""
        real = self.rsi.find(formatted)
        if real is None or (behind and self.rsi.flickers(real)):
            return
        if real != formatted:
            self.overrides[formatted] = real
        target.append(step)

    def finish(self):
        # Without BEHIND art the template names FRONT directly.
        if not self.behind and not self.behind_aroused:
            self.template = self.template.replace("{layer}", "FRONT")

    def yaml(self):
        lines = [
            "- type: genitalShape",
            f"  id: {self.id}",
            f"  slot: {self.slot}",
            f"  name: {self.loc}",
        ]
        if self.examine:
            lines.append(f"  examineName: {self.loc}-examine")
        lines += [
            f"  sprite: {self.rsi.sprite}",
            f"  state: \"{self.template}\"",
        ]
        if self.size_tokens:
            lines.append(f"  sizeTokens: {flow(self.size_tokens)}")
        lines += [
            f"  sizes: {flow(self.sizes)}",
            f"  arousedSizes: {flow(self.aroused)}",
            f"  behindSizes: {flow(self.behind)}",
            f"  behindArousedSizes: {flow(self.behind_aroused)}",
        ]
        if self.overrides:
            lines.append("  stateOverrides:")
            for key in sorted(self.overrides):
                lines.append(f"    {key}: {self.overrides[key]}")
        if self.sheaths is not None:
            lines.append(f"  allowedSheaths: {flow(self.sheaths)}")
        lines += [
            f"  region: {self.region}",
            f"  sortOrder: {self.sort}",
            f"  legacyToken: {self.legacy}",
        ]
        return lines


def loc_key(slot, suffix):
    return f"wf-genitals-shape-{slot.lower()}-{suffix.lower()}"


def flow(items):
    return "[" + ", ".join(str(i) for i in items) + "]"


def penis_shapes(rsi):
    shapes, loc = [], []
    for suffix, token, name, examine, sheaths, sort in PENIS:
        s = Shape("Penis", suffix, rsi, f"penis_{token}_{{size}}_{{aroused}}_{{layer}}", token, sort)
        for n in STEPS:
            s.probe(s.sizes, n, f"penis_{token}_{n}_0_FRONT")
            s.probe(s.aroused, n, f"penis_{token}_{n}_1_FRONT")
            s.probe(s.behind, n, f"penis_{token}_{n}_0_BEHIND", behind=True)
            s.probe(s.behind_aroused, n, f"penis_{token}_{n}_1_BEHIND", behind=True)
        s.sheaths, s.examine = sheaths, examine is not None
        s.finish()
        shapes.append(s)
        loc.append((s.loc, name, examine))
    return shapes, loc


def testicle_shapes(rsi):
    shapes, loc = [], []
    for suffix, token, name, examine, sort in TESTICLES:
        s = Shape("Testicles", suffix, rsi, f"testicles_{token}_{{size}}_0_{{layer}}", token, sort)
        for n in STEPS:
            s.probe(s.sizes, n, f"testicles_{token}_{n}_0_FRONT")
            s.probe(s.behind, n, f"testicles_{token}_{n}_0_BEHIND", behind=True)
        s.examine = examine is not None
        s.finish()
        shapes.append(s)
        loc.append((s.loc, name, examine))
    return shapes, loc


def vagina_shapes(rsi):
    shapes, loc = [], []
    for suffix, token, name, examine, sort in VAGINA:
        s = Shape("Vagina", suffix, rsi, f"vagina_{token}_1_{{aroused}}_FRONT", token, sort)
        s.probe(s.sizes, 1, f"vagina_{token}_1_0_FRONT")
        s.probe(s.aroused, 1, f"vagina_{token}_1_1_FRONT")
        s.examine = examine is not None
        s.finish()
        shapes.append(s)
        loc.append((s.loc, name, examine))
    return shapes, loc


def breast_shapes(rsi):
    shapes, loc = [], []
    for suffix, token, name, examine, region, sort in BREASTS:
        s = Shape("Breasts", suffix, rsi, f"breasts_{token}_{{size}}_0_{{layer}}", token, sort, region)
        s.size_tokens = BREAST_TOKENS
        for n, cup in enumerate(BREAST_TOKENS, start=1):
            s.probe(s.sizes, n, f"breasts_{token}_{cup}_0_FRONT")
            s.probe(s.behind, n, f"breasts_{token}_{cup}_0_BEHIND", behind=True)
        s.examine = examine is not None
        s.finish()
        shapes.append(s)
        loc.append((s.loc, name, examine))
    return shapes, loc


def write_if_changed(path, lines):
    text = NEWLINE.join(lines) + NEWLINE
    data = text.encode("utf-8")
    if os.path.exists(path):
        with open(path, "rb") as f:
            if f.read() == data:
                return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(data)
    return True


def main():
    groups = [
        ("shapes_penis.yml", penis_shapes(Rsi("cocks.rsi"))),
        ("shapes_testicles.yml", testicle_shapes(Rsi("balls.rsi"))),
        ("shapes_vagina.yml", vagina_shapes(Rsi("vagina.rsi"))),
        ("shapes_breasts.yml", breast_shapes(Rsi("breasts.rsi"))),
    ]

    loc_lines = [HEADER]
    changed = []
    for file_name, (shapes, loc) in groups:
        lines = [HEADER]
        for shape in shapes:
            if not shape.sizes:
                sys.exit(f"{shape.id}: no FRONT art found in {shape.rsi.name}")
            lines.append("")
            lines += shape.yaml()
        if write_if_changed(os.path.join(PROTO_OUT, file_name), lines):
            changed.append(file_name)

        loc_lines += ["", f"## {shapes[0].slot}"]
        for key, name, examine in loc:
            loc_lines.append(f"{key} = {name}")
            if examine is not None:
                loc_lines.append(f"{key}-examine = {examine}")

    loc_lines += ["", "## Hand-written shapes (shapes_extra.yml)"]
    for slot, suffix, name, examine in EXTRA_LOC:
        key = loc_key(slot, suffix)
        loc_lines.append(f"{key} = {name}")
        if examine is not None:
            loc_lines.append(f"{key}-examine = {examine}")

    if write_if_changed(LOC_OUT, loc_lines):
        changed.append(os.path.basename(LOC_OUT))

    total = sum(len(shapes) for _, (shapes, _) in groups)
    print(f"{total} shapes; " + (f"updated {', '.join(changed)}" if changed else "no changes"))


if __name__ == "__main__":
    main()
