using System.Linq;
using System.Numerics;
using Content.Client._Onyx.Medical.HealthAnalyzer;
using Content.Shared._Onyx.Medical;
using Content.Shared._Onyx.Wounds;
using Content.Shared._Shitmed.Targeting;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._WF.Wolfmed.Medical;

/// <summary>Self-contained wound/organ/chemical readout mounted inside the Shitmed health analyzer window (P4-D25).</summary>
[GenerateTypedNameReferences]
public sealed partial class WolfmedDiagnosticPanel : BoxContainer
{
    private const float DangerousBloodLevel = 0.65f;

    private IEntityManager _entityManager = default!;
    private SpriteSystem _spriteSystem = default!;
    private IPrototypeManager _prototypes = default!;
    private IResourceCache _cache = default!;

    private readonly Dictionary<NetEntity, (BoxContainer Row, EllipsisLabel Name, Label Health)> _organRows = new();
    private bool _organsUnavailable;
    private WolfmedDiagnosticTab _tab = WolfmedDiagnosticTab.Wounds;

    public WolfmedDiagnosticPanel()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();

        WoundsButton.OnPressed += _ => SelectTab(WolfmedDiagnosticTab.Wounds);
        OrgansButton.OnPressed += _ => SelectTab(WolfmedDiagnosticTab.Organs);
        ChemicalsButton.OnPressed += _ => SelectTab(WolfmedDiagnosticTab.Chemicals);

        ApplyTab();
    }

    /// <summary>Fills every tab from one scan message.</summary>
    public void Populate(HealthAnalyzerScannedUserMessage msg)
    {
        DrawWoundDiagnostics(msg);
        DrawOrgans(msg);
        DrawChemicals(msg);
        ApplyTab();
    }

    /// <summary>Drops every row so a hidden panel can never show the previous patient's findings.</summary>
    public void Clear()
    {
        WoundFindingsContainer.RemoveAllChildren();
        WoundStateLabel.Visible = false;
        VitalDamageRow.Visible = false;
        ClearOrganRows();
        ChemicalsContainer.RemoveAllChildren();
    }

    private void SelectTab(WolfmedDiagnosticTab tab)
    {
        _tab = tab;
        ApplyTab();
    }

    private void ApplyTab()
    {
        WoundsTab.Visible = _tab == WolfmedDiagnosticTab.Wounds;
        OrgansTab.Visible = _tab == WolfmedDiagnosticTab.Organs;
        ChemicalsTab.Visible = _tab == WolfmedDiagnosticTab.Chemicals;

        WoundsButton.Disabled = _tab == WolfmedDiagnosticTab.Wounds;
        OrgansButton.Disabled = _tab == WolfmedDiagnosticTab.Organs;
        ChemicalsButton.Disabled = _tab == WolfmedDiagnosticTab.Chemicals;
    }

    private void DrawWoundDiagnostics(HealthAnalyzerScannedUserMessage msg)
    {
        WoundFindingsContainer.RemoveAllChildren();
        WoundStateLabel.Visible = true;

        VitalDamageRow.Visible = msg.VitalDamage != null;
        if (msg.VitalDamage is { } vital)
            VitalDamageLabel.Text = vital.ToString();

        if (msg.ScanMode != true)
        {
            WoundStateLabel.SetMessage(Loc.GetString("health-analyzer-wound-diagnostics-inactive"));
            return;
        }

        if (IsDangerousBloodLevel(msg.BloodLevel))
            AddWoundFinding(Loc.GetString("health-analyzer-wound-blood-level-dangerous"));

        if (msg.WoundDiagnostics == null)
        {
            WoundStateLabel.SetMessage(Loc.GetString("health-analyzer-wound-diagnostics-unavailable"));
            return;
        }

        WoundStateLabel.Visible = false;
        foreach (var part in SharedTargetingSystem.GetValidParts())
        {
            if (!msg.WoundDiagnostics.Parts.TryGetValue(part, out var diagnostic))
                continue;

            var partName = Loc.GetString($"targeting-part-{PartKey(part)}");
            var details = new List<string>();

            if (diagnostic.VisibleWounds.Count > 0)
            {
                var wounds = diagnostic.VisibleWounds.Select(wound =>
                {
                    var type = Loc.GetString(wound.Name);
                    var stage = wound.StageName is { } stageName
                        ? $" ({Loc.GetString(stageName)})"
                        : string.Empty;
                    return $"{type}{stage}{(wound.Count > 1 ? $" x{wound.Count}" : string.Empty)}";
                });
                details.Add(string.Join(", ", wounds));
            }

            // Onyx carries Fracture/FractureTreatment in the payload and never renders them; Wolfgate has shipped
            // fractures with a live alert and two movement penalties since phase 2, so the grade is printed (P4-D25).
            if (diagnostic.Fracture != FractureGrade.None)
            {
                var grade = Loc.GetString($"fracture-grade-{diagnostic.Fracture.ToString().ToLowerInvariant()}");
                details.Add(diagnostic.FractureTreatment == FractureTreatment.None
                    ? Loc.GetString("health-analyzer-wound-fracture-short", ("grade", grade))
                    : Loc.GetString("health-analyzer-wound-fracture-treated-short",
                        ("grade", grade),
                        ("treatment", Loc.GetString(
                            $"health-analyzer-wound-fracture-treatment-{diagnostic.FractureTreatment.ToString().ToLowerInvariant()}"))));
            }

            if (diagnostic.BleedingRate > 0f)
                details.Add(Loc.GetString("health-analyzer-wound-bleeding-short"));

            if (diagnostic.InternalBleedingRate > 0f)
                details.Add(Loc.GetString("health-analyzer-wound-internal-bleeding-short"));

            if (diagnostic.ClottingPhase is HealthAnalyzerClottingPhase.InProgress
                or HealthAnalyzerClottingPhase.Complete
                or HealthAnalyzerClottingPhase.Mixed)
                details.Add(Loc.GetString(
                    $"health-analyzer-wound-clotting-{diagnostic.ClottingPhase.ToString().ToLowerInvariant()}"));

            // W1: printed before the scars, because it is the finding that decides what the medic does next.
            if (diagnostic.EmbeddedObjects > 0)
                details.Add(Loc.GetString("health-analyzer-wound-embedded-short",
                    ("count", diagnostic.EmbeddedObjects)));

            if (diagnostic.ScarCount > 0)
                details.Add(Loc.GetString("health-analyzer-wound-scars-short", ("count", diagnostic.ScarCount)));

            if (diagnostic.Pain > FixedPoint2.Zero)
                details.Add(Loc.GetString("health-analyzer-wound-pain-short", ("pain", diagnostic.Pain)));

            if (diagnostic.Functionality != BodyPartFunctionalityState.Functional)
                details.Add(Loc.GetString(
                    $"health-analyzer-wound-functionality-{diagnostic.Functionality.ToString().ToLowerInvariant()}"));

            if (details.Count > 0)
                AddWoundFinding(Loc.GetString("health-analyzer-wound-part-summary",
                    ("part", partName), ("details", string.Join(" - ", details))));
        }
    }

    internal static bool IsDangerousBloodLevel(float level) => !float.IsNaN(level) && level < DangerousBloodLevel;

    private static string PartKey(TargetBodyPart part) => part.ToString()
        .Replace("Left", "left-")
        .Replace("Right", "right-")
        .ToLowerInvariant();

    private void AddWoundFinding(string text)
    {
        var label = new RichTextLabel
        {
            HorizontalExpand = true,
            HorizontalAlignment = HAlignment.Left,
            Margin = new Thickness(0, 0, 0, 6),
        };
        label.SetMessage(FormattedMessage.FromMarkupPermissive($"- {text}"));
        WoundFindingsContainer.AddChild(label);
    }

    private void DrawOrgans(HealthAnalyzerScannedUserMessage msg)
    {
        if (msg.ScanMode != true || msg.Organs == null)
        {
            if (_organsUnavailable)
                return;

            ClearOrganRows();
            OrgansContainer.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-window-organs-unavailable"),
            });
            _organsUnavailable = true;
            return;
        }

        if (_organsUnavailable)
        {
            OrgansContainer.RemoveAllChildren();
            _organsUnavailable = false;
        }

        var present = new HashSet<NetEntity>();
        var position = 0;
        foreach (var organ in msg.Organs.OrderBy(organ => organ.Order))
        {
            if (!_entityManager.TryGetEntity(organ.Entity, out var organEntity) || organ.MaxHealth == 0)
                continue;

            present.Add(organ.Entity);
            var name = _entityManager.HasComponent<MetaDataComponent>(organEntity.Value)
                ? Capitalize(Identity.Name(organEntity.Value, _entityManager))
                : Loc.GetString("health-analyzer-window-entity-unknown-value-text");
            var percent = float.IsFinite((float) organ.Health / (float) organ.MaxHealth)
                ? (int) MathF.Round(Math.Clamp((float) organ.Health / (float) organ.MaxHealth * 100f, 0f, 100f))
                : 0;

            if (_organRows.TryGetValue(organ.Entity, out var existing))
            {
                if (existing.Name.Text != name)
                {
                    existing.Name.Text = name;
                    existing.Name.ToolTip = name;
                }

                var health = Loc.GetString("health-analyzer-window-organ-health", ("percent", percent));
                if (existing.Health.Text != health)
                    existing.Health.Text = health;

                if (existing.Row.GetPositionInParent() != position)
                    existing.Row.SetPositionInParent(position);
                position++;
                continue;
            }

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 8,
            };
            var icon = new SpriteView
            {
                SetSize = new Vector2(26, 26),
                OverrideDirection = Direction.South,
            };
            icon.SetEntity(organEntity.Value);
            row.AddChild(icon);
            var nameLabel = new EllipsisLabel
            {
                HorizontalExpand = true,
                Text = name,
                ToolTip = name,
            };
            row.AddChild(nameLabel);
            var healthLabel = new Label
            {
                Text = Loc.GetString("health-analyzer-window-organ-health", ("percent", percent)),
            };
            row.AddChild(healthLabel);
            OrgansContainer.AddChild(row);
            row.SetPositionInParent(position++);
            _organRows[organ.Entity] = (row, nameLabel, healthLabel);
        }

        foreach (var entity in _organRows.Keys.Where(entity => !present.Contains(entity)).ToArray())
        {
            OrgansContainer.RemoveChild(_organRows[entity].Row);
            _organRows.Remove(entity);
        }
    }

    private void ClearOrganRows()
    {
        OrgansContainer.RemoveAllChildren();
        _organRows.Clear();
        _organsUnavailable = false;
    }

    private void DrawChemicals(HealthAnalyzerScannedUserMessage msg)
    {
        ChemicalsContainer.RemoveAllChildren();

        if (msg.ScanMode != true || msg.Chemicals == null)
        {
            ChemicalsContainer.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-window-chemicals-unavailable"),
            });
            return;
        }

        if (msg.Chemicals.Count == 0)
        {
            ChemicalsContainer.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-window-chemicals-no-vessels"),
            });
            return;
        }

        foreach (var vessel in msg.Chemicals)
        {
            var group = new BoxContainer
            {
                Align = AlignMode.Begin,
                Orientation = LayoutOrientation.Vertical,
            };
            group.AddChild(CreateDiagnosticGroupTitle(
                Loc.GetString($"health-analyzer-window-solution-{vessel.Type.ToString().ToLowerInvariant()}"),
                "metaphysical"));

            if (vessel.Reagents.Count == 0)
            {
                group.AddChild(CreateDiagnosticItemLabel(
                    $" - {Loc.GetString("health-analyzer-window-solution-empty")}"));
            }
            else
            {
                foreach (var reagent in vessel.Reagents.OrderByDescending(reagent => reagent.Quantity))
                {
                    var name = _prototypes.TryIndex(reagent.Prototype, out ReagentPrototype? prototype)
                        ? prototype.LocalizedName
                        : Loc.GetString("chem-master-window-unknown-reagent-text");
                    group.AddChild(CreateDiagnosticItemLabel(
                        $" - {Loc.GetString("health-analyzer-window-solution-reagent", ("reagent", name), ("quantity", reagent.Quantity))}"));
                }
            }

            ChemicalsContainer.AddChild(group);
        }
    }

    private static string Capitalize(string text) =>
        string.IsNullOrEmpty(text) ? text : OopsConcat(char.ToUpper(text[0]).ToString(), text.Remove(0, 1));

    private static string OopsConcat(string first, string rest)
    {
        // Prevent Roslyn from emitting string span code forbidden by the content sandbox.
        return first + rest;
    }

    private static Label CreateDiagnosticItemLabel(string text) => new() { Text = text };

    private BoxContainer CreateDiagnosticGroupTitle(string text, string id)
    {
        var rootContainer = new BoxContainer
        {
            Margin = new Thickness(0, 6, 0, 0),
            VerticalAlignment = VAlignment.Bottom,
            Orientation = LayoutOrientation.Horizontal,
        };

        rootContainer.AddChild(new TextureRect
        {
            SetSize = new Vector2(30, 30),
            Texture = GetTexture(id.ToLower()),
        });

        rootContainer.AddChild(CreateDiagnosticItemLabel(text));

        return rootContainer;
    }

    private Texture GetTexture(string texture)
    {
        var rsiPath = new ResPath("/Textures/Objects/Devices/health_analyzer.rsi");
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);

        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
        if (!rsi.TryGetState(rsiSprite.RsiState, out _))
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");

        return _spriteSystem.Frame0(rsiSprite);
    }
}

/// <summary>Which of the panel's three tabs is showing.</summary>
public enum WolfmedDiagnosticTab : byte
{
    Wounds,
    Organs,
    Chemicals,
}
