using System.Linq;
using System.Numerics;
using Content.Client._Onyx.Medical.HealthAnalyzer;
using Content.Shared._Onyx.Medical;
using Content.Shared._Onyx.Wounds;
using Content.Shared._Shitmed.Targeting;
using Content.Shared._WF.Wolfmed.Wounds;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Damage.Prototypes;
using Content.Shared.FixedPoint;
using Content.Shared.IdentityManagement;
using Content.Shared.MedicalScanner;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._WF.Wolfmed.Medical;

/// <summary>Self-contained wound/organ/chemical readout mounted inside the Shitmed health analyzer window (P4-D25).</summary>
[GenerateTypedNameReferences]
public sealed partial class WolfmedDiagnosticPanel : BoxContainer
{
    // UI4: shared, so the step check that greys "give a bloodpack" uses the same line as the banner.
    private const float DangerousBloodLevel = WolfmedStepChecks.DangerousBloodLevel;

    private IEntityManager _entityManager = default!;
    private SpriteSystem _spriteSystem = default!;
    private IPrototypeManager _prototypes = default!;
    private IResourceCache _cache = default!;
    private WolfmedAnalyzerIcons _icons = default!; // UI2

    private readonly Dictionary<NetEntity, (BoxContainer Row, EllipsisLabel Name, Label Health)> _organRows = new();
    private bool _organsUnavailable;
    private WolfmedDiagnosticTab _tab = WolfmedDiagnosticTab.Wounds;

    /// <summary>UI2: the last scan, so a category chip can redraw the cards without waiting for the next one.</summary>
    private HealthAnalyzerScannedUserMessage? _lastMessage;

    public WolfmedDiagnosticPanel()
    {
        RobustXamlLoader.Load(this);

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        _prototypes = dependencies.Resolve<IPrototypeManager>();
        _cache = dependencies.Resolve<IResourceCache>();
        _icons = new WolfmedAnalyzerIcons(_cache, _spriteSystem); // UI2

        WoundsButton.OnPressed += _ => SelectTab(WolfmedDiagnosticTab.Wounds);
        OrgansButton.OnPressed += _ => SelectTab(WolfmedDiagnosticTab.Organs);
        ChemicalsButton.OnPressed += _ => SelectTab(WolfmedDiagnosticTab.Chemicals);

        ApplyTab();
    }

    /// <summary>Fills every tab from one scan message.</summary>
    public void Populate(HealthAnalyzerScannedUserMessage msg)
    {
        _lastMessage = msg; // UI2
        DrawWoundDiagnostics(msg);
        DrawOrgans(msg);
        DrawChemicals(msg);
        ApplyTab();
    }

    /// <summary>Drops every row so a hidden panel can never show the previous patient's findings.</summary>
    public void Clear()
    {
        WoundFindingsContainer.RemoveAllChildren();
        // UI2: the banners, the filter strip and the filter itself belong to the patient that just left.
        WoundAlertsContainer.RemoveAllChildren();
        WoundCategoryStrip.RemoveAllChildren();
        _lastMessage = null;
        _woundTarget = null;
        _categoryFilter = null;
        _scrollTo = null; // UI3: the card it pointed at has just been destroyed.
        WoundStateLabel.Visible = false;
        VitalDamageRow.Visible = false;
        ClearOrganRows();
        ChemicalsContainer.RemoveAllChildren();
    }

    /// <summary>UI3: the procedure window is a separate window, so it has to go when the analyzer does.</summary>
    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _treatmentWindow?.Close();
            _treatmentWindow = null;
        }

        base.Dispose(disposing);
    }

    private void SelectTab(WolfmedDiagnosticTab tab)
    {
        _tab = tab;
        ApplyTab();
    }

    private void ApplyTab()
    {
        WoundsTab.Visible = _tab == WolfmedDiagnosticTab.Wounds;
        OrgansTab.Visible = _tab == WolfmedDiagnosticTab.Organs;
        ChemicalsTab.Visible = _tab == WolfmedDiagnosticTab.Chemicals;

        WoundsButton.Disabled = _tab == WolfmedDiagnosticTab.Wounds;
        OrgansButton.Disabled = _tab == WolfmedDiagnosticTab.Organs;
        ChemicalsButton.Disabled = _tab == WolfmedDiagnosticTab.Chemicals;
    }

    // UI2: DrawWoundDiagnostics and its helpers moved to WolfmedDiagnosticPanel.Wounds.cs, which builds
    // cards instead of one joined line per part.

    private void DrawOrgans(HealthAnalyzerScannedUserMessage msg)
    {
        if (msg.ScanMode != true || msg.Organs == null)
        {
            if (_organsUnavailable)
                return;

            ClearOrganRows();
            OrgansContainer.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-window-organs-unavailable"),
            });
            _organsUnavailable = true;
            return;
        }

        if (_organsUnavailable)
        {
            OrgansContainer.RemoveAllChildren();
            _organsUnavailable = false;
        }

        var present = new HashSet<NetEntity>();
        var position = 0;
        foreach (var organ in msg.Organs.OrderBy(organ => organ.Order))
        {
            if (!_entityManager.TryGetEntity(organ.Entity, out var organEntity) || organ.MaxHealth == 0)
                continue;

            present.Add(organ.Entity);
            var name = _entityManager.HasComponent<MetaDataComponent>(organEntity.Value)
                ? Capitalize(Identity.Name(organEntity.Value, _entityManager))
                : Loc.GetString("health-analyzer-window-entity-unknown-value-text");
            var percent = float.IsFinite((float) organ.Health / (float) organ.MaxHealth)
                ? (int) MathF.Round(Math.Clamp((float) organ.Health / (float) organ.MaxHealth * 100f, 0f, 100f))
                : 0;

            if (_organRows.TryGetValue(organ.Entity, out var existing))
            {
                if (existing.Name.Text != name)
                {
                    existing.Name.Text = name;
                    existing.Name.ToolTip = name;
                }

                var health = Loc.GetString("health-analyzer-window-organ-health", ("percent", percent));
                if (existing.Health.Text != health)
                    existing.Health.Text = health;

                if (existing.Row.GetPositionInParent() != position)
                    existing.Row.SetPositionInParent(position);
                position++;
                continue;
            }

            var row = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 8,
            };
            var icon = new SpriteView
            {
                SetSize = new Vector2(26, 26),
                OverrideDirection = Direction.South,
            };
            icon.SetEntity(organEntity.Value);
            row.AddChild(icon);
            var nameLabel = new EllipsisLabel
            {
                HorizontalExpand = true,
                Text = name,
                ToolTip = name,
            };
            row.AddChild(nameLabel);
            var healthLabel = new Label
            {
                Text = Loc.GetString("health-analyzer-window-organ-health", ("percent", percent)),
            };
            row.AddChild(healthLabel);
            OrgansContainer.AddChild(row);
            row.SetPositionInParent(position++);
            _organRows[organ.Entity] = (row, nameLabel, healthLabel);
        }

        foreach (var entity in _organRows.Keys.Where(entity => !present.Contains(entity)).ToArray())
        {
            OrgansContainer.RemoveChild(_organRows[entity].Row);
            _organRows.Remove(entity);
        }
    }

    private void ClearOrganRows()
    {
        OrgansContainer.RemoveAllChildren();
        _organRows.Clear();
        _organsUnavailable = false;
    }

    private void DrawChemicals(HealthAnalyzerScannedUserMessage msg)
    {
        ChemicalsContainer.RemoveAllChildren();

        if (msg.ScanMode != true || msg.Chemicals == null)
        {
            ChemicalsContainer.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-window-chemicals-unavailable"),
            });
            return;
        }

        if (msg.Chemicals.Count == 0)
        {
            ChemicalsContainer.AddChild(new Label
            {
                Text = Loc.GetString("health-analyzer-window-chemicals-no-vessels"),
            });
            return;
        }

        foreach (var vessel in msg.Chemicals)
        {
            var group = new BoxContainer
            {
                Align = AlignMode.Begin,
                Orientation = LayoutOrientation.Vertical,
            };
            group.AddChild(CreateDiagnosticGroupTitle(
                Loc.GetString($"health-analyzer-window-solution-{vessel.Type.ToString().ToLowerInvariant()}"),
                "metaphysical"));

            if (vessel.Reagents.Count == 0)
            {
                group.AddChild(CreateDiagnosticItemLabel(
                    $" - {Loc.GetString("health-analyzer-window-solution-empty")}"));
            }
            else
            {
                foreach (var reagent in vessel.Reagents.OrderByDescending(reagent => reagent.Quantity))
                {
                    var name = _prototypes.TryIndex(reagent.Prototype, out ReagentPrototype? prototype)
                        ? prototype.LocalizedName
                        : Loc.GetString("chem-master-window-unknown-reagent-text");
                    group.AddChild(CreateDiagnosticItemLabel(
                        $" - {Loc.GetString("health-analyzer-window-solution-reagent", ("reagent", name), ("quantity", reagent.Quantity))}"));
                }
            }

            ChemicalsContainer.AddChild(group);
        }
    }

    private static string Capitalize(string text) =>
        string.IsNullOrEmpty(text) ? text : OopsConcat(char.ToUpper(text[0]).ToString(), text.Remove(0, 1));

    private static string OopsConcat(string first, string rest)
    {
        // Prevent Roslyn from emitting string span code forbidden by the content sandbox.
        return first + rest;
    }

    private static Label CreateDiagnosticItemLabel(string text) => new() { Text = text };

    private BoxContainer CreateDiagnosticGroupTitle(string text, string id)
    {
        var rootContainer = new BoxContainer
        {
            Margin = new Thickness(0, 6, 0, 0),
            VerticalAlignment = VAlignment.Bottom,
            Orientation = LayoutOrientation.Horizontal,
        };

        rootContainer.AddChild(new TextureRect
        {
            SetSize = new Vector2(30, 30),
            Texture = GetTexture(id.ToLower()),
        });

        rootContainer.AddChild(CreateDiagnosticItemLabel(text));

        return rootContainer;
    }

    private Texture GetTexture(string texture)
    {
        var rsiPath = new ResPath("/Textures/Objects/Devices/health_analyzer.rsi");
        var rsiSprite = new SpriteSpecifier.Rsi(rsiPath, texture);

        var rsi = _cache.GetResource<RSIResource>(rsiSprite.RsiPath).RSI;
        if (!rsi.TryGetState(rsiSprite.RsiState, out _))
            rsiSprite = new SpriteSpecifier.Rsi(rsiPath, "unknown");

        return _spriteSystem.Frame0(rsiSprite);
    }
}

/// <summary>Which of the panel's three tabs is showing.</summary>
public enum WolfmedDiagnosticTab : byte
{
    Wounds,
    Organs,
    Chemicals,
}
