using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.Lathe;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Lathe.UI;

/// <summary>
/// Lists the machines a fabrication silo can supply and what it has in stock.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FabricationSiloMenu : FancyWindow
{
    /// <summary>
    /// Raised with the machine whose link was toggled.
    /// </summary>
    public event Action<NetEntity>? OnClientPressed;

    /// <summary>
    /// Raised with the stored part to eject.
    /// </summary>
    public event Action<NetEntity>? OnPartPressed;

    private FabricationSiloBuiState? _state;

    public FabricationSiloMenu()
    {
        RobustXamlLoader.Load(this);
        SearchBar.OnTextChanged += _ => PopulateStock();
    }

    /// <summary>
    /// Shows a new silo state.
    /// </summary>
    public void Update(FabricationSiloBuiState state)
    {
        _state = state;
        var parts = state.Kind == FabricationSiloKind.Parts;
        Title = Loc.GetString(parts ? "fabrication-silo-parts" : "fabrication-silo-chemicals");
        KindLabel.Text = Title;
        StockLabel.Text = Loc.GetString(parts ? "fabrication-silo-components" : "fabrication-silo-reagents");
        HintLabel.SetMessage(Loc.GetString(parts ? "fabrication-silo-parts-hint" : "fabrication-silo-chemicals-hint"));

        ClientList.DisposeAllChildren();
        foreach (var (client, label) in state.Clients
                     .Select(client => (Client: client, Label: GetClientLabel(client)))
                     .OrderByDescending(pair => pair.Client.Linked)
                     .ThenBy(pair => pair.Label))
        {
            var row = new BoxContainer { HorizontalExpand = true, SeparationOverride = 8 };
            var details = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, HorizontalExpand = true };
            details.AddChild(new Label { Text = label, ToolTip = label, ClipText = true, HorizontalExpand = true });
            details.AddChild(new Label
            {
                Text = Loc.GetString(client.Linked
                    ? client.Available ? "fabrication-silo-connected" : "fabrication-silo-unavailable"
                    : "fabrication-silo-available"),
                StyleClasses = { "LabelSubText" },
            });
            row.AddChild(details);

            var button = new Button
            {
                Text = Loc.GetString(client.Linked ? "fabrication-silo-disconnect" : "fabrication-silo-connect"),
                MinWidth = 100,
                VerticalAlignment = VAlignment.Center,
            };
            var entity = client.Entity;
            button.OnPressed += _ => OnClientPressed?.Invoke(entity);
            row.AddChild(button);
            ClientList.AddChild(WrapRow(row));
        }

        if (state.Clients.Count == 0)
        {
            var empty = new RichTextLabel();
            empty.SetMessage(Loc.GetString("fabrication-silo-no-machines", ("range", state.Range)));
            ClientList.AddChild(empty);
        }

        PopulateStock();
    }

    private void PopulateStock()
    {
        StockList.DisposeAllChildren();
        if (_state == null)
            return;

        var search = SearchBar.Text.Trim();
        foreach (var (entry, label) in _state.Stock
                     .Select(entry => (Entry: entry, Label: GetStockLabel(entry)))
                     .OrderBy(pair => pair.Label))
        {
            if (!label.Contains(search, StringComparison.OrdinalIgnoreCase))
                continue;

            var row = new BoxContainer { HorizontalExpand = true, SeparationOverride = 8 };
            row.AddChild(new Label { Text = label, HorizontalExpand = true, VerticalAlignment = VAlignment.Center });
            if (entry.Entity is { } part)
            {
                var eject = new Button
                {
                    Text = Loc.GetString("fabrication-silo-eject"),
                    ToolTip = Loc.GetString("fabrication-silo-eject-hint"),
                    MinWidth = 100,
                    VerticalAlignment = VAlignment.Center,
                };
                eject.OnPressed += _ => OnPartPressed?.Invoke(part);
                row.AddChild(eject);
            }

            StockList.AddChild(WrapRow(row));
        }

        if (StockList.ChildCount == 0)
            StockList.AddChild(new Label { Text = Loc.GetString("fabrication-silo-empty"), StyleClasses = { "LabelSubText" } });
    }

    private static string GetClientLabel(FabricationSiloClientEntry client)
    {
        return client.Beacon == null
            ? client.Name
            : Loc.GetString("fabrication-silo-client-label", ("name", client.Name), ("beacon", client.Beacon));
    }

    private static string GetStockLabel(FabricationSiloStockEntry entry)
    {
        return entry.Entity != null
            ? Loc.GetString("fabrication-silo-part-stock", ("name", entry.Name), ("count", entry.Amount.Int()))
            : Loc.GetString("fabrication-silo-reagent-stock", ("reagent", entry.Name), ("amount", entry.Amount.Float()));
    }

    private static PanelContainer WrapRow(Control row)
    {
        row.Margin = new Thickness(8);
        var panel = new PanelContainer { HorizontalExpand = true, StyleClasses = { "AngleRect" } };
        panel.AddChild(row);
        return panel;
    }
}
