using System.Linq;
using Content.Client.Materials.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.Lathe;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Content.Shared.Materials.OreSilo;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._WF.Lathe.UI;

/// <summary>
/// Lists the machines a fabrication silo can supply, as the ore silo window does, and what it has in stock.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FabricationSiloMenu : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IPrototypeManager _prototypes = default!;

    private static readonly int[] WithdrawAmounts = { 5, 10, 50 };

    /// <summary>
    /// Raised with the machine whose link was toggled.
    /// </summary>
    public event Action<NetEntity>? OnClientEntryPressed;

    /// <summary>
    /// Raised with the stored part to eject.
    /// </summary>
    public event Action<NetEntity>? OnPartPressed;

    /// <summary>
    /// Raised to eject the slotted container, or insert the held one.
    /// </summary>
    public event Action? OnSlotPressed;

    /// <summary>
    /// Raised with a reagent to withdraw and the most to move; null moves as much as fits.
    /// </summary>
    public event Action<ProtoId<ReagentPrototype>, FixedPoint2?>? OnWithdrawPressed;

    /// <summary>
    /// Raised with a reagent to discard.
    /// </summary>
    public event Action<ProtoId<ReagentPrototype>>? OnDiscardPressed;

    private readonly FabricationSiloSystem _silos;
    private readonly Dictionary<(string?, string), int> _partRows = new();
    private List<StockEntry> _stock = new();
    private List<StockEntry> _nextStock = new();
    private EntityUid _owner;
    private FabricationSiloKind _kind;
    private FixedPoint2 _volume;
    private FixedPoint2 _maxVolume;
    private SlotState? _slot;

    public FabricationSiloMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _silos = _entityManager.System<FabricationSiloSystem>();

        ClientList.OnItemSelected += args => OnClientEntryPressed?.Invoke((NetEntity) ClientList[args.ItemIndex].Metadata!);
        SearchBar.OnTextChanged += _ => PopulateStock();
        SlotButton.OnPressed += _ => OnSlotPressed?.Invoke();
    }

    /// <summary>
    /// Sets the silo this window shows.
    /// </summary>
    public void SetEntity(EntityUid uid)
    {
        _owner = uid;
        if (!_entityManager.TryGetComponent<FabricationSiloComponent>(uid, out var silo))
            return;

        _kind = silo.Kind;
        var parts = _kind == FabricationSiloKind.Parts;
        Title = Loc.GetString(parts ? "fabrication-silo-parts" : "fabrication-silo-chemicals");
        KindLabel.Text = Title;
        HintLabel.SetMessage(Loc.GetString(parts ? "fabrication-silo-parts-hint" : "fabrication-silo-chemicals-hint"));
        NoClientsLabel.SetMessage(Loc.GetString("fabrication-silo-no-machines", ("range", silo.Range)));
        SlotRow.Visible = !parts;
        PopulateStock();
    }

    /// <summary>
    /// Shows the machine list with the ore silo window's entries.
    /// </summary>
    public void Update(OreSiloBuiState state)
    {
        OreSiloMenu.UpdateClientList(ClientList, state);
        NoClientsLabel.Visible = state.Clients.Count == 0;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // Stock and the slotted container are read from networked entities, like the ore silo's material list.
        _nextStock.Clear();
        var volume = FixedPoint2.Zero;
        var maxVolume = FixedPoint2.Zero;
        SlotState? slot = null;
        if (_entityManager.TryGetComponent<FabricationSiloComponent>(_owner, out var silo))
        {
            if (silo.Parts is { } parts)
                ReadParts(parts.ContainedEntities);
            else if (_silos.TryGetSolution((_owner, silo), out _, out var solution))
            {
                volume = solution.Volume;
                maxVolume = solution.MaxVolume;
                ReadReagents(solution.Contents);
            }

            if (_silos.TryGetSlottedSolution((_owner, silo), out var container, out _, out var slotted))
            {
                var name = _entityManager.GetComponent<MetaDataComponent>(container).EntityName;
                slot = new SlotState(name, slotted.Volume, slotted.MaxVolume);
            }
        }

        if (volume == _volume && maxVolume == _maxVolume && slot == _slot && _nextStock.SequenceEqual(_stock))
            return;

        (_stock, _nextStock) = (_nextStock, _stock);
        _volume = volume;
        _maxVolume = maxVolume;
        _slot = slot;
        PopulateStock();
    }

    private void ReadParts(IReadOnlyList<EntityUid> contained)
    {
        // Identical parts share one row; the row ejects its first stack.
        _partRows.Clear();
        foreach (var part in contained)
        {
            var meta = _entityManager.GetComponent<MetaDataComponent>(part);
            var key = (meta.EntityPrototype?.ID, meta.EntityName);
            var count = _silos.GetItemCount(part);
            if (_partRows.TryGetValue(key, out var index))
            {
                var row = _nextStock[index];
                _nextStock[index] = row with { Amount = row.Amount + count };
                continue;
            }

            _partRows[key] = _nextStock.Count;
            _nextStock.Add(new StockEntry(meta.EntityName, count, _entityManager.GetNetEntity(part), null));
        }
    }

    private void ReadReagents(IReadOnlyList<ReagentQuantity> contents)
    {
        // Data variants of one reagent share a row.
        foreach (var (reagent, quantity) in contents)
        {
            var index = _nextStock.FindIndex(row => row.Reagent == reagent.Prototype);
            if (index >= 0)
            {
                _nextStock[index] = _nextStock[index] with { Amount = _nextStock[index].Amount + quantity };
                continue;
            }

            var name = _prototypes.TryIndex<ReagentPrototype>(reagent.Prototype, out var proto)
                ? proto.LocalizedName
                : reagent.Prototype;
            _nextStock.Add(new StockEntry(name, quantity, null, reagent.Prototype));
        }
    }

    private void PopulateStock()
    {
        StockLabel.Text = _kind == FabricationSiloKind.Parts
            ? Loc.GetString("fabrication-silo-components")
            : Loc.GetString("fabrication-silo-reagents", ("volume", _volume.Float()), ("max", _maxVolume.Float()));

        SlotLabel.Text = _slot is { } slot
            ? Loc.GetString("fabrication-silo-container",
                ("name", slot.Name),
                ("volume", slot.Volume.Float()),
                ("max", slot.MaxVolume.Float()))
            : Loc.GetString("fabrication-silo-no-container-inserted");
        SlotButton.Text = Loc.GetString(_slot != null ? "fabrication-silo-eject" : "fabrication-silo-insert");
        SlotButton.ToolTip = Loc.GetString(_slot != null ? "fabrication-silo-eject-container-hint" : "fabrication-silo-insert-hint");

        StockList.DisposeAllChildren();
        var search = SearchBar.Text.Trim();
        var canWithdraw = _slot is { } target && target.Volume < target.MaxVolume;
        foreach (var (entry, label) in _stock
                     .Select(entry => (Entry: entry, Label: GetStockLabel(entry)))
                     .OrderBy(pair => pair.Label))
        {
            if (!label.Contains(search, StringComparison.OrdinalIgnoreCase))
                continue;

            var row = new BoxContainer { HorizontalExpand = true, SeparationOverride = 8, Margin = new Thickness(8) };
            row.AddChild(new Label
            {
                Text = label,
                HorizontalExpand = true,
                ClipText = true,
                VerticalAlignment = VAlignment.Center,
            });

            if (entry.Part is { } part)
            {
                var eject = new Button
                {
                    Text = Loc.GetString("fabrication-silo-eject"),
                    ToolTip = Loc.GetString("fabrication-silo-eject-hint"),
                    MinWidth = 100,
                    VerticalAlignment = VAlignment.Center,
                };
                eject.OnPressed += _ => OnPartPressed?.Invoke(part);
                row.AddChild(eject);
            }
            else if (entry.Reagent is { } reagent)
            {
                AddReagentButtons(row, reagent, canWithdraw);
            }

            var panel = new PanelContainer { HorizontalExpand = true, StyleClasses = { "AngleRect" } };
            panel.AddChild(row);
            StockList.AddChild(panel);
        }

        if (StockList.ChildCount == 0)
            StockList.AddChild(new Label { Text = Loc.GetString("fabrication-silo-empty"), StyleClasses = { "LabelSubText" } });
    }

    private void AddReagentButtons(BoxContainer row, string reagent, bool canWithdraw)
    {
        foreach (var amount in WithdrawAmounts)
        {
            var withdraw = NewWithdrawButton(Loc.GetString("fabrication-silo-withdraw-amount", ("amount", amount)),
                canWithdraw);
            withdraw.OnPressed += _ => OnWithdrawPressed?.Invoke(reagent, FixedPoint2.New(amount));
            row.AddChild(withdraw);
        }

        var all = NewWithdrawButton(Loc.GetString("fabrication-silo-withdraw-all"), canWithdraw);
        all.OnPressed += _ => OnWithdrawPressed?.Invoke(reagent, null);
        row.AddChild(all);

        var discard = new ConfirmButton
        {
            Text = Loc.GetString("fabrication-silo-discard"),
            ToolTip = Loc.GetString("fabrication-silo-discard-hint"),
            MinWidth = 80,
            VerticalAlignment = VAlignment.Center,
        };
        discard.OnPressed += _ => OnDiscardPressed?.Invoke(reagent);
        row.AddChild(discard);
    }

    private static Button NewWithdrawButton(string text, bool enabled)
    {
        return new Button
        {
            Text = text,
            ToolTip = Loc.GetString(enabled ? "fabrication-silo-withdraw-hint" : "fabrication-silo-withdraw-blocked"),
            Disabled = !enabled,
            MinWidth = 44,
            VerticalAlignment = VAlignment.Center,
        };
    }

    private static string GetStockLabel(StockEntry entry)
    {
        return entry.Part != null
            ? Loc.GetString("fabrication-silo-part-stock", ("name", entry.Name), ("count", entry.Amount.Int()))
            : Loc.GetString("fabrication-silo-reagent-stock", ("reagent", entry.Name), ("amount", entry.Amount.Float()));
    }

    /// <summary>
    /// One stock row; Part is set for parts so the stack can be ejected, Reagent for chemicals.
    /// </summary>
    private readonly record struct StockEntry(string Name, FixedPoint2 Amount, NetEntity? Part, string? Reagent);

    /// <summary>
    /// The container in a chemical silo's slot.
    /// </summary>
    private readonly record struct SlotState(string Name, FixedPoint2 Volume, FixedPoint2 MaxVolume);
}
