using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Lathe.UI;

/// <summary>
/// Shows whether a lathe's parts and chemical silos can supply it.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LatheSupplyStatus : BoxContainer
{
    public LatheSupplyStatus()
    {
        RobustXamlLoader.Load(this);
        SetLinks(false, false);
    }

    /// <summary>
    /// Shows which silos are linked and available.
    /// </summary>
    public void SetLinks(bool parts, bool chemicals)
    {
        PartsSiloStatus.Text = Loc.GetString(parts ? "lathe-menu-parts-silo-online" : "lathe-menu-parts-silo-offline");
        ChemicalSiloStatus.Text = Loc.GetString(chemicals ? "lathe-menu-chemical-silo-online" : "lathe-menu-chemical-silo-offline");
    }
}
