using Content.Shared.Lathe;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._WF.Lathe.UI;

/// <summary>
/// One queued batch: its progress, supply status, an editable total and a cancel button.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LatheQueueEntry : PanelContainer
{
    /// <summary>
    /// Raised with a valid new total.
    /// </summary>
    public event Action<int>? OnAmountChanged;

    /// <summary>
    /// Raised when the batch is cancelled.
    /// </summary>
    public event Action? OnCancelled;

    private int _printed;
    private int _requested;

    public LatheQueueEntry(string name, Control display)
    {
        RobustXamlLoader.Load(this);
        RecipeName.SetMessage(FormattedMessage.FromUnformatted(name));
        RecipeDisplayContainer.AddChild(display);
        AmountEdit.ToolTip = Loc.GetString("lathe-menu-queue-amount-tooltip", ("max", LatheRecipeBatch.MaxItemsRequested));
        AmountEdit.OnTextEntered += _ => ApplyAmount();
        AmountEdit.OnFocusExit += _ => ApplyAmount();
        CancelButton.OnPressed += _ => OnCancelled?.Invoke();
    }

    /// <summary>
    /// Refreshes the row; the total is left alone while it is being edited.
    /// </summary>
    public void Update(int position, int printed, int requested, string status, string? missing)
    {
        _printed = printed;
        _requested = requested;
        NumberLabel.Text = Loc.GetString("lathe-menu-queue-index", ("index", position.ToString("00")));
        PrintedLabel.Text = Loc.GetString("lathe-menu-queue-printed", ("printed", printed));
        StatusLabel.Text = status;
        MissingLabel.Visible = missing != null;
        if (missing != null)
            MissingLabel.SetMessage(FormattedMessage.FromUnformatted(missing));

        if (!AmountEdit.HasKeyboardFocus())
            AmountEdit.SetText(requested.ToString());
    }

    private void ApplyAmount()
    {
        if (!int.TryParse(AmountEdit.Text, out var amount) ||
            amount <= 0 ||
            amount > LatheRecipeBatch.MaxItemsRequested ||
            amount < _printed)
        {
            AmountEdit.SetText(_requested.ToString());
            return;
        }

        if (amount != _requested)
            OnAmountChanged?.Invoke(amount);
    }
}
