using Content.Shared._WF.Lathe;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._WF.Lathe.UI;

/// <summary>
/// Shows whether a lathe's parts and chemical silos can supply it, read from the networked links.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LatheSupplyStatus : BoxContainer
{
    [Dependency] private IEntityManager _entityManager = default!;

    private FabricationSiloSystem? _silos;
    private EntityUid? _owner;
    private bool? _parts;
    private bool? _chemicals;

    public LatheSupplyStatus()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SetLinks(false, false);
    }

    /// <summary>
    /// Sets the lathe whose links are shown.
    /// </summary>
    public void SetOwner(EntityUid owner)
    {
        _owner = owner;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_owner is not { } owner)
            return;

        _silos ??= _entityManager.System<FabricationSiloSystem>();
        SetLinks(_silos.GetLinkedSilo(owner, FabricationSiloKind.Parts) != null,
            _silos.GetLinkedSilo(owner, FabricationSiloKind.Chemicals) != null);
    }

    private void SetLinks(bool parts, bool chemicals)
    {
        if (_parts == parts && _chemicals == chemicals)
            return;

        _parts = parts;
        _chemicals = chemicals;
        PartsSiloStatus.Text = Loc.GetString(parts ? "lathe-menu-parts-silo-online" : "lathe-menu-parts-silo-offline");
        ChemicalSiloStatus.Text = Loc.GetString(chemicals ? "lathe-menu-chemical-silo-online" : "lathe-menu-chemical-silo-offline");
    }
}
