using Content.Client._WF.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.CCVar;
using Content.Shared._WF.PlanetCracker.Cracker;
using Content.Shared.Power;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;

namespace Content.Client._WF.PlanetCracker.Cracker;

/// <summary>Centrifuge machine window: stock power controls plus spin and load read from <see cref="WFCentrifugeComponent"/>.</summary>
[GenerateTypedNameReferences]
public sealed partial class WFCentrifugeWindow : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    [Dependency] private IConfigurationManager _cfg = default!;

    // Load bands match WFCentrifugeDial.
    private const float LoadCaution = 0.75f;

    private const float LoadDanger = 0.95f;

    private readonly ButtonGroup _powerGroup = new();

    private EntityUid _owner;

    private bool _on;

    // Values last written to the labels.
    private int _shownSpin = -1;

    private bool _shownAtFull;

    private int _shownLoad = -1;

    private int _shownCapacity = -1;

    public WFCentrifugeWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PowerOnButton.Group = _powerGroup;
        PowerOffButton.Group = _powerGroup;

        UpdateReadout(0f, false, 0f, 0f);
    }

    /// <summary>Binds the window to its machine and its interface.</summary>
    public void SetOwner(WFCentrifugeBoundUserInterface bui, string? title)
    {
        if (!string.IsNullOrEmpty(title))
            Title = title;

        _owner = bui.Owner;

        PowerOnButton.OnPressed += _ => bui.SetPowerSwitch(true);
        PowerOffButton.OnPressed += _ => bui.SetPowerSwitch(false);
    }

    /// <summary>Takes the switch and the charge readouts from the stock machine state.</summary>
    public void UpdateState(PowerChargeState state)
    {
        _on = state.On;

        if (state.On)
            PowerOnButton.Pressed = true;
        else
            PowerOffButton.Pressed = true;

        ChargeStatusLabel.Text = Loc.GetString(state.PowerStatus switch
        {
            PowerChargePowerStatus.Off => "power-charge-window-status-off",
            PowerChargePowerStatus.Discharging => "power-charge-window-status-discharging",
            PowerChargePowerStatus.Charging => "power-charge-window-status-charging",
            _ => "power-charge-window-status-fully-charged",
        });

        ChargeStatusLabel.SetOnlyStyleClass(state.PowerStatus switch
        {
            PowerChargePowerStatus.Off => "Danger",
            PowerChargePowerStatus.Discharging or PowerChargePowerStatus.Charging => "Caution",
            _ => "Good",
        });

        ChargeEtaLabel.Text = state.EtaSeconds >= 0
            ? Loc.GetString("power-charge-window-eta-value", ("left", TimeSpan.FromSeconds(state.EtaSeconds)))
            : Loc.GetString("power-charge-window-eta-none");

        ChargeEtaLabel.SetOnlyStyleClass(state.EtaSeconds >= 0 ? "Caution" : "Disabled");

        ChargeDrawLabel.Text = Loc.GetString("power-charge-window-power-label",
            ("draw", state.PowerDraw),
            ("max", state.PowerDrawMax));

        UpdateStatusLine();
    }

    /// <summary>Pushes one spin and load reading; unchanged values are skipped since every Label.Text set relayouts.</summary>
    public void UpdateReadout(float spin, bool atFull, float load, float capacity)
    {
        RotorDial.SetReadout(spin, atFull, load, capacity);

        var percent = (int)MathF.Round(Math.Clamp(spin, 0f, 1f) * 100f);
        var wholeLoad = (int)MathF.Round(load);
        var wholeCapacity = (int)MathF.Round(capacity);

        if (percent == _shownSpin && atFull == _shownAtFull && wholeLoad == _shownLoad && wholeCapacity == _shownCapacity)
            return;

        _shownSpin = percent;
        _shownAtFull = atFull;
        _shownLoad = wholeLoad;
        _shownCapacity = wholeCapacity;

        var skin = WolfgateSkins.Get(_cfg.GetCVar(WolfgateCVars.UiStyle));

        SpinBar.Value = percent;
        SpinValueLabel.Text = Loc.GetString("wf-centrifuge-window-spin-value", ("percent", percent));
        SpinValueLabel.FontColorOverride = atFull ? skin.Good : skin.Text;

        var fraction = capacity > 0f ? Math.Clamp(load / capacity, 0f, 1f) : 0f;

        LoadBar.Value = fraction * 100f;

        LoadValueLabel.Text = capacity > 0f
            ? Loc.GetString("wf-centrifuge-window-load-value", ("mass", wholeLoad), ("capacity", wholeCapacity))
            : Loc.GetString("wf-centrifuge-window-load-none");

        LoadValueLabel.FontColorOverride = capacity <= 0f
            ? skin.TextDisabled
            : fraction switch
            {
                >= LoadDanger => skin.Danger,
                >= LoadCaution => skin.Caution,
                _ => skin.Good,
            };

        UpdateStatusLine();
    }

    /// <summary>The headline: what the rotor is doing, and what that means for a cut.</summary>
    private void UpdateStatusLine()
    {
        var skin = WolfgateSkins.Get(_cfg.GetCVar(WolfgateCVars.UiStyle));

        var (status, hint, colour) = !_on
            ? ("wf-centrifuge-window-rotor-stopped", "wf-centrifuge-window-rotor-hint-stopped", skin.Danger)
            : _shownAtFull
                ? ("wf-centrifuge-window-rotor-full", "wf-centrifuge-window-rotor-hint-full", skin.Good)
                : ("wf-centrifuge-window-rotor-spinning", "wf-centrifuge-window-rotor-hint-spinning", skin.Caution);

        RotorStatusLabel.Text = Loc.GetString(status);
        RotorStatusLabel.FontColorOverride = colour;

        RotorHintLabel.Text = Loc.GetString(hint);
        RotorHintLabel.FontColorOverride = skin.TextMuted;
    }

    /// <inheritdoc/>
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_entityManager.TryGetComponent(_owner, out WFCentrifugeComponent? centrifuge))
            return;

        UpdateReadout(centrifuge.Spin, centrifuge.AtFull, centrifuge.Load, centrifuge.Capacity);
    }
}
