using System.Linq;
using System.Text;
using Content.Client._WF.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.CCVar;
using Content.Shared._WF.PlanetCracker.Cracker;
using Content.Shared._WF.PlanetCracker.Cracker.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._WF.PlanetCracker.Cracker;

/// <summary>
/// The crack control console: stage readout, the site plan, the centrifuge dial, the projector rows, the stage strip
/// and the three buttons. Everything it shows comes out of one <see cref="WFCrackConsoleState"/>, and every failing
/// condition and blocker is named from a locale key rather than a server-sent string.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class WFCrackConsoleWindow : FancyWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;

    /// <summary>Raised when the crew presses TARGET PAIR.</summary>
    public event Action? OnTargetPressed;

    /// <summary>Raised when the crew presses CLEAR TARGET.</summary>
    public event Action? OnUntargetPressed;

    /// <summary>Raised when the crew presses BEGIN CRACK.</summary>
    public event Action? OnBeginPressed;

    /// <summary>Scratch buffer for the blocker hover list, so a 0.25 s update does not allocate a new one each pass.</summary>
    private readonly StringBuilder _blockers = new();

    public WFCrackConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TargetButton.OnPressed += _ => OnTargetPressed?.Invoke();
        UntargetButton.OnPressed += _ => OnUntargetPressed?.Invoke();
        BeginButton.OnPressed += _ => OnBeginPressed?.Invoke();
    }

    /// <summary>Pushes one server state into every control on the window.</summary>
    public void UpdateState(WFCrackConsoleState state)
    {
        var skin = WolfgateSkins.Get(_cfg.GetCVar(WolfgateCVars.UiStyle));

        SiteView.SetState(state);
        TimelineView.SetState(state);
        ProjectorView.SetState(state);
        CentrifugeView.SetReadout(state.Spin, state.AtFull, state.Load, state.Capacity);

        HeaderState.Text = Loc.GetString("wf-crack-console-state",
            ("state", Loc.GetString(StageKey(state.State))));

        HeaderCrack.Text = CrackText(state);
        HeaderCrack.FontColorOverride = state.CrackPaused ? skin.Caution : skin.Text;

        // One label, three countdowns, most urgent first: the evacuation outranks the pairing window, which outranks
        // the hull-loss grace. Only the last of the three ever reads nominal.
        // Neither header line is shown while it only reads nominal: the strip's own countdown line already says so.
        GraceLabel.Text = GraceText(state);
        GraceLabel.Visible = state.EvacRunning || state.DisconnectArmed || state.GraceRunning;
        GraceLabel.FontColorOverride = state.EvacRunning || state.DisconnectArmed || state.GraceRunning
            ? skin.Danger
            : skin.TextMuted;

        FailureLabel.Text = FailureText(state);
        FailureLabel.Visible = state.Failing != WFCrackFailure.None;
        FailureLabel.FontColorOverride = state.Failing == WFCrackFailure.None ? skin.TextMuted : skin.Danger;

        TargetButton.Disabled = !state.CanTarget;
        UntargetButton.Disabled = !state.CanUntarget;
        BeginButton.Disabled = !state.CanBegin;

        // A greyed BEGIN CRACK has to say why, one line per flag, or the crew has nothing to act on.
        BeginButton.ToolTip = BlockerText(state);
    }

    /// <summary>The timeline countdown line: the evacuation, else the armed disconnect window, else the grace.</summary>
    private static string GraceText(WFCrackConsoleState state)
    {
        if (state.EvacRunning)
            return Loc.GetString("wf-crack-console-evac", ("time", Format(state.EvacRemaining)));

        if (state.DisconnectArmed)
            return Loc.GetString("wf-crack-console-disconnect", ("time", Format(state.DisconnectRemaining)));

        return state.GraceRunning
            ? Loc.GetString("wf-crack-console-grace", ("time", Format(state.GraceRemaining)))
            : Loc.GetString("wf-crack-console-grace-nominal");
    }

    /// <summary>The cut readout: remaining time, the spin-down when one is running, or the alignment offset.</summary>
    private static string CrackText(WFCrackConsoleState state)
    {
        if (state.PendingAbort is { } pending)
        {
            return Loc.GetString("wf-crack-console-abort",
                       ("seconds", (int)Math.Ceiling(state.AbortRemaining.TotalSeconds))) +
                   " " +
                   Loc.GetString("wf-crack-console-abort-to", ("state", Loc.GetString(StageKey(pending))));
        }

        if (state.State is WFCrackState.Cracking or WFCrackState.Cracked)
        {
            return state.CrackPaused
                ? Loc.GetString("wf-crack-console-crack-paused")
                : Loc.GetString("wf-crack-console-crack-remaining", ("time", Format(state.CrackRemaining)));
        }

        if (state.CircleRadius <= 0f)
            return string.Empty;

        return state.Aligned
            ? Loc.GetString("wf-crack-console-aligned")
            : Loc.GetString("wf-crack-console-offset",
                ("x", state.BerthOffset.X.ToString("F1")),
                ("y", state.BerthOffset.Y.ToString("F1")),
                ("distance", state.BerthOffset.Length().ToString("F1")));
    }

    /// <summary>Every failing hold condition, named one flag at a time.</summary>
    private string FailureText(WFCrackConsoleState state)
    {
        if (state.Failing == WFCrackFailure.None)
            return Loc.GetString("wf-crack-console-grace-nominal");

        _blockers.Clear();

        foreach (var (flag, key) in FailureKeys)
        {
            if ((state.Failing & flag) == 0)
                continue;

            if (_blockers.Length > 0)
                _blockers.Append(", ");

            _blockers.Append(Loc.GetString(key));
        }

        return _blockers.ToString();
    }

    /// <summary>Every blocker holding BEGIN CRACK, one line per flag.</summary>
    private string? BlockerText(WFCrackConsoleState state)
    {
        if (state.Blockers == WFCrackBlocker.None)
            return null;

        return string.Join("\n", BlockerKeys
            .Where(pair => (state.Blockers & pair.Flag) != 0)
            .Select(pair => Loc.GetString(pair.Key)));
    }

    /// <summary>One locale key per <see cref="WFCrackFailure"/> flag.</summary>
    private static readonly (WFCrackFailure Flag, string Key)[] FailureKeys =
    {
        (WFCrackFailure.Centrifuge, "wf-crack-console-fail-centrifuge"),
        (WFCrackFailure.ProjectorsShort, "wf-crack-console-fail-projectors-short"),
        (WFCrackFailure.ProjectorPower, "wf-crack-console-fail-projector-power"),
        (WFCrackFailure.ProjectorBroken, "wf-crack-console-fail-projector-broken"),
    };

    /// <summary>One locale key per <see cref="WFCrackBlocker"/> flag; all twelve, so the hover names the real fault.</summary>
    private static readonly (WFCrackBlocker Flag, string Key)[] BlockerKeys =
    {
        (WFCrackBlocker.WrongState, "wf-crack-console-blocker-wrong-state"),
        (WFCrackBlocker.NoPair, "wf-crack-console-blocker-no-pair"),
        (WFCrackBlocker.NotTargeted, "wf-crack-console-blocker-not-targeted"),
        (WFCrackBlocker.NotAligned, "wf-crack-console-blocker-not-aligned"),
        (WFCrackBlocker.Obstructed, "wf-crack-console-blocker-obstructed"),
        (WFCrackBlocker.InGridNetwork, "wf-crack-console-blocker-in-grid-network"),
        (WFCrackBlocker.CentrifugeMissing, "wf-crack-console-blocker-centrifuge-missing"),
        (WFCrackBlocker.CentrifugeNotFull, "wf-crack-console-blocker-centrifuge-not-full"),
        (WFCrackBlocker.ProjectorsShort, "wf-crack-console-blocker-projectors-short"),
        (WFCrackBlocker.ProjectorsUnpowered, "wf-crack-console-blocker-projectors-unpowered"),
        (WFCrackBlocker.ProjectorsBroken, "wf-crack-console-blocker-projectors-broken"),
        (WFCrackBlocker.PlanetCracked, "wf-crack-console-blocker-planet-cracked"),
    };

    /// <summary>Locale key naming one stage.</summary>
    private static string StageKey(WFCrackState state)
    {
        return state switch
        {
            WFCrackState.Idle => "wf-crack-console-state-idle",
            WFCrackState.Surveying => "wf-crack-console-state-surveying",
            WFCrackState.AnchorsPlaced => "wf-crack-console-state-anchors-placed",
            WFCrackState.AnchorsLocked => "wf-crack-console-state-anchors-locked",
            WFCrackState.Cracking => "wf-crack-console-state-cracking",
            WFCrackState.Cracked => "wf-crack-console-state-cracked",
            WFCrackState.Disconnecting => "wf-crack-console-state-disconnecting",
            WFCrackState.Released => "wf-crack-console-state-released",
            WFCrackState.Falling => "wf-crack-console-state-falling",
            _ => "wf-crack-console-state-idle",
        };
    }

    /// <summary>Minutes and seconds, the only shape any of the three timers needs.</summary>
    private static string Format(TimeSpan time)
    {
        return time <= TimeSpan.Zero ? "0:00" : $"{(int)time.TotalMinutes}:{time.Seconds:D2}";
    }
}
