using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Genitals.UI;

/// <summary>One-time notice that Adult content now also covers anatomy, and that actions by others need their own toggles.</summary>
[GenerateTypedNameReferences]
public sealed partial class AdultContentNoticeWindow : FancyWindow
{
    public event Action? OnOpenConsentSettings;

    /// <summary>OK: the controller records the acknowledgement in wf.anatomy_notice_seen.</summary>
    public event Action? OnAcknowledged;

    public AdultContentNoticeWindow()
    {
        RobustXamlLoader.Load(this);

        NoticeLabel.SetMessage(Loc.GetString("wf-anatomy-notice-text"));
        OpenConsentButton.OnPressed += _ => OnOpenConsentSettings?.Invoke();
        OkButton.OnPressed += _ => OnAcknowledged?.Invoke();
    }
}
