using Content.Client._WF.Stylesheets;
using Content.Shared._WF.Genitals;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Genitals.UI;

/// <summary>One organ in the Anatomy panel: its description and, for external organs, the exposure status and visibility choice.</summary>
[GenerateTypedNameReferences]
public sealed partial class AnatomyOrganRow : PanelContainer
{
    public readonly GenitalSlot Slot;

    public event Action<GenitalSlot, GenitalVisibility>? OnVisibilitySelected;

    public AnatomyOrganRow(GenitalSlot slot)
    {
        RobustXamlLoader.Load(this);
        Slot = slot;

        var group = new ButtonGroup(false);
        SetUp(NormalButton, GenitalVisibility.Normal, group);
        SetUp(HiddenButton, GenitalVisibility.AlwaysHidden, group);
        SetUp(ThroughButton, GenitalVisibility.ShowThroughClothing, group);
    }

    /// <summary>Shows the description. A status means the organ is external, which also shows the visibility choice.</summary>
    public void Update(string description, string? status, GenitalVisibility visibility)
    {
        DescriptionLabel.Text = description;

        var external = status != null;
        StatusLabel.Visible = external;
        StatusLabel.Text = status;
        VisibilityBox.Visible = external;
        if (!external)
            return;

        var button = visibility switch
        {
            GenitalVisibility.AlwaysHidden => HiddenButton,
            GenitalVisibility.ShowThroughClothing => ThroughButton,
            _ => NormalButton,
        };

        button.Pressed = true;
    }

    private void SetUp(Button button, GenitalVisibility visibility, ButtonGroup group)
    {
        button.Group = group;
        button.AddStyleClass(StyleWolfgate.StyleClassCreatorToggle);
        button.OnPressed += _ => OnVisibilitySelected?.Invoke(Slot, visibility);
    }
}
