using System.Linq;
using Content.Client._WF.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.Genitals;
using Content.Shared._WF.Genitals.Components;
using Content.Shared._WF.Genitals.Prototypes;
using Content.Shared._WF.Genitals.Systems;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WF.Genitals.UI;

/// <summary>The owner's in-game anatomy settings: reveal mode, undergarments, strip consent, arousal and per-organ visibility.</summary>
/// <remarks>Only shows state and raises events; AnatomyUIController turns them into owner requests.</remarks>
[GenerateTypedNameReferences]
public sealed partial class AnatomyWindow : FancyWindow
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    /// <summary>Row order: external organs first, informational rows last.</summary>
    private static readonly GenitalSlot[] RowOrder =
    {
        GenitalSlot.Penis,
        GenitalSlot.Testicles,
        GenitalSlot.Vagina,
        GenitalSlot.Breasts,
        GenitalSlot.Womb,
    };

    private readonly Dictionary<GenitalSlot, AnatomyOrganRow> _rows = new();
    private readonly List<GenitalSlot> _rowSlots = new();
    private readonly List<GenitalSlot> _presentSlots = new();

    private byte _partialArousal;
    private byte _fullArousal;

    public event Action<GenitalRevealMode>? OnRevealModeSelected;

    /// <summary>Slot and the chosen state: true puts the undergarment back, false removes it.</summary>
    public event Action<UndergarmentSlot, bool>? OnUndergarmentSelected;

    public event Action<bool>? OnStripConsentSelected;

    /// <summary>Raised while dragging, on release and by the snap buttons; the controller throttles it.</summary>
    public event Action<byte>? OnArousalSelected;

    public event Action<GenitalSlot, GenitalVisibility>? OnVisibilitySelected;
    public event Action? OnSaveDefaultsPressed;
    public event Action? OnConsentSettingsPressed;

    private GenitalSettingsPrototype Settings => GenitalProfileValidator.GetSettings(_proto);

    public AnatomyWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var reveal = new ButtonGroup(false);
        RevealUndergarmentsButton.Group = reveal;
        RevealClothingButton.Group = reveal;
        RevealUndergarmentsButton.OnPressed += _ => OnRevealModeSelected?.Invoke(GenitalRevealMode.UndergarmentRemoval);
        RevealClothingButton.OnPressed += _ => OnRevealModeSelected?.Invoke(GenitalRevealMode.ClothingRemoval);

        SetUpPair(TopWornButton, TopRemovedButton, worn => OnUndergarmentSelected?.Invoke(UndergarmentSlot.Top, worn));
        SetUpPair(BottomWornButton, BottomRemovedButton, worn => OnUndergarmentSelected?.Invoke(UndergarmentSlot.Bottom, worn));
        SetUpPair(StripOnButton, StripOffButton, on => OnStripConsentSelected?.Invoke(on));

        ArousalTicks.LinkedSlider = ArousalSlider;
        ArousalSlider.OnValueChanged += _ => OnSliderChanged();
        ArousalSlider.OnReleased += _ => OnArousalSelected?.Invoke(SliderValue());
        SnapNoneButton.OnPressed += _ => Snap(0);
        SnapPartialButton.OnPressed += _ => Snap(_partialArousal);
        SnapFullButton.OnPressed += _ => Snap(_fullArousal);

        SaveDefaultsButton.AddStyleClass(StyleWolfgate.StyleClassCreatorPrimary);
        SaveDefaultsButton.OnPressed += _ => OnSaveDefaultsPressed?.Invoke();
        ConsentSettingsButton.OnPressed += _ => OnConsentSettingsPressed?.Invoke();
    }

    /// <summary>Shows the controls for the local body, or the reason they are unavailable.</summary>
    /// <param name="stripConsent">The saved UndergarmentStrip value; null while consent has not loaded.</param>
    /// <param name="pendingArousal">An arousal value the controller has yet to send; the slider keeps showing it.</param>
    public void Refresh(EntityUid? body, bool optedIn, bool canSaveDefaults, bool? stripConsent, byte? pendingArousal)
    {
        if (!optedIn)
        {
            ShowGate(Loc.GetString("wf-anatomy-gate-consent"));
            return;
        }

        if (body is not { } uid
            || !_entMan.TryGetComponent<GenitalsComponent>(uid, out var genitals)
            || genitals.LifeStage > ComponentLifeStage.Running)
        {
            ShowGate(UnavailableReason(body));
            return;
        }

        var settings = Settings;
        GatePanel.Visible = false;
        ContentScroll.Visible = true;
        SaveDefaultsButton.Visible = true;
        SaveDefaultsButton.Disabled = !canSaveDefaults;
        SaveDefaultsButton.ToolTip = Loc.GetString(canSaveDefaults
            ? "wf-anatomy-save-defaults-tooltip"
            : "wf-anatomy-save-defaults-unavailable");

        var ent = new Entity<GenitalsComponent>(uid, genitals);
        _entMan.TryGetComponent<HumanoidAppearanceComponent>(uid, out var humanoid);

        UpdateReveal(genitals.RevealMode);
        UpdateUndergarments(genitals, humanoid);
        UpdateStripConsent(stripConsent, settings);
        UpdateArousal(ent, settings, pendingArousal);
        UpdateOrgans(ent, humanoid);
    }

    /// <summary>Drops the organ rows, e.g. when the master switch turns off.</summary>
    public void Clear()
    {
        OrganRows.DisposeAllChildren();
        _rows.Clear();
        _rowSlots.Clear();
    }

    private void ShowGate(string text)
    {
        GateLabel.SetMessage(text);
        GatePanel.Visible = true;
        ContentScroll.Visible = false;
        SaveDefaultsButton.Visible = false;
    }

    /// <summary>Why a body has no anatomy: the creator's age or species gate text, otherwise the generic line.</summary>
    private string UnavailableReason(EntityUid? body)
    {
        var settings = Settings;
        if (body is { } uid
            && _entMan.TryGetComponent<HumanoidAppearanceComponent>(uid, out var humanoid)
            && !GenitalProfileValidator.IsEligible(humanoid.Age, humanoid.Species.Id, settings, out var reason))
        {
            return reason == GenitalIssue.SpeciesExcluded
                ? Loc.GetString("wf-genitals-gate-species")
                : Loc.GetString("wf-genitals-gate-age", ("age", settings.AdultAge));
        }

        return Loc.GetString("wf-anatomy-unavailable");
    }

    private void UpdateReveal(GenitalRevealMode mode)
    {
        var button = mode == GenitalRevealMode.ClothingRemoval ? RevealClothingButton : RevealUndergarmentsButton;
        button.Pressed = true;
    }

    private void UpdateUndergarments(GenitalsComponent genitals, HumanoidAppearanceComponent? humanoid)
    {
        UpdateUndergarment(genitals, humanoid, UndergarmentSlot.Top, TopWornButton, TopRemovedButton, TopNoneLabel);
        UpdateUndergarment(genitals, humanoid, UndergarmentSlot.Bottom, BottomWornButton, BottomRemovedButton, BottomNoneLabel);
    }

    /// <summary>Worn/Removed for a worn undergarment; "None worn" otherwise.</summary>
    private static void UpdateUndergarment(GenitalsComponent genitals, HumanoidAppearanceComponent? humanoid, UndergarmentSlot slot,
        Button wornButton, Button removedButton, Label noneLabel)
    {
        var hasMarking = GenitalCoverageSystem.HasVisibleUndergarment(humanoid, slot);
        wornButton.Visible = hasMarking;
        removedButton.Visible = hasMarking;
        noneLabel.Visible = !hasMarking;

        if (hasMarking)
            ((genitals.Undergarments & UndergarmentSlots.RemovedFlag(slot)) != 0 ? removedButton : wornButton).Pressed = true;
    }

    private void UpdateStripConsent(bool? state, GenitalSettingsPrototype settings)
    {
        StripConsentBox.Visible = settings.StripConsent != null;
        StripOnButton.Disabled = state == null;
        StripOffButton.Disabled = state == null;

        if (state is { } on)
            (on ? StripOnButton : StripOffButton).Pressed = true;
    }

    private void UpdateArousal(Entity<GenitalsComponent> ent, GenitalSettingsPrototype settings, byte? pendingArousal)
    {
        var arousable = _entMan.System<SharedArousalSystem>().CanBeAroused((ent.Owner, ent.Comp));
        ArousalCard.Visible = arousable;
        if (!arousable)
            return;

        _partialArousal = settings.PartialArousal;
        _fullArousal = settings.FullArousal;
        ArousalTicks.SetThresholds(settings.PartialArousal / (float) SharedArousalSystem.MaxArousal,
            settings.FullArousal / (float) SharedArousalSystem.MaxArousal);

        // Never move the slider under the player's cursor, nor back from a value still waiting to be sent: the state that
        // confirms the previous value usually arrives in that gap.
        if (!ArousalSlider.Grabbed && pendingArousal == null)
            ArousalSlider.SetValueWithoutEvent(ent.Comp.Arousal);

        UpdateArousalLabel(SliderValue());
    }

    private void UpdateOrgans(Entity<GenitalsComponent> ent, HumanoidAppearanceComponent? humanoid)
    {
        _presentSlots.Clear();
        foreach (var slot in RowOrder)
        {
            if (ent.Comp.HasOrgan(slot))
                _presentSlots.Add(slot);
        }

        if (!_presentSlots.SequenceEqual(_rowSlots))
            RebuildRows();

        var coverageSystem = _entMan.System<GenitalCoverageSystem>();
        var coverage = coverageSystem.GetCoverage(
            new Entity<GenitalsComponent, HumanoidAppearanceComponent?>(ent.Owner, ent.Comp, humanoid));

        var anyExternal = false;
        foreach (var slot in _rowSlots)
        {
            string? status = null;
            if (ent.Comp.HasExternalOrgan(slot))
            {
                anyExternal = true;
                status = Status(ent, slot, coverageSystem.GetExposure(ent, slot, coverage));
            }

            _rows[slot].Update(Describe(ent.Comp, slot), status, ent.Comp.Visibility.Get(slot));
        }

        NoOrgansLabel.Visible = !anyExternal;
    }

    private void RebuildRows()
    {
        Clear();
        foreach (var slot in _presentSlots)
        {
            var row = new AnatomyOrganRow(slot);
            row.OnVisibilitySelected += (rowSlot, visibility) => OnVisibilitySelected?.Invoke(rowSlot, visibility);
            _rows[slot] = row;
            _rowSlots.Add(slot);
            OrganRows.AddChild(row);
        }
    }

    /// <summary>One clinical line per organ, from the body mirror.</summary>
    private string Describe(GenitalsComponent genitals, GenitalSlot slot)
    {
        switch (slot)
        {
            case GenitalSlot.Penis when genitals.Penis is { } penis:
                // An organ spawned without a configuration has no length.
                if (penis.LengthCm == 0)
                    return Loc.GetString("wf-anatomy-row-penis-plain");

                return Loc.GetString("wf-anatomy-row-penis",
                    ("shape", ShapeName(penis.Shape)),
                    ("length", (int) penis.LengthCm),
                    ("sheath", SheathWord(penis.Sheath)));

            case GenitalSlot.Testicles when genitals.Testicles is { } testicles:
                return testicles.Testicles == TesticleType.Internal
                    ? Loc.GetString("wf-anatomy-row-testicles-internal")
                    : Loc.GetString("wf-anatomy-row-testicles", ("size", GenitalWords.TesticleSize(testicles.Step)));

            case GenitalSlot.Vagina when genitals.Vagina is { } vagina:
                return Loc.GetString("wf-anatomy-row-vagina", ("shape", ShapeName(vagina.Shape)));

            case GenitalSlot.Womb:
                return Loc.GetString("wf-anatomy-row-womb");

            case GenitalSlot.Breasts when genitals.Breasts is { } breasts:
                return Loc.GetString("wf-anatomy-row-breasts",
                    ("shape", ShapeName(breasts.Shape)),
                    ("cup", GenitalWords.CupText(breasts.Step)),
                    ("lactating", breasts.Lactation ? "yes" : "no"));

            default:
                return string.Empty;
        }
    }

    /// <summary>Status line from the shared coverage function: hidden, exposed, shown through, or what covers it.</summary>
    private string Status(Entity<GenitalsComponent> ent, GenitalSlot slot, GenitalExposure exposure)
    {
        string status;
        if (ent.Comp.Visibility.Get(slot) == GenitalVisibility.AlwaysHidden)
            status = Loc.GetString("wf-anatomy-status-hidden");
        else if (exposure.Exposed)
            status = Loc.GetString(exposure.Layer == GenitalLayerSet.Over ? "wf-anatomy-status-through" : "wf-anatomy-status-exposed");
        else if (exposure.CoveredBy is { } item && _entMan.TryGetComponent<MetaDataComponent>(item, out var meta))
            status = Loc.GetString("wf-anatomy-status-covered", ("item", meta.EntityName));
        else if (exposure.CoveredByUndergarment)
            status = Loc.GetString("wf-anatomy-status-undergarment");
        else
            status = Loc.GetString("wf-anatomy-status-covered-generic");

        return Loc.GetString("wf-anatomy-status", ("status", status));
    }

    private string ShapeName(ProtoId<GenitalShapePrototype>? shape)
    {
        return shape is { } id && _proto.TryIndex(id, out var proto)
            ? Loc.GetString(proto.Name)
            : Loc.GetString("wf-anatomy-shape-unknown");
    }

    /// <summary>Fluent selector value for the penis row.</summary>
    private static string SheathWord(SheathType sheath)
    {
        return sheath switch
        {
            SheathType.Sheath => "sheath",
            SheathType.Slit => "slit",
            _ => "none",
        };
    }

    private void OnSliderChanged()
    {
        var value = SliderValue();
        UpdateArousalLabel(value);

        if (ArousalSlider.Grabbed)
            OnArousalSelected?.Invoke(value);
    }

    private void Snap(byte value)
    {
        ArousalSlider.SetValueWithoutEvent(value);
        UpdateArousalLabel(value);
        OnArousalSelected?.Invoke(value);
    }

    private byte SliderValue()
    {
        return (byte) Math.Clamp((int) MathF.Round(ArousalSlider.Value), 0, SharedArousalSystem.MaxArousal);
    }

    private void UpdateArousalLabel(byte value)
    {
        var state = SharedArousalSystem.ToState(value, Settings) switch
        {
            ArousalState.Full => "wf-anatomy-arousal-state-full",
            ArousalState.Partial => "wf-anatomy-arousal-state-partial",
            _ => "wf-anatomy-arousal-state-none",
        };

        ArousalValueLabel.Text = Loc.GetString("wf-anatomy-arousal-value", ("value", (int) value), ("state", Loc.GetString(state)));
    }

    /// <summary>Groups two toggle buttons; pressing the first reports true, the second false.</summary>
    private static void SetUpPair(Button first, Button second, Action<bool> selected)
    {
        var group = new ButtonGroup(false);
        first.Group = group;
        second.Group = group;
        first.AddStyleClass(StyleWolfgate.StyleClassCreatorToggle);
        second.AddStyleClass(StyleWolfgate.StyleClassCreatorToggle);
        first.OnPressed += _ => selected(true);
        second.OnPressed += _ => selected(false);
    }
}

/// <summary>Arousal slider that exposes its grabber width, so the tick marks under it line up with their values.</summary>
public sealed class AnatomyArousalSlider : Slider
{
    public float GrabberWidth => _grabber.DesiredSize.X;
}

/// <summary>Tick marks under the arousal slider at the Partial and Full thresholds.</summary>
public sealed class AnatomyArousalTicks : Control
{
    private static readonly Color TickColor = Color.White.WithAlpha(0.45f);

    private float _partial;
    private float _full;

    /// <summary>The slider the ticks line up with; both span the same width.</summary>
    public AnatomyArousalSlider? LinkedSlider { get; set; }

    /// <summary>Tick positions as ratios of the slider range.</summary>
    public void SetThresholds(float partial, float full)
    {
        _partial = partial;
        _full = full;
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        var grabber = LinkedSlider?.GrabberWidth ?? 0f;
        DrawTick(handle, grabber, _partial);
        DrawTick(handle, grabber, _full);
    }

    /// <summary>Same mapping as Slider: the grabber centre runs from half a grabber in from each edge.</summary>
    private void DrawTick(DrawingHandleScreen handle, float grabber, float ratio)
    {
        if (ratio <= 0f || ratio >= 1f)
            return;

        var x = (int) ((grabber / 2f + (Size.X - grabber) * ratio) * UIScale);
        var half = Math.Max(1, (int) UIScale);
        handle.DrawRect(new UIBox2i(x - half, 0, x + half, PixelSize.Y), TickColor);
    }
}
