using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Genitals.UI;

/// <summary>Asks before saving a character whose age means the save removes its anatomy settings.</summary>
/// <remarks>The profile editor keeps one instance and closes it whenever the edited profile changes.</remarks>
[GenerateTypedNameReferences]
public sealed partial class AnatomySaveConfirmWindow : FancyWindow
{
    /// <summary>The save waiting for an answer. Cleared on every close, so Cancel or a later close never runs it.</summary>
    private Action? _onConfirmed;

    public AnatomySaveConfirmWindow()
    {
        RobustXamlLoader.Load(this);
        MessageLabel.SetMessage(Loc.GetString("wf-genitals-save-confirm-text"));

        ConfirmButton.OnPressed += _ =>
        {
            var confirmed = _onConfirmed;
            Close();
            confirmed?.Invoke();
        };
        CancelButton.OnPressed += _ => Close();
        OnClose += () => _onConfirmed = null;
    }

    /// <summary>Opens the window for one save; <paramref name="onConfirmed"/> runs after Save and replaces any earlier one.</summary>
    public void Ask(Action onConfirmed)
    {
        _onConfirmed = onConfirmed;
        OpenCentered();
    }
}
