using System.Linq;
using Content.Client._Common.Consent;
using Content.Client._WF.Stylesheets;
using Content.Client._WF.UserInterface.Controls;
using Content.Client.Options.UI;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Shared._WF.CCVar;
using Content.Shared._WF.Genitals;
using Content.Shared._WF.Genitals.Prototypes;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;

namespace Content.Client._WF.Genitals.UI;

/// <summary>Creator tab for per-organ anatomy options.</summary>
/// <remarks>
/// Gates (kill switch, consent, age, species) are shown instead of the controls and never change the working copy.
/// Only the genital controls write, always through GenitalProfileValidator.ValidateOrgans (organ rules, not eligibility).
/// </remarks>
[GenerateTypedNameReferences]
public sealed partial class WolfgateGenitalEditor : BoxContainer
{
    [Dependency] private IClientConsentManager _consent = default!;
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _proto = default!;
    [Dependency] private MarkingManager _markingManager = default!;

    /// <summary>Width of the field labels, so the rows line up with the ones in the XAML.</summary>
    private const float LabelWidth = 150f;

    /// <summary>Id prefix of the pregnancy overlay markings.</summary>
    private const string PregnancyMarkingPrefix = "Pregnant-";

    /// <summary>Its art is the same at every cup size, so the creator says so.</summary>
    private static readonly ProtoId<GenitalShapePrototype> UddersShape = "GenitalShapeBreastsUdders";

    private static readonly SheathType[] SheathTypes = { SheathType.None, SheathType.Sheath, SheathType.Slit };

    /// <summary>Validator issues shown under the header rather than next to one control.</summary>
    private static readonly GenitalIssue[] GeneralIssues =
    {
        GenitalIssue.UnknownShape, GenitalIssue.WrongSlotShape, GenitalIssue.InvalidValue,
    };

    private static readonly IReadOnlySet<string> NoHiddenMarkings = new HashSet<string>();

    private static readonly Color WarningColor = Color.FromHex("#E0A040");

    private readonly Segmented<GenitalPreviewMode> _previewMode = new();
    private readonly Segmented<ArousalState> _previewArousal = new();
    private readonly Segmented<GenitalRevealMode> _reveal = new();
    private readonly Segmented<SheathType> _sheath = new();
    private readonly Segmented<TesticleType> _testicleType = new();
    private readonly Segmented<GenitalVisibility> _penisVisibility = new();
    private readonly Segmented<GenitalVisibility> _testicleVisibility = new();
    private readonly Segmented<GenitalVisibility> _vaginaVisibility = new();
    private readonly Segmented<GenitalVisibility> _breastVisibility = new();
    private readonly ColourRow _penisColour;
    private readonly ColourRow _sheathColour;
    private readonly ColourRow _testicleColour;
    private readonly ColourRow _vaginaColour;
    private readonly ColourRow _breastColour;
    private readonly ButtonGroup _penisTiles = new();
    private readonly ButtonGroup _vaginaTiles = new();
    private readonly ButtonGroup _breastTiles = new();

    /// <summary>Issues from the last validation, shown next to the controls they concern.</summary>
    private readonly List<GenitalIssue> _issues = new();

    /// <summary>Organ-rule view of the working copy: what the controls show and edit.</summary>
    private GenitalProfile _profile = GenitalProfile.Empty;

    private string _species = SharedHumanoidAppearanceSystem.DefaultSpecies;
    private Sex _sex = Sex.Unsexed;

    /// <summary>Age as EnsureValid stores it: clamped to the species' range.</summary>
    private int _age;

    private Color _skin = Color.White;
    private bool _speciesHasUndergarments = true;
    private bool _wearsUndergarment;
    private bool _pregnancyMarking;

    /// <summary>The player's last sheath choice. A shape that does not allow it suppresses it; the next shape that does restores it.</summary>
    private SheathType _sheathChoice;

    /// <summary>Typical anatomy waiting for the player to confirm the replacement.</summary>
    private Action? _pendingPreset;

    private bool _tilesBuilt;

    /// <summary>Set while the controls are filled from the profile, so their change events do not write back.</summary>
    private bool _syncing;

    private Direction _direction = Direction.South;

    /// <summary>Raised after a genital control changed the anatomy; carries the organ-rule-validated profile.</summary>
    public event Action<GenitalProfile>? OnProfileChanged;

    /// <summary>Raised after the arousal preview changed; the doll reloads in place.</summary>
    public event Action? OnPreviewSettingsChanged;

    /// <summary>Raised after the preview mode changed; the doll respawns, because only As worn dresses it.</summary>
    public event Action? OnPreviewModeChanged;

    /// <summary>Raised by the "Choose undergarments" button.</summary>
    public event Action? OnOpenMarkingsRequested;

    public WolfgateGenitalEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _previewMode.Add(GenitalPreviewMode.AsWorn, Loc.GetString("wf-genitals-preview-worn"));
        _previewMode.Add(GenitalPreviewMode.UnderwearOnly, Loc.GetString("wf-genitals-preview-underwear"));
        _previewMode.Add(GenitalPreviewMode.Nude, Loc.GetString("wf-genitals-preview-nude"));
        PreviewModeRow.AddChild(_previewMode);

        _previewArousal.Add(ArousalState.None, Loc.GetString("wf-genitals-preview-arousal-none"));
        _previewArousal.Add(ArousalState.Partial, Loc.GetString("wf-genitals-preview-arousal-partial"));
        _previewArousal.Add(ArousalState.Full, Loc.GetString("wf-genitals-preview-arousal-full"));
        PreviewArousalRow.AddChild(_previewArousal);

        _reveal.Add(GenitalRevealMode.UndergarmentRemoval, Loc.GetString("wf-genitals-reveal-undergarments"));
        _reveal.Add(GenitalRevealMode.ClothingRemoval, Loc.GetString("wf-genitals-reveal-clothing"),
            Loc.GetString("wf-genitals-reveal-clothing-tooltip"));
        RevealButtons.AddChild(_reveal);

        _sheath.Add(SheathType.None, Loc.GetString("wf-genitals-sheath-none"));
        _sheath.Add(SheathType.Sheath, Loc.GetString("wf-genitals-sheath-sheath"));
        _sheath.Add(SheathType.Slit, Loc.GetString("wf-genitals-sheath-slit"));
        SheathRow.AddChild(_sheath);

        _testicleType.Add(TesticleType.None, Loc.GetString("wf-genitals-testicles-none"));
        _testicleType.Add(TesticleType.External, Loc.GetString("wf-genitals-testicles-external"));
        _testicleType.Add(TesticleType.Internal, Loc.GetString("wf-genitals-testicles-internal"));
        TesticleTypeRow.AddChild(_testicleType);

        AddVisibilityOptions(_penisVisibility, PenisVisibilityRow);
        AddVisibilityOptions(_testicleVisibility, TesticleVisibilityRow);
        AddVisibilityOptions(_vaginaVisibility, VaginaVisibilityRow);
        AddVisibilityOptions(_breastVisibility, BreastVisibilityRow);

        _penisColour = new ColourRow(Loc.GetString("wf-genitals-colour"));
        PenisColourRow.AddChild(_penisColour);
        _sheathColour = new ColourRow(Loc.GetString("wf-genitals-sheath-colour"));
        SheathColourRow.AddChild(_sheathColour);
        _testicleColour = new ColourRow(Loc.GetString("wf-genitals-colour"));
        TesticleColourRow.AddChild(_testicleColour);
        _vaginaColour = new ColourRow(Loc.GetString("wf-genitals-colour"));
        VaginaColourRow.AddChild(_vaginaColour);
        _breastColour = new ColourRow(Loc.GetString("wf-genitals-colour"));
        BreastColourRow.AddChild(_breastColour);

        PresetConfirmLabel.SetMessage(Loc.GetString("wf-genitals-preset-confirm"));
        UndergarmentNoticeLabel.SetMessage(Loc.GetString("wf-genitals-no-undergarments"));
        SpeciesUndergarmentNote.SetMessage(Loc.GetString("wf-genitals-no-undergarments-species"));
        PregnancyNote.SetMessage(Loc.GetString("wf-genitals-warning-PregnancyMarkingWithoutWomb"), WarningColor);
        LoadFailedWarning.SetMessage(Loc.GetString("wf-genitals-load-failed"), WarningColor);
        TesticleInternalNote.SetMessage(Loc.GetString("wf-genitals-testicles-internal-note"));
        UddersNote.SetMessage(Loc.GetString("wf-genitals-udders-note"));

        WireControls();
    }

    /// <summary>Direction the shape tiles face; follows the preview doll.</summary>
    public Direction PreviewDirection
    {
        get => _direction;
        set
        {
            _direction = value;
            foreach (var grid in ShapeGrids())
            {
                foreach (var child in grid.Children)
                {
                    if (child is WolfgateGenitalShapeTile tile)
                        tile.SetDirection(value);
                }
            }
        }
    }

    /// <summary>Rebuilds gates, presets, notices and tile colours. Never raises OnProfileChanged.</summary>
    /// <remarks>Runs on every age keystroke and species change, so it must never write to the profile.</remarks>
    public void SetContext(string species, Sex sex, int age, Color skinColor, IReadOnlyCollection<Marking> markings)
    {
        // A confirmation asked for another species or sex no longer describes what would be applied.
        if (species != _species || sex != _sex)
            HidePresetConfirm();

        _species = species;
        _sex = sex;
        _age = GenitalProfileValidator.ClampAge(age, species, _proto);
        _skin = skinColor;
        _speciesHasUndergarments = SpeciesHasUndergarments(species);

        _wearsUndergarment = false;
        _pregnancyMarking = false;
        foreach (var marking in markings)
        {
            if (marking.MarkingId.StartsWith(PregnancyMarkingPrefix, StringComparison.Ordinal))
                _pregnancyMarking = true;

            if (_markingManager.TryGetMarking(marking, out var proto)
                && proto.MarkingCategory is MarkingCategories.UndergarmentTop or MarkingCategories.UndergarmentBottom)
                _wearsUndergarment = true;
        }

        Refresh();
    }

    /// <summary>Shows a profile's anatomy. Raises no events; organ-rule fixes are only written back after an edit.</summary>
    public void SetProfile(GenitalProfile profile)
    {
        _issues.Clear();
        _profile = GenitalProfileValidator.ValidateOrgans(profile, _proto, _issues);
        _sheathChoice = _profile.Penis?.Sheath ?? SheathType.None;
        HidePresetConfirm();
        Refresh();
    }

    /// <summary>Re-reads the local consent settings; called whenever the server sends them.</summary>
    public void RefreshConsent()
    {
        Refresh();
    }

    /// <summary>Preview back to As worn and resting arousal, including dolls already filled with the old settings.</summary>
    public void ResetPreview()
    {
        PreviewSystem?.ResetPreview();

        _syncing = true;
        try
        {
            _previewMode.Select(GenitalPreviewMode.AsWorn);
            _previewArousal.Select(ArousalState.None);
        }
        finally
        {
            _syncing = false;
        }
    }

    /// <summary>Markings the markings tab must not offer: the adult-only ones while the character is below the adult age.</summary>
    public static IReadOnlySet<string> HiddenMarkingsFor(string species, int age, IPrototypeManager proto)
    {
        var settings = GenitalProfileValidator.GetSettings(proto);
        return GenitalProfileValidator.ClampAge(age, species, proto) < settings.AdultAge
            ? new HashSet<string>(settings.AdultOnlyMarkings)
            : NoHiddenMarkings;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _consent.OnServerDataLoaded += RefreshConsent;
        _cfg.OnValueChanged(WolfgateCVars.AnatomyEnabled, OnAnatomyEnabledChanged);
        Refresh();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _consent.OnServerDataLoaded -= RefreshConsent;
        _cfg.UnsubValueChanged(WolfgateCVars.AnatomyEnabled, OnAnatomyEnabledChanged);
        ResetPreview();
    }

    protected override void Resized()
    {
        base.Resized();
        UpdateColumns();
    }

    private void OnAnatomyEnabledChanged(bool enabled)
    {
        Refresh();
    }

    private void WireControls()
    {
        OpenConsentButton.OnPressed += _ =>
            UserInterfaceManager.GetUIController<OptionsUIController>().OpenWindow(OptionsMenu.ConsentTabIndex);
        ChooseUndergarmentsButton.OnPressed += _ => OnOpenMarkingsRequested?.Invoke();

        _previewMode.OnSelected += mode =>
        {
            if (_syncing || PreviewSystem is not { } preview || preview.Mode == mode)
                return;

            preview.Mode = mode;
            OnPreviewModeChanged?.Invoke();
        };
        _previewArousal.OnSelected += state =>
        {
            if (_syncing || PreviewSystem is not { } preview)
                return;

            preview.Arousal = state == ArousalState.None ? null : state;
            OnPreviewSettingsChanged?.Invoke();
        };

        PresetMaleButton.OnPressed += _ =>
        {
            if (PresetEntry(true) is { } entry)
                RequestPreset(entry);
        };
        PresetFemaleButton.OnPressed += _ =>
        {
            if (PresetEntry(false) is { } entry)
                RequestPreset(entry);
        };
        PresetClearButton.OnPressed += _ => RequestPreset(null);
        PresetApplyButton.OnPressed += _ =>
        {
            var apply = _pendingPreset;
            HidePresetConfirm();
            apply?.Invoke();
        };
        PresetCancelButton.OnPressed += _ => HidePresetConfirm();

        _reveal.OnSelected += mode =>
        {
            if (!_syncing)
                Commit(_profile.WithRevealMode(mode));
        };

        // Penis
        PenisInclude.OnToggled += args =>
        {
            if (!_syncing)
                SetPenisIncluded(args.Pressed);
        };
        LengthSlider.OnValueChanged += range =>
        {
            if (!_syncing)
                EditPenis(p => p.With(lengthCm: (int) MathF.Round(range.Value)));
        };
        _sheath.OnSelected += type =>
        {
            if (_syncing)
                return;

            _sheathChoice = type;
            EditPenis(p => p.With(sheath: type));
        };
        _penisColour.OnMatchChanged += match =>
        {
            if (!_syncing)
                EditPenis(p => p.With(matchSkin: match, color: match ? p.Color : SeedColour(p.Color)));
        };
        _penisColour.OnColorPicked += color =>
        {
            if (!_syncing)
                EditPenis(p => p.With(matchSkin: false, color: color));
        };
        _sheathColour.OnMatchChanged += match =>
        {
            if (!_syncing)
                EditPenis(p => p.With(sheathMatchSkin: match, sheathColor: match ? p.SheathColor : SeedColour(p.SheathColor)));
        };
        _sheathColour.OnColorPicked += color =>
        {
            if (!_syncing)
                EditPenis(p => p.With(sheathMatchSkin: false, sheathColor: color));
        };
        _penisVisibility.OnSelected += visibility =>
        {
            if (!_syncing)
                EditPenis(p => p.With(visibility: visibility));
        };

        // Testicles
        _testicleType.OnSelected += type =>
        {
            if (!_syncing)
                SetTesticleType(type);
        };
        TesticleSizeSlider.OnValueChanged += range =>
        {
            if (!_syncing)
                EditTesticles(t => t.With(size: (int) MathF.Round(range.Value)));
        };
        _testicleColour.OnMatchChanged += match =>
        {
            if (!_syncing)
                EditTesticles(t => t.With(matchSkin: match, color: match ? t.Color : SeedColour(t.Color)));
        };
        _testicleColour.OnColorPicked += color =>
        {
            if (!_syncing)
                EditTesticles(t => t.With(matchSkin: false, color: color));
        };
        _testicleVisibility.OnSelected += visibility =>
        {
            if (!_syncing)
                EditTesticles(t => t.With(visibility: visibility));
        };

        // Vagina and womb
        VaginaInclude.OnToggled += args =>
        {
            if (!_syncing)
                SetVaginaIncluded(args.Pressed);
        };
        _vaginaColour.OnMatchChanged += match =>
        {
            if (!_syncing)
                EditVagina(v => v.With(matchSkin: match, color: match ? v.Color : SeedColour(v.Color)));
        };
        _vaginaColour.OnColorPicked += color =>
        {
            if (!_syncing)
                EditVagina(v => v.With(matchSkin: false, color: color));
        };
        WombCheck.OnToggled += args =>
        {
            if (!_syncing && _profile.Vagina != null)
                Commit(_profile.WithWomb(args.Pressed));
        };
        _vaginaVisibility.OnSelected += visibility =>
        {
            if (!_syncing)
                EditVagina(v => v.With(visibility: visibility));
        };

        // Breasts
        BreastsInclude.OnToggled += args =>
        {
            if (!_syncing)
                SetBreastsIncluded(args.Pressed);
        };
        CupSlider.OnValueChanged += range =>
        {
            if (!_syncing)
                EditBreasts(b => b.With(cup: (int) MathF.Round(range.Value)));
        };
        LactationCheck.OnToggled += args =>
        {
            if (!_syncing)
                EditBreasts(b => b.With(lactation: args.Pressed));
        };
        _breastColour.OnMatchChanged += match =>
        {
            if (!_syncing)
                EditBreasts(b => b.With(matchSkin: match, color: match ? b.Color : SeedColour(b.Color)));
        };
        _breastColour.OnColorPicked += color =>
        {
            if (!_syncing)
                EditBreasts(b => b.With(matchSkin: false, color: color));
        };
        _breastVisibility.OnSelected += visibility =>
        {
            if (!_syncing)
                EditBreasts(b => b.With(visibility: visibility));
        };
    }

    private static void AddVisibilityOptions(Segmented<GenitalVisibility> segmented, Control row)
    {
        segmented.Add(GenitalVisibility.Normal, Loc.GetString("wf-genitals-visibility-normal"),
            Loc.GetString("wf-genitals-visibility-normal-tooltip"));
        segmented.Add(GenitalVisibility.AlwaysHidden, Loc.GetString("wf-genitals-visibility-hidden"),
            Loc.GetString("wf-genitals-visibility-hidden-tooltip"));
        segmented.Add(GenitalVisibility.ShowThroughClothing, Loc.GetString("wf-genitals-visibility-through"),
            Loc.GetString("wf-genitals-visibility-through-tooltip"));
        row.AddChild(segmented);
    }

    #region Edits

    /// <summary>Applies the organ rules, shows the result and hands it to the profile editor.</summary>
    private void Commit(GenitalProfile edited)
    {
        _issues.Clear();
        _profile = GenitalProfileValidator.ValidateOrgans(edited, _proto, _issues);
        Refresh();
        OnProfileChanged?.Invoke(_profile);
    }

    private void EditPenis(Func<PenisProfile, PenisProfile> edit)
    {
        if (_profile.Penis is { } penis)
            Commit(_profile.WithPenis(edit(penis)));
    }

    private void EditTesticles(Func<TesticlesProfile, TesticlesProfile> edit)
    {
        if (_profile.Testicles is { } testicles)
            Commit(_profile.WithTesticles(edit(testicles)));
    }

    private void EditVagina(Func<VaginaProfile, VaginaProfile> edit)
    {
        if (_profile.Vagina is { } vagina)
            Commit(_profile.WithVagina(edit(vagina)));
    }

    private void EditBreasts(Func<BreastsProfile, BreastsProfile> edit)
    {
        if (_profile.Breasts is { } breasts)
            Commit(_profile.WithBreasts(edit(breasts)));
    }

    /// <summary>A newly included penis comes from the species' typical male anatomy, with its testicles.</summary>
    private void SetPenisIncluded(bool included)
    {
        if (!included)
        {
            // Also removes the testicles, its linked option.
            Commit(_profile.WithPenis(null));
            return;
        }

        if (_profile.Penis != null)
            return;

        var seed = Seed(true);
        var settings = GenitalProfileValidator.GetSettings(_proto);
        var penis = seed.Penis ?? GenitalColorDefaults.ApplyPenis(
            new PenisProfile(FirstShape(GenitalSlot.Penis), settings.DefaultLengthCm),
            GenitalColorDefaults.TissueColorFor(_species, _proto));

        _sheathChoice = penis.Sheath;
        Commit(_profile.WithPenis(penis).WithTesticles(seed.Penis != null ? seed.Testicles : null));
    }

    /// <summary>A newly included vagina comes from the species' typical female anatomy, with a womb unless that says otherwise.</summary>
    private void SetVaginaIncluded(bool included)
    {
        if (!included)
        {
            // Also removes the womb.
            Commit(_profile.WithVagina(null));
            return;
        }

        if (_profile.Vagina != null)
            return;

        var seed = Seed(false);
        var vagina = seed.Vagina ?? GenitalColorDefaults.ApplyVagina(
            new VaginaProfile(FirstShape(GenitalSlot.Vagina)),
            GenitalColorDefaults.TissueColorFor(_species, _proto));

        Commit(_profile.WithVagina(vagina).WithWomb(seed.Vagina == null || seed.Womb));
    }

    /// <summary>Newly included breasts come from the species' typical female anatomy, or the first shape at the default cup.</summary>
    private void SetBreastsIncluded(bool included)
    {
        if (!included)
        {
            Commit(_profile.WithBreasts(null));
            return;
        }

        if (_profile.Breasts != null)
            return;

        var settings = GenitalProfileValidator.GetSettings(_proto);
        var breasts = Seed(false).Breasts ?? GenitalColorDefaults.ApplyBreasts(
            new BreastsProfile(FirstShape(GenitalSlot.Breasts), settings.DefaultCup));

        Commit(_profile.WithBreasts(breasts));
    }

    private void SetTesticleType(TesticleType type)
    {
        if (type == TesticleType.None)
        {
            Commit(_profile.WithTesticles(null));
            return;
        }

        var settings = GenitalProfileValidator.GetSettings(_proto);
        var testicles = _profile.Testicles?.With(type: type)
                        ?? GenitalColorDefaults.ApplyTesticles(new TesticlesProfile(type, settings.DefaultTesticleSize));
        Commit(_profile.WithTesticles(testicles));
    }

    /// <summary>The remembered sheath comes back with a shape that allows it; the validator removes it otherwise.</summary>
    private void OnPenisShapePicked(ProtoId<GenitalShapePrototype> shape)
    {
        EditPenis(p => p.With(shape: shape, sheath: _sheathChoice));
    }

    /// <summary>Custom colour when "match skin" is turned off: the stored one, or the skin colour instead of untinted white.</summary>
    private Color SeedColour(Color stored)
    {
        return stored.Equals(Color.White) ? _skin : stored;
    }

    #endregion

    #region Typical anatomy

    /// <summary>The species' typical anatomy for one sex; null without a preset.</summary>
    private GenitalProfile? PresetEntry(bool male)
    {
        var preset = GenitalColorDefaults.FindPreset(_species, _proto);
        if (preset == null)
            return null;

        return male ? preset.Male : preset.Female;
    }

    /// <summary>The typical anatomy for one sex, coloured by the default colour policy; empty without a preset.</summary>
    private GenitalProfile Seed(bool male)
    {
        return PresetEntry(male) is { } entry
            ? GenitalColorDefaults.Apply(entry, _species, _proto)
            : GenitalProfile.Empty;
    }

    /// <summary>Applies a typical anatomy entry (null clears), asking first when anything is configured.</summary>
    private void RequestPreset(GenitalProfile? entry)
    {
        if (_profile.IsEmpty)
        {
            ApplyPreset(entry);
            return;
        }

        _pendingPreset = () => ApplyPreset(entry);
        PresetConfirm.Visible = true;
    }

    /// <summary>Replaces every organ with the entry's, coloured by the default colour policy. The reveal mode is kept.</summary>
    private void ApplyPreset(GenitalProfile? entry)
    {
        HidePresetConfirm();
        var organs = entry == null ? null : GenitalColorDefaults.Apply(entry, _species, _proto);
        var result = _profile
            .WithPenis(organs?.Penis)
            .WithTesticles(organs?.Testicles)
            .WithVagina(organs?.Vagina)
            .WithWomb(organs?.Womb ?? false)
            .WithBreasts(organs?.Breasts);

        _sheathChoice = result.Penis?.Sheath ?? SheathType.None;
        Commit(result);
    }

    private void HidePresetConfirm()
    {
        _pendingPreset = null;
        PresetConfirm.Visible = false;
    }

    #endregion

    #region Display

    /// <summary>Fills every control from the profile and context, or shows the gate instead.</summary>
    private void Refresh()
    {
        _syncing = true;
        try
        {
            if (UpdateGate())
                return;

            EnsureTiles();
            var settings = GenitalProfileValidator.GetSettings(_proto);
            var tissue = GenitalColorDefaults.TissueColorFor(_species, _proto);
            RefreshHeader();
            RefreshPenis(settings, tissue);
            RefreshVagina(tissue);
            RefreshBreasts();
        }
        finally
        {
            _syncing = false;
        }
    }

    /// <summary>Shows the first gate that applies instead of the controls. True while gated.</summary>
    private bool UpdateGate()
    {
        var message = GateMessage(out var optedOut, out var consentButton);
        var gated = message != null;
        GateCard.Visible = gated;
        EditorBody.Visible = !gated;
        OpenConsentButton.Visible = consentButton;

        if (!gated)
            return false;

        GateLabel.SetMessage(message!);
        HidePresetConfirm();

        // Anatomy art only exists for players who have opted in.
        if (optedOut && _tilesBuilt)
            DisposeTiles();

        return true;
    }

    /// <summary>The gate message in the order of the design: kill switch, offline, consent, age, species; null when none applies.</summary>
    /// <param name="optedOut">The gate is the kill switch, a missing connection or missing consent.</param>
    /// <param name="consentButton">The gate offers the consent settings button.</param>
    private string? GateMessage(out bool optedOut, out bool consentButton)
    {
        optedOut = true;
        consentButton = false;

        if (!_cfg.GetCVar(WolfgateCVars.AnatomyEnabled))
            return Loc.GetString("wf-genitals-gate-disabled");

        if (!_consent.HasLoaded)
            return Loc.GetString("wf-genitals-gate-offline");

        if (!_entManager.EntitySysManager.TryGetEntitySystem(out ClientGenitalConsentSystem? consent) || !consent.ViewerHasMaster())
        {
            consentButton = true;
            return Loc.GetString("wf-genitals-gate-consent");
        }

        optedOut = false;
        var settings = GenitalProfileValidator.GetSettings(_proto);
        if (GenitalProfileValidator.IsEligible(_age, _species, settings, out var reason))
            return null;

        return reason == GenitalIssue.SpeciesExcluded
            ? Loc.GetString("wf-genitals-gate-species")
            : Loc.GetString("wf-genitals-gate-age", ("age", settings.AdultAge));
    }

    private void RefreshHeader()
    {
        var preview = PreviewSystem;
        _previewMode.Select(preview?.Mode ?? GenitalPreviewMode.AsWorn);
        _previewArousal.Select(preview?.Arousal ?? ArousalState.None);

        var hasPreset = GenitalColorDefaults.FindPreset(_species, _proto) != null;
        PresetLabel.Text = Loc.GetString("wf-genitals-preset-menu", ("species", SpeciesName()));
        PresetMaleButton.Disabled = !hasPreset;
        PresetFemaleButton.Disabled = !hasPreset;

        // Every entry is offered for every sex. They are actions, so none is lit; the tooltip names the one matching the sex.
        SetPresetHint(PresetMaleButton, hasPreset && _sex == Sex.Male);
        SetPresetHint(PresetFemaleButton, hasPreset && _sex == Sex.Female);

        var anyOrgan = !_profile.IsEmpty;
        RevealRow.Visible = anyOrgan;
        _reveal.Select(_profile.RevealMode);

        // Species without undergarment art get a note instead of the button, since there is nothing to choose.
        SpeciesUndergarmentNote.Visible = anyOrgan && !_speciesHasUndergarments;
        UndergarmentNotice.Visible = anyOrgan
                                     && _speciesHasUndergarments
                                     && !_wearsUndergarment
                                     && _profile.RevealMode == GenitalRevealMode.UndergarmentRemoval;
        PregnancyNote.Visible = _pregnancyMarking && !_profile.Womb;
        LoadFailedWarning.Visible = _profile.LoadFailed;
        SetWarnings(GeneralWarning, GeneralIssues);
    }

    private void RefreshPenis(GenitalSettingsPrototype settings, Color? tissue)
    {
        var penis = _profile.Penis;
        PenisInclude.Pressed = penis != null;
        PenisBody.Visible = penis != null;
        SetWarnings(PenisWarning, GenitalIssue.TesticlesWithoutPenis);
        SyncTiles(PenisShapes, penis?.Shape, penis == null ? tissue ?? _skin : Shown(penis.MatchSkin, penis.Color));

        if (penis == null)
            return;

        _proto.TryIndex(penis.Shape, out var shape);

        var minLength = settings.MinLengthCm;
        LengthSlider.MinValue = minLength;
        LengthSlider.MaxValue = Math.Max(minLength, settings.MaxLengthCm);
        LengthSlider.SetValueWithoutEvent(penis.LengthCm);
        LengthValue.Text = Loc.GetString("wf-genitals-length-value",
            ("cm", penis.LengthCm),
            ("step", GenitalStateBuilder.LengthToStep(penis.LengthCm, settings)));
        SetWarnings(LengthWarning, GenitalIssue.LengthClamped);

        _sheath.Select(penis.Sheath);
        var unavailable = Loc.GetString("wf-genitals-sheath-unavailable");
        foreach (var type in SheathTypes)
        {
            var allowed = type == SheathType.None || shape != null && shape.AllowedSheaths.Contains(type);
            _sheath.SetEnabled(type, allowed, unavailable);
        }

        // The remembered choice stays suppressed until a shape that allows it is picked.
        var suppressed = _sheathChoice != SheathType.None
                         && penis.Sheath == SheathType.None
                         && shape != null
                         && !shape.AllowedSheaths.Contains(_sheathChoice);
        SheathWarning.Visible = suppressed || _issues.Contains(GenitalIssue.SheathNotAllowed);
        if (SheathWarning.Visible)
            SheathWarning.SetMessage(Loc.GetString("wf-genitals-warning-SheathNotAllowed"), WarningColor);

        _penisColour.Set(penis.MatchSkin, penis.Color);
        SheathColourRow.Visible = penis.Sheath != SheathType.None;
        _sheathColour.Set(penis.SheathMatchSkin, penis.SheathColor);
        _penisVisibility.Select(penis.Visibility);

        var testicles = _profile.Testicles;
        _testicleType.Select(testicles?.Type ?? TesticleType.None);
        TesticleInternalNote.Visible = testicles is { Type: TesticleType.Internal };
        TesticleDetails.Visible = testicles is { Type: TesticleType.External };
        if (testicles is not { Type: TesticleType.External })
            return;

        var size = Math.Clamp(testicles.Size, GenitalProfileValidator.MinTesticleSize, GenitalProfileValidator.MaxTesticleSize);
        TesticleSizeSlider.SetValueWithoutEvent(size);
        TesticleSizeValue.Text = GenitalWords.TesticleSize(size);
        SetWarnings(TesticleWarning, GenitalIssue.SizeClamped);
        _testicleColour.Set(testicles.MatchSkin, testicles.Color);
        _testicleVisibility.Select(testicles.Visibility);
    }

    private void RefreshVagina(Color? tissue)
    {
        var vagina = _profile.Vagina;
        VaginaInclude.Pressed = vagina != null;
        VaginaBody.Visible = vagina != null;
        SetWarnings(VaginaWarning, GenitalIssue.WombWithoutVagina);
        SyncTiles(VaginaShapes, vagina?.Shape, vagina == null ? tissue ?? _skin : Shown(vagina.MatchSkin, vagina.Color));

        if (vagina == null)
            return;

        _vaginaColour.Set(vagina.MatchSkin, vagina.Color);
        WombCheck.Pressed = _profile.Womb;
        _vaginaVisibility.Select(vagina.Visibility);
    }

    private void RefreshBreasts()
    {
        var breasts = _profile.Breasts;
        BreastsInclude.Pressed = breasts != null;
        BreastsBody.Visible = breasts != null;
        SyncTiles(BreastShapes, breasts?.Shape, breasts == null ? _skin : Shown(breasts.MatchSkin, breasts.Color));

        if (breasts == null)
            return;

        CupSlider.SetValueWithoutEvent(breasts.Cup);
        CupValue.Text = GenitalWords.CupText(breasts.Cup);
        UddersNote.Visible = breasts.Shape == UddersShape;
        SetWarnings(CupWarning, GenitalIssue.CupClamped);
        LactationCheck.Pressed = breasts.Lactation;
        _breastColour.Set(breasts.MatchSkin, breasts.Color);
        _breastVisibility.Select(breasts.Visibility);
    }

    /// <summary>One warning line per listed issue from the last validation; hidden when there is none.</summary>
    private void SetWarnings(RichTextLabel label, params GenitalIssue[] issues)
    {
        var lines = new List<string>();
        foreach (var issue in issues)
        {
            if (_issues.Contains(issue))
                lines.Add(Loc.GetString($"wf-genitals-warning-{issue}"));
        }

        label.Visible = lines.Count > 0;
        if (lines.Count > 0)
            label.SetMessage(string.Join("\n", lines), WarningColor);
    }

    /// <summary>Tooltip only: a preset is a one-shot action, so it is never shown pressed.</summary>
    private static void SetPresetHint(Button button, bool matchesSex)
    {
        button.ToolTip = matchesSex ? Loc.GetString("wf-genitals-preset-suggested") : null;
    }

    /// <summary>Colour an organ is drawn in.</summary>
    private Color Shown(bool matchSkin, Color color)
    {
        return matchSkin ? _skin : color;
    }

    private string SpeciesName()
    {
        return _proto.TryIndex<SpeciesPrototype>(_species, out var species) ? Loc.GetString(species.Name) : _species;
    }

    /// <summary>Whether the species can wear any undergarment marking at all (Resomi cannot).</summary>
    private bool SpeciesHasUndergarments(string species)
    {
        if (!_proto.HasIndex<SpeciesPrototype>(species))
            return true;

        return _markingManager.MarkingsByCategoryAndSpecies(MarkingCategories.UndergarmentTop, species).Count > 0
               || _markingManager.MarkingsByCategoryAndSpecies(MarkingCategories.UndergarmentBottom, species).Count > 0;
    }

    private GenitalPreviewSystem? PreviewSystem =>
        _entManager.EntitySysManager.TryGetEntitySystem(out GenitalPreviewSystem? preview) ? preview : null;

    #endregion

    #region Shape tiles

    private GridContainer[] ShapeGrids()
    {
        return new[] { PenisShapes, VaginaShapes, BreastShapes };
    }

    /// <summary>Builds the shape tiles once the gates pass.</summary>
    private void EnsureTiles()
    {
        if (_tilesBuilt)
            return;

        _tilesBuilt = true;
        BuildTiles(PenisShapes, _penisTiles, GenitalSlot.Penis, OnPenisShapePicked);
        BuildTiles(VaginaShapes, _vaginaTiles, GenitalSlot.Vagina, shape => EditVagina(v => v.With(shape: shape)));
        BuildTiles(BreastShapes, _breastTiles, GenitalSlot.Breasts, shape => EditBreasts(b => b.With(shape: shape)));
        UpdateColumns();
    }

    private void BuildTiles(GridContainer grid, ButtonGroup group, GenitalSlot slot, Action<ProtoId<GenitalShapePrototype>> picked)
    {
        foreach (var shape in SortedShapes(slot))
        {
            var art = shape.Preview is { } previewId && _proto.TryIndex(previewId, out var previewShape) ? previewShape : shape;
            var tile = new WolfgateGenitalShapeTile(shape, art, _direction) { Group = group };
            if (shape.ID == UddersShape.Id)
                tile.ToolTip = Loc.GetString(shape.Name) + "\n" + Loc.GetString("wf-genitals-udders-note");

            ProtoId<GenitalShapePrototype> id = shape.ID;
            tile.OnPressed += _ =>
            {
                if (!_syncing)
                    picked(id);
            };
            grid.AddChild(tile);
        }
    }

    private void DisposeTiles()
    {
        // Disposed rather than removed: a ButtonGroup only lets go of disposed buttons.
        foreach (var grid in ShapeGrids())
        {
            grid.DisposeAllChildren();
        }

        _tilesBuilt = false;
    }

    /// <summary>Lights the selected shape and tints every tile with the colour the organ would be drawn in.</summary>
    private static void SyncTiles(GridContainer grid, ProtoId<GenitalShapePrototype>? selected, Color tint)
    {
        foreach (var child in grid.Children)
        {
            if (child is not WolfgateGenitalShapeTile tile)
                continue;

            tile.Pressed = selected == tile.Shape;
            tile.Tint = tint;
        }
    }

    private void UpdateColumns()
    {
        // The cards and the tab add about 48 px of margin around the grids.
        var columns = Math.Max(1, (int) ((Width - 48) / WolfgateGenitalShapeTile.TileWidth));
        foreach (var grid in ShapeGrids())
        {
            if (grid.Columns != columns)
                grid.Columns = columns;
        }
    }

    private IEnumerable<GenitalShapePrototype> SortedShapes(GenitalSlot slot)
    {
        return _proto.EnumeratePrototypes<GenitalShapePrototype>()
            .Where(s => s.Slot == slot)
            .OrderBy(s => s.SortOrder)
            .ThenBy(s => s.ID, StringComparer.Ordinal);
    }

    /// <summary>The first shape in tile order; empty when the slot has none, which the validator then drops.</summary>
    private ProtoId<GenitalShapePrototype> FirstShape(GenitalSlot slot)
    {
        return SortedShapes(slot).FirstOrDefault()?.ID ?? string.Empty;
    }

    #endregion

    /// <summary>Segmented choice: a row of CreatorToggle buttons with one lit, like WolfgateSexSelector.</summary>
    private sealed class Segmented<T> : BoxContainer where T : struct, Enum
    {
        private readonly ButtonGroup _group = new();
        private readonly Dictionary<T, Button> _buttons = new();
        private readonly Dictionary<T, string?> _tooltips = new();

        /// <summary>Raised when the player picks an option; not raised by Select.</summary>
        public event Action<T>? OnSelected;

        public Segmented()
        {
            Orientation = LayoutOrientation.Horizontal;
            SeparationOverride = 4;
        }

        public void Add(T value, string text, string? tooltip = null)
        {
            var button = new Button
            {
                Text = text,
                ToolTip = tooltip,
                Group = _group,
                StyleClasses = { StyleWolfgate.StyleClassCreatorToggle },
            };
            button.OnPressed += _ => OnSelected?.Invoke(value);
            _buttons[value] = button;
            _tooltips[value] = tooltip;
            AddChild(button);
        }

        /// <summary>Lights an option without raising OnSelected.</summary>
        public void Select(T value)
        {
            if (_buttons.TryGetValue(value, out var button))
                button.Pressed = true;
        }

        /// <summary>Enables or disables an option; a disabled option explains itself in its tooltip.</summary>
        public void SetEnabled(T value, bool enabled, string disabledTooltip)
        {
            if (!_buttons.TryGetValue(value, out var button))
                return;

            button.Disabled = !enabled;
            button.ToolTip = enabled ? _tooltips[value] : disabledTooltip;
        }
    }

    /// <summary>Colour of one organ part: a match-skin check box, and a colour picker while the colour is custom.</summary>
    private sealed class ColourRow : BoxContainer
    {
        private readonly CheckBox _match;
        private readonly WolfgateColorPicker _picker;

        public event Action<bool>? OnMatchChanged;
        public event Action<Color>? OnColorPicked;

        public ColourRow(string caption)
        {
            Orientation = LayoutOrientation.Vertical;
            SeparationOverride = 4;

            _match = new CheckBox
            {
                Text = Loc.GetString("wf-genitals-match-skin"),
                VerticalAlignment = VAlignment.Center,
            };
            _match.OnToggled += args => OnMatchChanged?.Invoke(args.Pressed);

            _picker = new WolfgateColorPicker { HorizontalExpand = true };
            _picker.OnColorChanged += color => OnColorPicked?.Invoke(color);

            AddChild(new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                SeparationOverride = 8,
                Children =
                {
                    new Label
                    {
                        Text = caption,
                        MinWidth = LabelWidth,
                        VerticalAlignment = VAlignment.Center,
                        StyleClasses = { StyleWolfgate.StyleClassCreatorFieldLabel },
                    },
                    _match,
                },
            });
            AddChild(_picker);
        }

        /// <summary>Shows the setting without raising events.</summary>
        public void Set(bool matchSkin, Color color)
        {
            _match.Pressed = matchSkin;
            _picker.Color = color;
            _picker.Visible = !matchSkin;
        }
    }
}
