"""Writes the autodoc's voice prototype from the same line table that generated the ogg files.

Usage: python Tools/_WF/wolfmed/gen_autodoc_voice_protos.py

Every AutodocVoiceEvent member appears in EVENTS with at least one line id, and every line id it names is a
row of gen_autodoc_voice.LINES, so the prototype cannot reference a file that was never rendered. The
priority column comes along with the line, which is what the pod's voice queue sorts on.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from gen_autodoc_voice import LINES, PREFIX  # noqa: E402

PROTO = "Resources/Prototypes/_WF/Wolfmed/Autodoc/voice.yml"
AUDIO = "/Audio/_WF/Wolfmed/Autodoc/voice"

EVENTS = [
    ("Boot", ["boot"]),
    ("Greeting", ["greeting-1", "greeting-2", "greeting-3"]),
    ("SelfService", ["self-service"]),
    ("OperatorStart", ["operator-start"]),
    ("QueueEmpty", ["queue-empty"]),
    ("NoOccupant", ["no-occupant"]),
    ("Anaesthetic", ["anaesthetic"]),
    ("NoAnaesthetic", ["no-anaesthetic"]),
    ("StepIncision", ["step-incision"]),
    ("StepRetract", ["step-retract"]),
    ("StepClamp", ["step-clamp"]),
    ("StepCauterise", ["step-cauterise"]),
    ("StepSaw", ["step-saw"]),
    ("StepDrill", ["step-drill"]),
    ("StepSetBone", ["step-setbone"]),
    ("StepBoneGel", ["step-bonegel"]),
    ("StepSuture", ["step-suture"]),
    ("StepClose", ["step-close"]),
    ("StepRemovePart", ["step-removepart"]),
    ("StepAttachPart", ["step-attachpart"]),
    ("StepRemoveOrgan", ["step-removeorgan"]),
    ("StepInsertOrgan", ["step-insertorgan"]),
    ("StepEmbedded", ["step-embedded"]),
    ("StepTend", ["step-tend"]),
    ("StepRelocate", ["step-relocate"]),
    ("StepWeld", ["step-weld"]),
    ("StepWrench", ["step-wrench"]),
    ("StepWire", ["step-wire"]),
    ("StepAmputate", ["step-amputate"]),
    ("StepEvisceration", ["step-evisceration"]),
    ("StepCavity", ["step-cavity"]),
    ("StepGeneric", ["step-generic"]),
    ("RequirePart", ["require-part"]),
    ("RequireOrgan", ["require-organ"]),
    ("RequireItem", ["require-item"]),
    ("WrongItem", ["wrong-item"]),
    ("ItemAccepted", ["item-accepted"]),
    ("ReagentMissing", ["reagent-missing"]),
    ("ReagentIgnored", ["reagent-ignored"]),
    ("Paused", ["paused"]),
    ("Resumed", ["resumed"]),
    ("Aborted", ["aborted"]),
    ("EmergencyEject", ["emergency-eject"]),
    ("PowerLost", ["power-lost"]),
    ("PowerRestored", ["power-restored"]),
    ("LidForced", ["lid-forced"]),
    ("Slip", ["slip"]),
    ("SlipFix", ["slip-fix"]),
    ("Unconscious", ["unconscious"]),
    ("Critical", ["critical"]),
    ("DefibMissing", ["defib-missing"]),
    ("DefibCharge", ["defib-charge"]),
    ("DefibSuccess", ["defib-success"]),
    ("DefibFailure", ["defib-failure"]),
    ("DefibBlocked", ["defib-blocked"]),
    ("DefibGaveUp", ["defib-gaveup"]),
    ("Complete", ["complete-1", "complete-2", "complete-3"]),
    ("QueueComplete", ["queue-complete"]),
    ("DiskMissing", ["disk-missing"]),
    ("DiskInserted", ["disk-inserted"]),
    ("DiskRemoved", ["disk-removed"]),
    ("Plan", ["plan"]),
    ("AutoEngaged", ["auto-engaged"]),
    ("AutoNothing", ["auto-nothing"]),
    ("AutoOff", ["auto-off"]),
    ("Dying", ["dying"]),
    ("Goodbye", ["goodbye"]),
    ("Stall", ["stall"]),
    ("Clothing", ["clothing"]),
    ("ClothingAuto", ["clothing-auto"]),
    ("Cutting", ["cutting"]),
    ("Removing", ["removing"]),
    ("Transfusing", ["transfuse"]),
    ("SedationLimit", ["sedation-limit"]),
    ("DeadProceeding", ["dead-proceeding"]),
    ("Idle", ["idle-1", "idle-2", "idle-3", "idle-4", "idle-5"]),
    ("Emag", ["emag-1", "emag-2", "emag-3", "emag-4", "emag-5"]),
    ("Offline", ["offline"]),
]


def main():
    ids = {line_id for line_id, _, _, _ in LINES}
    for _, variants in EVENTS:
        for variant in variants:
            if variant not in ids:
                raise SystemExit("event names a line with no file: " + variant)

    os.makedirs(os.path.dirname(PROTO), exist_ok=True)
    out = ["# Generated by Tools/_WF/wolfmed/gen_autodoc_voice_protos.py. Edit the script, not this file.",
           "- type: autodocVoice",
           "  id: WolfmedAutodocVoiceSam",
           "  lines:"]
    for line_id, _, _, priority in LINES:
        out.append("    " + line_id + ":")
        out.append("      sound:")
        out.append("        path: " + AUDIO + "/" + line_id + ".ogg")
        out.append("      message: " + PREFIX + line_id)
        out.append("      priority: " + priority)
    out.append("  events:")
    for event, variants in EVENTS:
        out.append("    " + event + ": [" + ", ".join(variants) + "]")

    with open(PROTO, "w", newline="\n") as handle:
        handle.write("\n".join(out) + "\n")

    print("wrote", len(LINES), "lines and", len(EVENTS), "events")


if __name__ == "__main__":
    main()
