using Content.Client.UserInterface.Controls;
using Content.Shared.Lathe;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lathe.UI;

[GenerateTypedNameReferences]
public sealed partial class FabricationSiloMenu : FancyWindow
{
    public event Action<NetEntity>? OnClientPressed;
    public event Action<NetEntity>? OnPartPressed;

    public FabricationSiloMenu()
    {
        RobustXamlLoader.Load(this);
        ClientList.OnItemSelected += args =>
        {
            if (ClientList[args.ItemIndex].Metadata is NetEntity uid)
                OnClientPressed?.Invoke(uid);
        };
        StockList.OnItemSelected += args =>
        {
            if (StockList[args.ItemIndex].Metadata is NetEntity uid)
                OnPartPressed?.Invoke(uid);
        };
    }

    public void Update(FabricationSiloBuiState state)
    {
        var parts = state.Kind == FabricationSiloKind.Parts;
        KindLabel.Text = parts ? "PARTS SILO" : "CHEMICAL SILO";
        StockLabel.Text = parts ? "Stored components" : "Stored reagents";
        HintLabel.Text = parts
            ? "Use a recipe component on the silo to deposit it. Select one here to eject it."
            : "Use a reagent container on the silo to deposit its recipe chemicals.";

        var clients = new List<ItemList.Item>();
        foreach (var (uid, label) in state.Clients)
            clients.Add(new ItemList.Item(ClientList) { Metadata = uid, Text = label });
        ClientList.SetItems(clients, (a, b) => ((NetEntity)a.Metadata!).CompareTo((NetEntity)b.Metadata!));

        var stock = new List<ItemList.Item>();
        foreach (var (uid, label) in state.Stock)
            stock.Add(new ItemList.Item(StockList) { Metadata = uid, Text = label });
        StockList.SetItems(stock, (a, b) => string.Compare(a.Text, b.Text, StringComparison.Ordinal));
    }
}
