using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared.Lathe;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lathe.UI;

[GenerateTypedNameReferences]
public sealed partial class FabricationSiloMenu : FancyWindow
{
    public event Action<NetEntity>? OnClientPressed;
    public event Action<NetEntity>? OnPartPressed;
    private FabricationSiloBuiState? _state;

    public FabricationSiloMenu()
    {
        RobustXamlLoader.Load(this);
        SearchBar.OnTextChanged += _ => PopulateStock();
    }

    public void Update(FabricationSiloBuiState state)
    {
        _state = state;
        var parts = state.Kind == FabricationSiloKind.Parts;
        Title = Loc.GetString(parts ? "fabrication-silo-parts" : "fabrication-silo-chemicals");
        KindLabel.Text = Title;
        StockLabel.Text = Loc.GetString(parts ? "fabrication-silo-components" : "fabrication-silo-reagents");
        HintLabel.SetMessage(Loc.GetString(parts ? "fabrication-silo-parts-hint" : "fabrication-silo-chemicals-hint"));

        ClientList.DisposeAllChildren();
        foreach (var (uid, label, linked, available) in state.Clients.OrderByDescending(c => c.Linked).ThenBy(c => c.Label))
        {
            var row = new BoxContainer { HorizontalExpand = true, SeparationOverride = 8 };
            var details = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, HorizontalExpand = true };
            details.AddChild(new Label { Text = label, ToolTip = label, ClipText = true, HorizontalExpand = true });
            details.AddChild(new Label
            {
                Text = Loc.GetString(linked
                    ? available ? "fabrication-silo-connected" : "fabrication-silo-unavailable"
                    : "fabrication-silo-available"),
                StyleClasses = { "LabelSubText" },
            });
            row.AddChild(details);
            var button = new Button
            {
                Text = Loc.GetString(linked ? "fabrication-silo-disconnect" : "fabrication-silo-connect"),
                MinWidth = 100,
                VerticalAlignment = VAlignment.Center,
            };
            button.OnPressed += _ => OnClientPressed?.Invoke(uid);
            row.AddChild(button);
            ClientList.AddChild(WrapRow(row));
        }
        if (state.Clients.Count == 0)
        {
            var empty = new RichTextLabel();
            empty.SetMessage(Loc.GetString("fabrication-silo-no-machines"));
            ClientList.AddChild(empty);
        }
        PopulateStock();
    }

    private void PopulateStock()
    {
        StockList.DisposeAllChildren();
        if (_state == null)
            return;

        foreach (var (uid, label) in _state.Stock.OrderBy(s => s.Label))
        {
            if (!label.Contains(SearchBar.Text.Trim(), StringComparison.OrdinalIgnoreCase))
                continue;
            var row = new BoxContainer { HorizontalExpand = true, SeparationOverride = 8 };
            var name = new RichTextLabel { HorizontalExpand = true, VerticalAlignment = VAlignment.Center };
            name.SetMessage(label);
            row.AddChild(name);
            if (uid is { } part)
            {
                var eject = new Button
                {
                    Text = Loc.GetString("fabrication-silo-eject"),
                    ToolTip = Loc.GetString("fabrication-silo-eject-hint"),
                    MinWidth = 100,
                    VerticalAlignment = VAlignment.Center,
                };
                eject.OnPressed += _ => OnPartPressed?.Invoke(part);
                row.AddChild(eject);
            }
            StockList.AddChild(WrapRow(row));
        }
        if (StockList.ChildCount == 0)
            StockList.AddChild(new Label { Text = Loc.GetString("fabrication-silo-empty"), StyleClasses = { "LabelSubText" } });
    }

    private static PanelContainer WrapRow(Control row)
    {
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = new Color(25, 31, 37),
                BorderColor = new Color(53, 66, 75),
                BorderThickness = new Thickness(1),
            },
        };
        row.Margin = new Thickness(8);
        panel.AddChild(row);
        return panel;
    }
}
