using Content.Shared._NF.Shipyard.Prototypes;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.ShipPreview.UI;

/// <summary>
/// Standalone window around <see cref="ShipPreviewControl"/>, used on its own for smoke testing and as a reference
/// host for other UIs that want to embed the previewer.
/// </summary>
[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class ShipPreviewWindow : DefaultWindow
{
    private VesselPrototype? _vessel;

    public ShipPreviewWindow()
    {
        RobustXamlLoader.Load(this);

        Preview.PreviewUpdated += UpdateInfo;
        ResetViewButton.OnPressed += _ => Preview.FitToGrid();

        // The preview map is only freed once every window using it has closed.
        OnClose += () =>
        {
            Preview.PreviewUpdated -= UpdateInfo;
            Preview.Release();
        };

        UpdateInfo();
    }

    /// <summary>
    /// Opens a preview window for a vessel.
    /// </summary>
    public static ShipPreviewWindow Open(VesselPrototype vessel)
    {
        var window = new ShipPreviewWindow();
        window.SetVessel(vessel);
        window.OpenCentered();
        return window;
    }

    /// <summary>
    /// Shows a vessel, or clears the preview when given null.
    /// </summary>
    public void SetVessel(VesselPrototype? vessel)
    {
        _vessel = vessel;
        Preview.SetVessel(vessel);
        UpdateInfo();
    }

    private void UpdateInfo()
    {
        VesselLabel.Text = _vessel == null
            ? Loc.GetString("wf-ship-preview-no-vessel")
            : _vessel.Name;

        InfoLabel.Text = Preview.HasPreview
            ? Loc.GetString("wf-ship-preview-info",
                ("width", Preview.GridSize.X),
                ("height", Preview.GridSize.Y),
                ("count", Preview.TileCount))
            : string.Empty;
    }
}
