using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private IClientConsoleHost _consoleHost = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);
            SetAnchorPreset(SkinScanlines, LayoutPreset.Wide); // WOLFGATE(Stylesheets): skin scanlines cover the whole screen

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            // WOLFGATE(Stylesheets) START: menu entry for character setup; un-readies first like LobbyState.OnSetupPressed
            CustomizeButton.OnPressed += _ =>
            {
                if (ReadyButton.ToggleMode)
                    _consoleHost.ExecuteCommand("toggleready False");
                SwitchState(LobbyGuiState.CharacterSetup);
            };
            // WOLFGATE END
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    // WOLFGATE(Stylesheets) START: the creator takes the whole screen, so the chat dock always hides
                    // var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    // var setupWidth = (float) LeftSide.PixelWidth;
                    //
                    // if (1 - (setupWidth / actualWidth) > 0.30)
                    // {
                    //     RightSide.Visible = false;
                    // }
                    RightSide.Visible = false;
                    // WOLFGATE END

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
