using Content.Shared.Atmos;
using Robust.Shared.GameStates;

namespace Content.Shared._Mono.Atmos.Components;

/// <summary>
/// Causes a gas tank to slowly regenerate its gas contents.
/// </summary>
[RegisterComponent, NetworkedComponent]
public sealed partial class SelfRechargingGasTankComponent : Component
{
    /// <summary>
    /// Amount of gas regenerated per second, in moles.
    /// </summary>
    [DataField]
    public float RechargeRate = 0.05f;

    /// <summary>
    /// Maximum pressure the tank will recharge to, in kPa.
    /// </summary>
    [DataField]
    public float MaxPressure = 51.2f;

    /// <summary>
    /// Temperature of the generated gas, in Kelvin.
    /// </summary>
    [DataField]
    public float GasTemperature = 293.15f;

    /// <summary>
    /// Gases regenerated by the tank and their relative ratios.
    /// </summary>
    [DataField]
    public Dictionary<Gas, float> Gases = new();
}
