using System.Text;
using Content.Shared._WF.ShipAccess;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.ShipAccess;

/// <summary>Four-digit keypad for a code door: 0-9, clear and enter. The entered digits show masked.</summary>
[GenerateTypedNameReferences]
public sealed partial class ShipAccessKeypadWindow : DefaultWindow
{
    private readonly StringBuilder _entered = new();

    /// <summary>The user pressed enter with four digits in.</summary>
    public event Action<string>? Submitted;

    public ShipAccessKeypadWindow()
    {
        RobustXamlLoader.Load(this);

        for (var digit = 1; digit <= 9; digit++)
            Keys.AddChild(Key(digit.ToString(), Digit(digit)));

        Keys.AddChild(Key(Loc.GetString("ship-access-keypad-clear"), Clear));
        Keys.AddChild(Key("0", Digit(0)));
        Keys.AddChild(Key(Loc.GetString("ship-access-keypad-enter"), Submit));
        UpdateLabel();
    }

    private static Button Key(string text, Action pressed)
    {
        var button = new Button { Text = text, MinSize = new System.Numerics.Vector2(56, 48) };
        button.AddStyleClass("ButtonSquare");
        button.OnPressed += _ => pressed();
        return button;
    }

    private Action Digit(int digit)
    {
        return () =>
        {
            if (_entered.Length >= WFShipAccessSystem.CodeLength)
                return;

            _entered.Append((char) ('0' + digit));
            UpdateLabel();
        };
    }

    private void Clear()
    {
        _entered.Clear();
        UpdateLabel();
    }

    private void Submit()
    {
        var code = _entered.ToString();
        if (!WFShipAccessSystem.IsValidCode(code))
            return;

        Submitted?.Invoke(code);
        Close();
    }

    private void UpdateLabel()
    {
        var sb = new StringBuilder();
        for (var i = 0; i < WFShipAccessSystem.CodeLength; i++)
        {
            if (i > 0)
                sb.Append(' ');

            sb.Append(i < _entered.Length ? '*' : '_');
        }

        CodeLabel.Text = sb.ToString();
    }
}
