using System.Linq;
using System.Text;
using Content.Shared._WF.ShipAccess;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Timing;

namespace Content.Client._WF.ShipAccess;

/// <summary>
/// Shuttle console tab where the owner sees and edits who may board: lock, allow list and nearby people to add.
/// Reads WFShipAccessComponent straight off the networked grid; every change goes to the server as a message.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ShipAccessScreen : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPlayerManager _player = default!;

    private const float RefreshInterval = 0.5f;
    private static readonly Color Readout = Color.FromHex("#00ff2a");

    private readonly WFShipAccessSystem _access;
    private readonly EntityLookupSystem _lookup;
    private readonly SharedTransformSystem _transform;

    private EntityUid? _grid;
    private EntityUid? _console;
    private float _accumulator = RefreshInterval;
    private string? _listSnapshot;
    private string? _nearbySnapshot;
    private readonly Dictionary<NetUserId, CheckBox> _builderChecks = new();

    /// <summary>The owner flipped the lock checkbox.</summary>
    public event Action<bool>? LockedChanged;

    /// <summary>The owner pressed Add on a nearby person.</summary>
    public event Action<NetEntity>? AddRequested;

    /// <summary>The owner pressed Remove on a listed person.</summary>
    public event Action<NetUserId>? RemoveRequested;

    /// <summary>The owner flipped a listed person's Builder checkbox.</summary>
    public event Action<NetUserId, bool>? BuilderChanged;

    /// <summary>The viewer wants to adopt an unowned ship.</summary>
    public event Action? ClaimRequested;

    public ShipAccessScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _access = _entManager.System<WFShipAccessSystem>();
        _lookup = _entManager.System<EntityLookupSystem>();
        _transform = _entManager.System<SharedTransformSystem>();

        LockedCheck.OnToggled += args => LockedChanged?.Invoke(args.Pressed);
        ClaimButton.OnPressed += _ => ClaimRequested?.Invoke();
    }

    /// <summary>The grid whose access is shown; null blanks the tab.</summary>
    public void SetShuttle(EntityUid? grid)
    {
        _grid = grid;
        _listSnapshot = null;
        _nearbySnapshot = null;
        _accumulator = RefreshInterval;
    }

    /// <summary>The console the nearby list is measured from.</summary>
    public void SetConsole(EntityUid? console)
    {
        _console = console;
        _listSnapshot = null;
        _nearbySnapshot = null;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!Visible)
            return;

        _accumulator += args.DeltaSeconds;
        if (_accumulator < RefreshInterval)
            return;

        _accumulator = 0f;
        Refresh();
    }

    /// <summary>
    /// Re-reads the grid and rebuilds the rows only when something shown has changed, so a checkbox is
    /// never rebuilt under the cursor. The nearby list has its own snapshot, so people walking past the
    /// console leave the allow list rows alone. Checkbox states are re-synced every call regardless.
    /// </summary>
    public void Refresh()
    {
        _entManager.TryGetComponent<WFShipAccessComponent>(_grid, out var comp);
        var localId = _player.LocalSession?.UserId;
        var isOwner = comp != null && localId != null && _access.IsOwner((_grid!.Value, comp), localId.Value);
        var claimable = _grid != null && (comp == null || !comp.HasOwner);
        // The client can't see deeds, so the server answers a claim it refuses with its own popup.
        var canClaim = claimable && localId != null;

        var sb = new StringBuilder();
        sb.Append(isOwner).Append('|').Append(claimable).Append('|').Append(canClaim).Append('|');
        if (comp != null)
        {
            sb.Append(comp.OwnerUserId.UserId.ToString()).Append('|').Append(comp.OwnerName).Append('|').Append(comp.Mode.ToString()).Append('|').Append(comp.Locked).Append('|');
            foreach (var entry in comp.AllowList)
                sb.Append(entry.UserId.UserId.ToString()).Append(',').Append(entry.Name).Append(',').Append(entry.Label).Append(',').Append(entry.Builder).Append(';');
        }
        else if (_grid != null)
            sb.Append(_access.IsFactionGrid(_grid.Value, out _));

        var listSnapshot = sb.ToString();
        if (listSnapshot != _listSnapshot)
        {
            _listSnapshot = listSnapshot;
            RebuildList(comp, isOwner, claimable, canClaim);
        }

        var nearby = isOwner ? FindNearby(comp!) : new List<(EntityUid Uid, string Name)>();
        sb.Clear();
        sb.Append(isOwner).Append('|');
        foreach (var (uid, name) in nearby)
            sb.Append(uid.Id).Append(',').Append(name).Append(';');

        var nearbySnapshot = sb.ToString();
        if (nearbySnapshot != _nearbySnapshot)
        {
            _nearbySnapshot = nearbySnapshot;
            RebuildNearby(isOwner, nearby);
        }

        SyncChecks(comp);
    }

    private void RebuildList(WFShipAccessComponent? comp, bool isOwner, bool claimable, bool canClaim)
    {
        ReadOnlyLabel.Visible = !isOwner && !claimable;
        ClaimBox.Visible = claimable;
        ClaimButton.Disabled = !canClaim;
        LockedCheck.Visible = isOwner;
        LockedLabel.Visible = !isOwner;

        OwnerLabel.Text = comp != null && comp.HasOwner ? comp.OwnerName : Loc.GetString("ship-access-owner-none");
        var faction = comp != null ? comp.Mode == WFShipAccessMode.Faction : _grid != null && _access.IsFactionGrid(_grid.Value, out _);
        ModeLabel.Text = Loc.GetString(faction ? "ship-access-mode-faction" : "ship-access-mode-private");
        LockedLabel.Text = comp == null ? "-" : Loc.GetString(comp.Locked ? "ship-access-locked-yes" : "ship-access-locked-no");

        _builderChecks.Clear();
        AllowListContainer.DisposeAllChildren();
        if (comp != null)
        {
            foreach (var entry in comp.AllowList)
                AllowListContainer.AddChild(EntryRow(entry, isOwner));
        }

        AllowListEmptyLabel.Visible = AllowListContainer.ChildCount == 0;
    }

    private void RebuildNearby(bool isOwner, List<(EntityUid Uid, string Name)> nearby)
    {
        NearbyBox.Visible = isOwner;
        NearbyContainer.DisposeAllChildren();
        foreach (var (uid, name) in nearby)
            NearbyContainer.AddChild(NearbyRow(uid, name));

        NearbyEmptyLabel.Visible = nearby.Count == 0;
    }

    /// <summary>Server state wins over a click the server refused.</summary>
    private void SyncChecks(WFShipAccessComponent? comp)
    {
        if (comp == null)
            return;

        LockedCheck.Pressed = comp.Locked;
        foreach (var entry in comp.AllowList)
        {
            if (_builderChecks.TryGetValue(entry.UserId, out var check))
                check.Pressed = entry.Builder;
        }
    }

    private Control EntryRow(WFShipAccessEntry entry, bool editable)
    {
        var row = Row();
        row.AddChild(new Label { Text = entry.Name, HorizontalExpand = true, VerticalAlignment = VAlignment.Center, FontColorOverride = Readout });

        if (entry.Label.Length > 0)
        {
            row.AddChild(new Label
            {
                Text = entry.Label,
                StyleClasses = { "LabelSecondaryColor" },
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(0, 0, 8, 0),
            });
        }

        if (!editable)
            return row;

        var userId = entry.UserId;
        var builder = new CheckBox
        {
            Text = Loc.GetString("ship-access-builder"),
            Pressed = entry.Builder,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(0, 0, 8, 0),
        };
        builder.OnToggled += args => BuilderChanged?.Invoke(userId, args.Pressed);
        _builderChecks[userId] = builder;
        row.AddChild(builder);

        var remove = new Button { Text = Loc.GetString("ship-access-remove"), MinWidth = 80 };
        remove.AddStyleClass("ButtonSquare");
        remove.OnPressed += _ => RemoveRequested?.Invoke(userId);
        row.AddChild(remove);
        return row;
    }

    private Control NearbyRow(EntityUid uid, string name)
    {
        var row = Row();
        row.AddChild(new Label { Text = name, HorizontalExpand = true, VerticalAlignment = VAlignment.Center, FontColorOverride = Readout });

        var add = new Button { Text = Loc.GetString("ship-access-add"), MinWidth = 80 };
        add.AddStyleClass("ButtonSquare");
        var netEntity = _entManager.GetNetEntity(uid);
        add.OnPressed += _ => AddRequested?.Invoke(netEntity);
        row.AddChild(add);
        return row;
    }

    private static BoxContainer Row()
    {
        return new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(4, 2),
        };
    }

    /// <summary>
    /// Humanoids within adding range of the console, minus the viewer and, by name, the owner and anyone
    /// already listed. The client can't map other entities to accounts, so names are the best filter it has.
    /// </summary>
    private List<(EntityUid Uid, string Name)> FindNearby(WFShipAccessComponent comp)
    {
        var result = new List<(EntityUid Uid, string Name)>();
        if (!_entManager.TryGetComponent<TransformComponent>(_console, out var xform))
            return result;

        var local = _player.LocalEntity;
        foreach (var humanoid in _lookup.GetEntitiesInRange<HumanoidAppearanceComponent>(xform.Coordinates, WFShipAccessSystem.AddRange, LookupFlags.Uncontained))
        {
            var uid = humanoid.Owner;
            // The lookup goes by bounds; the server's Add check is centre to centre, so list only who it would take.
            if (uid == local || !_transform.InRange(xform.Coordinates, _entManager.GetComponent<TransformComponent>(uid).Coordinates, WFShipAccessSystem.AddRange))
                continue;

            var name = _entManager.GetComponent<MetaDataComponent>(uid).EntityName;
            if (name == comp.OwnerName || comp.AllowList.Any(e => e.Name == name))
                continue;

            result.Add((uid, name));
        }

        result.Sort((a, b) => string.CompareOrdinal(a.Name, b.Name));
        return result;
    }
}
