using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.MappingTools;

/// <summary>
/// The mapping tools' buttons and key reference; <see cref="MappingToolsSystem"/> wires them up.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MappingToolsWindow : FancyWindow
{
    /// <summary>
    /// Key reference rows; each id has a key line and a <c>-desc</c> line.
    /// </summary>
    private static readonly string[] Keys =
    {
        "wf-mapping-tools-key-toggle",
        "wf-mapping-tools-key-click",
        "wf-mapping-tools-key-shift-click",
        "wf-mapping-tools-key-drag",
        "wf-mapping-tools-key-shift-drag",
        "wf-mapping-tools-key-move",
        "wf-mapping-tools-key-rotate",
        "wf-mapping-tools-key-mirror",
        "wf-mapping-tools-key-delete",
        "wf-mapping-tools-key-clipboard",
        "wf-mapping-tools-key-keep-pasting",
        "wf-mapping-tools-key-clear",
        "wf-mapping-tools-key-history",
    };

    public MappingToolsWindow()
    {
        RobustXamlLoader.Load(this);

        foreach (var key in Keys)
        {
            KeyGrid.AddChild(new Label { Text = Loc.GetString(key), StyleClasses = { "LabelKeyText" } });
            KeyGrid.AddChild(new Label
            {
                Text = Loc.GetString($"{key}-desc"),
                StyleClasses = { "LabelSubText" },
                HorizontalExpand = true,
            });
        }
    }
}
