using Content.Shared._WF.Administration.GhostShortcuts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._WF.Administration.UI.GhostShortcuts;

/// <summary>
/// Asks the admin whether to ghost a body's current player before dropping another ghost into it.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GhostPossessPromptWindow : DefaultWindow
{
    public event Action? Replace;

    public GhostPossessPromptWindow(GhostPossessOccupiedEvent ev)
    {
        RobustXamlLoader.Load(this);

        // Names are player-controlled text, so they must not be parsed as markup.
        MessageLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("wf-ghost-possess-prompt-message",
            ("body", FormattedMessage.EscapeText(ev.BodyName)),
            ("ghost", FormattedMessage.EscapeText(ev.GhostPlayer)),
            ("character", FormattedMessage.EscapeText(ev.OccupantCharacter)),
            ("player", FormattedMessage.EscapeText(ev.OccupantPlayer)))));
        WarningLabel.Text = Loc.GetString("wf-ghost-possess-prompt-warning", ("character", ev.OccupantCharacter));

        ReplaceButton.OnPressed += _ =>
        {
            Replace?.Invoke();
            Close();
        };
        AbortButton.OnPressed += _ => Close();
    }
}
