using System.Collections.Generic;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Content.Shared._WF.Traders;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WF.Traders;

[GenerateTypedNameReferences]
public sealed partial class TraderShopWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _proto = default!;

    /// <summary>
    /// Item prototypes the customer has picked, in the order they first picked them.
    /// </summary>
    private List<string> _order = new();

    /// <summary>
    /// How many of each picked item, and what the server last quoted for one of it.
    /// </summary>
    private Dictionary<string, int> _basket = new();
    private Dictionary<string, int> _prices = new();

    /// <summary>
    /// The catalogue as last sent, so an unchanged refresh does not rebuild the list under the mouse.
    /// </summary>
    private List<TraderShopEntry> _entries = new();

    public event Action<Dictionary<string, int>>? OnPurchasePressed;

    public TraderShopWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchBar.OnTextChanged += _ => RebuildCatalogue();
        ClearButton.OnPressed += _ => ClearBasket();
        PurchaseButton.OnPressed += _ => OnPurchasePressed?.Invoke(new Dictionary<string, int>(_basket));
    }

    public void UpdateState(TraderShopState state)
    {
        if (!SameEntries(state.Entries))
        {
            _entries = new List<TraderShopEntry>(state.Entries);

            _prices.Clear();
            foreach (var entry in _entries)
                _prices[entry.Item] = entry.Price;

            // Anything the trader has stopped stocking falls out of the basket.
            _order.RemoveAll(item => !_prices.ContainsKey(item));
            foreach (var item in new List<string>(_basket.Keys))
            {
                if (!_prices.ContainsKey(item))
                    _basket.Remove(item);
            }

            RebuildCatalogue();
            RebuildBasket();
        }

        UpdateFooter(state);
    }

    private bool SameEntries(List<TraderShopEntry> entries)
    {
        if (entries.Count != _entries.Count)
            return false;

        for (var i = 0; i < entries.Count; i++)
        {
            if (entries[i].Item != _entries[i].Item || entries[i].Price != _entries[i].Price)
                return false;
        }

        return true;
    }

    private void RebuildCatalogue()
    {
        EntriesBox.RemoveAllChildren();

        var filter = SearchBar.Text.Trim();
        var index = 0;

        foreach (var entry in _entries)
        {
            if (filter.Length > 0
                && !GetItemName(entry.Item).Contains(filter, StringComparison.CurrentCultureIgnoreCase))
                continue;

            EntriesBox.AddChild(MakeCatalogueRow(entry, index));
            index++;
        }

        if (index == 0)
        {
            EntriesBox.AddChild(new Label
            {
                Text = Loc.GetString(filter.Length > 0 ? "trader-shop-search-empty" : "trader-shop-empty"),
                StyleClasses = { "LabelSecondaryColor" },
                Margin = new Thickness(8, 6),
            });
        }
    }

    /// <summary>
    /// Empties the basket after the trader has taken payment for it.
    /// </summary>
    public void ClearBasket()
    {
        _order.Clear();
        _basket.Clear();
        RebuildBasket();
    }

    #region Basket

    private void Add(string item)
    {
        var count = _basket.GetValueOrDefault(item);

        if (count == 0)
        {
            if (_basket.Count >= TraderShopComponent.MaxLines)
                return;

            _order.Add(item);
        }
        else if (count >= TraderShopComponent.MaxPerLine)
        {
            return;
        }

        _basket[item] = count + 1;
        RebuildBasket();
    }

    private void Remove(string item)
    {
        if (!_basket.TryGetValue(item, out var count))
            return;

        if (count <= 1)
        {
            _basket.Remove(item);
            _order.Remove(item);
        }
        else
        {
            _basket[item] = count - 1;
        }

        RebuildBasket();
    }

    private void RebuildBasket()
    {
        BasketBox.RemoveAllChildren();

        var total = 0;
        var index = 0;

        foreach (var item in _order)
        {
            if (!_basket.TryGetValue(item, out var count))
                continue;

            var price = _prices.GetValueOrDefault(item);
            total += price * count;

            BasketBox.AddChild(MakeBasketRow(item, count, price * count, index));
            index++;
        }

        if (index == 0)
        {
            BasketBox.AddChild(new Label
            {
                Text = Loc.GetString("trader-shop-basket-empty"),
                StyleClasses = { "LabelSecondaryColor" },
                Margin = new Thickness(8, 6),
            });
        }

        TotalLabel.Text = Loc.GetString("trader-shop-total",
            ("amount", BankSystemExtensions.ToSpesoString(total)));

        PurchaseButton.Disabled = _basket.Count == 0;
    }

    #endregion

    #region Rows

    private Color RowColour(int index)
    {
        return index % 2 == 0
            ? new Color(0.15f, 0.15f, 0.15f)
            : new Color(0.12f, 0.12f, 0.12f);
    }

    private Control MakeCatalogueRow(TraderShopEntry entry, int index)
    {
        var row = new Button
        {
            HorizontalExpand = true,
            StyleClasses = { "OpenBoth" },
            ModulateSelfOverride = RowColour(index),
        };

        var contents = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(8, 4),
        };

        var view = new EntityPrototypeView
        {
            SetSize = new Vector2(32, 32),
            Margin = new Thickness(0, 0, 8, 0),
            VerticalAlignment = Control.VAlignment.Center,
        };
        view.SetPrototype(entry.Item);

        contents.AddChild(view);
        contents.AddChild(new Label
        {
            Text = GetItemName(entry.Item),
            HorizontalExpand = true,
            ClipText = true,
            VerticalAlignment = Control.VAlignment.Center,
        });
        contents.AddChild(new Label
        {
            Text = BankSystemExtensions.ToSpesoString(entry.Price),
            MinWidth = 70,
            Align = Label.AlignMode.Right,
            VerticalAlignment = Control.VAlignment.Center,
        });

        row.AddChild(contents);

        var item = entry.Item;
        row.OnPressed += _ => Add(item);

        return row;
    }

    private Control MakeBasketRow(string item, int count, int lineTotal, int index)
    {
        var row = new PanelContainer
        {
            HorizontalExpand = true,
            StyleClasses = { "AngleRect" },
            ModulateSelfOverride = RowColour(index),
        };

        var contents = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(6, 4),
        };

        var view = new EntityPrototypeView
        {
            SetSize = new Vector2(32, 32),
            Margin = new Thickness(0, 0, 8, 0),
            VerticalAlignment = Control.VAlignment.Center,
        };
        view.SetPrototype(item);
        contents.AddChild(view);

        // Name on its own line so the quantity buttons never crowd it out.
        var lines = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        lines.AddChild(new Label
        {
            Text = GetItemName(item),
            HorizontalExpand = true,
            ClipText = true,
        });

        var controls = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        var less = new Button
        {
            Text = "-",
            MinWidth = 28,
            VerticalAlignment = Control.VAlignment.Center,
        };
        less.OnPressed += _ => Remove(item);

        var more = new Button
        {
            Text = "+",
            MinWidth = 28,
            Disabled = count >= TraderShopComponent.MaxPerLine,
            VerticalAlignment = Control.VAlignment.Center,
        };
        more.OnPressed += _ => Add(item);

        controls.AddChild(less);
        controls.AddChild(new Label
        {
            Text = count.ToString(),
            MinWidth = 32,
            Align = Label.AlignMode.Center,
            VerticalAlignment = Control.VAlignment.Center,
        });
        controls.AddChild(more);
        controls.AddChild(new Label
        {
            Text = BankSystemExtensions.ToSpesoString(lineTotal),
            HorizontalExpand = true,
            Align = Label.AlignMode.Right,
            VerticalAlignment = Control.VAlignment.Center,
        });

        lines.AddChild(controls);
        contents.AddChild(lines);

        row.AddChild(contents);
        return row;
    }

    private string GetItemName(string protoId)
    {
        return _proto.TryIndex<EntityPrototype>(protoId, out var proto) ? proto.Name : protoId;
    }

    #endregion

    private void UpdateFooter(TraderShopState state)
    {
        var parts = new List<string>();

        if (state.CashInZone > 0)
            parts.Add(Loc.GetString("trader-shop-zone-cash",
                ("amount", BankSystemExtensions.ToSpesoString(state.CashInZone))));

        if (state.IdName != null)
            parts.Add(Loc.GetString("trader-shop-zone-id", ("name", state.IdName)));

        ZoneLabel.Text = parts.Count == 0
            ? Loc.GetString("trader-shop-zone-none")
            : string.Join(", ", parts);

        BalanceLabel.Text = Loc.GetString("trader-shop-balance",
            ("amount", BankSystemExtensions.ToSpesoString(state.Balance)));
    }
}
