using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.Traders;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Traders;

[GenerateTypedNameReferences]
public sealed partial class TraderDialogueWindow : FancyWindow
{
    public event Action<int>? OnOptionPressed;
    public event Action<bool>? OnConfirmPressed;
    public event Action<string?>? OnTextSubmitted;

    private int _textMaxLength;

    public TraderDialogueWindow()
    {
        RobustXamlLoader.Load(this);

        AcceptButton.OnPressed += _ => OnConfirmPressed?.Invoke(true);
        DeclineButton.OnPressed += _ => OnConfirmPressed?.Invoke(false);
        TextSubmitButton.OnPressed += _ => SubmitText();
        TextEntry.OnTextEntered += _ => SubmitText();
        TextCancelButton.OnPressed += _ => OnTextSubmitted?.Invoke(null);
        TextEntry.OnTextChanged += args =>
        {
            if (_textMaxLength > 0 && args.Text.Length > _textMaxLength)
                TextEntry.Text = args.Text[.._textMaxLength];
        };
    }

    /// <summary>
    /// Shows the trader the customer is talking to.
    /// </summary>
    public void SetTrader(EntityUid trader, string name)
    {
        TraderView.SetEntity(trader);
        TraderNameLabel.Text = name;
    }

    public void UpdateState(TraderDialogueState state)
    {
        LineLabel.SetMessage(state.Line);

        ConfirmBox.Visible = state.Confirming;

        var asking = state.TextPrompt != null;
        if (asking && !TextBox.Visible)
        {
            TextEntry.Text = string.Empty;
            TextEntry.GrabKeyboardFocus();
        }

        TextBox.Visible = asking;
        TextEntry.PlaceHolder = state.TextPrompt ?? string.Empty;
        _textMaxLength = state.TextMaxLength;

        OptionsBox.RemoveAllChildren();
        if (state.Confirming || asking)
            return;

        for (var i = 0; i < state.Options.Count; i++)
        {
            var index = i;
            var button = new Button
            {
                Text = $"{i + 1}. {state.Options[i]}",
                HorizontalExpand = true,
                MinSize = new Vector2(0, 30),
                StyleClasses = { "OpenBoth" },
            };

            button.Label.Align = Label.AlignMode.Left;
            button.OnPressed += _ => OnOptionPressed?.Invoke(index);
            OptionsBox.AddChild(button);
        }
    }

    private void SubmitText()
    {
        var text = TextEntry.Text.Trim();
        if (text.Length == 0)
            return;

        OnTextSubmitted?.Invoke(text);
    }
}
