using System.Collections.Generic;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Content.Shared._WF.Traders;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Traders;

/// <summary>
/// The used ship lot: whatever the salesman has bought back so far, and a button per hull.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TraderUsedShipsWindow : FancyWindow
{
    public event Action<int>? OnBuyPressed;

    /// <summary>
    /// The lot as last sent, so a refresh of what is on the table does not rebuild the list under
    /// the mouse.
    /// </summary>
    private List<TraderUsedShipEntry> _entries = new();

    public TraderUsedShipsWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(TraderUsedShipsState state)
    {
        if (!SameEntries(state.Entries))
        {
            _entries = new List<TraderUsedShipEntry>(state.Entries);
            RebuildLot();
        }

        UpdateFooter(state);
    }

    private bool SameEntries(List<TraderUsedShipEntry> entries)
    {
        if (entries.Count != _entries.Count)
            return false;

        for (var i = 0; i < entries.Count; i++)
        {
            if (!entries[i].Equals(_entries[i]))
                return false;
        }

        return true;
    }

    private void RebuildLot()
    {
        LotBox.RemoveAllChildren();

        if (_entries.Count == 0)
        {
            LotBox.AddChild(new Label
            {
                Text = Loc.GetString("trader-used-empty"),
                StyleClasses = { "LabelSecondaryColor" },
                Margin = new Robust.Shared.Maths.Thickness(4),
            });
        }

        foreach (var entry in _entries)
            LotBox.AddChild(MakeRow(entry));
    }

    /// <summary>
    /// What the salesman can see on the table right now.
    /// </summary>
    private void UpdateFooter(TraderUsedShipsState state)
    {
        var parts = new List<string>();

        if (state.CashInZone > 0)
            parts.Add(Loc.GetString("trader-shop-zone-cash",
                ("amount", BankSystemExtensions.ToSpesoString(state.CashInZone))));

        if (state.IdName != null)
            parts.Add(Loc.GetString("trader-shop-zone-id", ("name", state.IdName)));

        ZoneLabel.Text = parts.Count == 0
            ? Loc.GetString("trader-shop-zone-none")
            : string.Join(", ", parts);

        BalanceLabel.Text = Loc.GetString("trader-shop-balance",
            ("amount", BankSystemExtensions.ToSpesoString(state.Balance)));
    }

    private BoxContainer MakeRow(TraderUsedShipEntry entry)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 6,
        };

        var text = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
        };

        text.AddChild(new Label { Text = entry.ShipName, StyleClasses = { "LabelKeyText" }, ClipText = true });
        text.AddChild(new Label
        {
            Text = Loc.GetString("trader-used-row-detail",
                ("design", entry.Design),
                ("seller", entry.Seller)),
            StyleClasses = { "LabelSecondaryColor" },
            ClipText = true,
        });

        row.AddChild(text);
        row.AddChild(new Label
        {
            Text = BankSystemExtensions.ToSpesoString(entry.Price),
            Align = Label.AlignMode.Right,
            MinWidth = 90,
            VerticalAlignment = Control.VAlignment.Center,
        });

        var buy = new Button
        {
            Text = Loc.GetString("trader-used-buy"),
            MinWidth = 80,
            StyleClasses = { "ButtonColorGreen" },
            VerticalAlignment = Control.VAlignment.Center,
        };

        var id = entry.Id;
        buy.OnPressed += _ => OnBuyPressed?.Invoke(id);
        row.AddChild(buy);

        return row;
    }
}
