using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.Traders;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Traders;

[GenerateTypedNameReferences]
public sealed partial class TraderDialogueWindow : FancyWindow
{
    public event Action<int>? OnOptionPressed;
    public event Action<bool>? OnConfirmPressed;

    public TraderDialogueWindow()
    {
        RobustXamlLoader.Load(this);

        AcceptButton.OnPressed += _ => OnConfirmPressed?.Invoke(true);
        DeclineButton.OnPressed += _ => OnConfirmPressed?.Invoke(false);
    }

    /// <summary>
    /// Shows the trader the customer is talking to.
    /// </summary>
    public void SetTrader(EntityUid trader, string name)
    {
        TraderView.SetEntity(trader);
        TraderNameLabel.Text = name;
    }

    public void UpdateState(TraderDialogueState state)
    {
        LineLabel.SetMessage(state.Line);

        ConfirmBox.Visible = state.Confirming;

        OptionsBox.RemoveAllChildren();
        if (state.Confirming)
            return;

        for (var i = 0; i < state.Options.Count; i++)
        {
            var index = i;
            var button = new Button
            {
                Text = $"{i + 1}. {state.Options[i]}",
                HorizontalExpand = true,
                MinSize = new Vector2(0, 30),
                StyleClasses = { "OpenBoth" },
            };

            button.Label.Align = Label.AlignMode.Left;
            button.OnPressed += _ => OnOptionPressed?.Invoke(index);
            OptionsBox.AddChild(button);
        }
    }
}
