using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._WF.PlanetCracker.Planets;

/// <summary>Asks before a hull enters the orbit of a world nobody is cleared to visit.</summary>
[GenerateTypedNameReferences]
public sealed partial class WFUnsanctionedOrbitConfirmWindow : FancyWindow
{
    /// <summary>The hop waiting for an answer. Cleared on every close, so an abort never sends it.</summary>
    private Action? _onConfirmed;

    public WFUnsanctionedOrbitConfirmWindow()
    {
        RobustXamlLoader.Load(this);

        ProceedButton.OnPressed += _ =>
        {
            var confirmed = _onConfirmed;
            Close();
            confirmed?.Invoke();
        };

        AbortButton.OnPressed += _ => Close();
        OnClose += () => _onConfirmed = null;
    }

    /// <summary>Opens the window for one orbit entry.</summary>
    public void Ask(string planet, Action onConfirmed)
    {
        _onConfirmed = onConfirmed;
        WarningLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("wf-orbit-unsanctioned-text",
            ("planet", FormattedMessage.EscapeText(planet)))));
        OpenCentered();
    }
}
