using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chat.Prototypes;
using Content.Shared.Speech;
using Content.Shared.Whitelist;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Chat.UI;

[GenerateTypedNameReferences]
public sealed partial class EmotesMenu : RadialMenu
{
    [Dependency] private EntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private ISharedPlayerManager _playerManager = default!;

    public event Action<ProtoId<EmotePrototype>>? OnPlayEmote;

    /// <summary>
    /// Whether the player may use an emote, by the same rule the server applies in
    /// ChatSystem.AllowedToUseEmote: a granted emote bypasses both lists, otherwise the lists decide and
    /// the emote must be generally available.
    /// </summary>
    private bool CanUseEmote(EntityUid player, EmotePrototype emote, EntityWhitelistSystem whitelist)
    {
        if (_entManager.TryGetComponent<SpeechComponent>(player, out var speech) &&
            speech.AllowedEmotes.Contains(emote.ID))
            return true;

        if (whitelist.IsWhitelistFail(emote.Whitelist, player) ||
            whitelist.IsBlacklistPass(emote.Blacklist, player))
            return false;

        return emote.Available;
    }

    public EmotesMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        var spriteSystem = _entManager.System<SpriteSystem>();
        var whitelistSystem = _entManager.System<EntityWhitelistSystem>();

        var main = FindControl<RadialContainer>("Main");

        var emotes = _prototypeManager.EnumeratePrototypes<EmotePrototype>();
        var player = _playerManager.LocalSession?.AttachedEntity;
        foreach (var emote in emotes)
        {
            // An emote with no trigger words cannot be spoken, so it has nothing to show.
            if (emote.Category == EmoteCategory.Invalid || emote.ChatTriggers.Count == 0)
                continue;

            // WOLFGATE: was testing the whitelist before AllowedEmotes, the opposite of the server. Every
            // emote a species is granted through its Speech component while the emote's own whitelist
            // rejects it - Synth and all fourteen Protogen chassis with Beep, Ping, Buzz, Chime, Honk,
            // Whirr - was typeable but never appeared here.
            if (player is not { Valid: true } playerUid || !CanUseEmote(playerUid, emote, whitelistSystem))
                continue;

            var parent = FindControl<RadialContainer>(emote.Category.ToString());

            var button = new EmoteMenuButton
            {
                SetSize = new Vector2(64f, 64f),
                ToolTip = Loc.GetString(emote.Name),
                ProtoId = emote.ID,
            };

            var tex = new TextureRect
            {
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Center,
                Texture = spriteSystem.Frame0(emote.Icon),
                TextureScale = new Vector2(2f, 2f),
            };

            button.AddChild(tex);
            parent.AddChild(button);
            foreach (var child in main.Children)
            {
                if (child is not RadialMenuTextureButton castChild)
                    continue;

                if (castChild.TargetLayer == emote.Category.ToString())
                {
                    castChild.Visible = true;
                    break;
                }
            }
        }


        // Set up menu actions
        foreach (var child in Children)
        {
            if (child is not RadialContainer container)
                continue;
            AddEmoteClickAction(container);
        }

        GeneralCategoryTexture.Texture = spriteSystem.Frame0(new SpriteSpecifier.Rsi(new ResPath("/Textures/Clothing/Head/Soft/mimesoft.rsi"), "icon"));
        HandsCategoryTexture.Texture = spriteSystem.Frame0(new SpriteSpecifier.Rsi(new ResPath("/Textures/Clothing/Hands/Gloves/latex.rsi"), "icon"));
    }

    private void AddEmoteClickAction(RadialContainer container)
    {
        foreach (var child in container.Children)
        {
            if (child is not EmoteMenuButton castChild)
                continue;

            castChild.OnButtonUp += _ =>
            {
                OnPlayEmote?.Invoke(castChild.ProtoId);
                Close();
            };
        }
    }
}


public sealed class EmoteMenuButton : RadialMenuTextureButtonWithSector
{
    public ProtoId<EmotePrototype> ProtoId { get; set; }
}
