using System.Linq;
using System.Numerics;
using Content.Client._WF.Encounters;
using Content.Client._WF.Stylesheets;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.CCVar;
using Content.Shared._WF.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._WF.Ghost;

/// <summary>
/// Categorised, searchable ghost warp menu in the style of TG's orbit menu. Replaces GhostTargetWindow.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GhostOrbitWindow : FancyWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IGameTiming _timing = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    private static readonly TimeSpan RefreshInterval = TimeSpan.FromSeconds(5);
    private static readonly SpriteSpecifier ShipIcon = new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/VerbIcons/anchor.svg.192dpi.png"));
    private static readonly SpriteSpecifier LocationIcon = new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/home.png"));

    /// <summary>Collapsed sections, kept for the whole client session.</summary>
    private static readonly HashSet<GhostOrbitCategory> Collapsed = new() { GhostOrbitCategory.Npc };

    private readonly List<Section> _sections = new();
    private List<GhostOrbitTarget> _targets = new();
    private List<GhostOrbitEncounterShip> _encounters = new();
    private string _search = string.Empty;
    private TimeSpan _nextRefresh;

    public event Action? OnGhostnadoClicked;

    public GhostOrbitWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        SearchBar.OnTextChanged += args =>
        {
            _search = args.Text.Trim().ToLowerInvariant();
            ApplyFilter();
            Scroll.SetScrollValue(Vector2.Zero);
        };
        SearchBar.OnTextEntered += _ => OrbitFirstMatch();
        MostFollowedButton.OnPressed += _ => OnGhostnadoClicked?.Invoke();
        RefreshButton.OnPressed += _ => RequestTargets();
    }

    /// <summary>
    /// Kept for the GhostGui and GhostUIController call sites; the window rebuilds itself when targets arrive.
    /// </summary>
    public void Populate()
    {
    }

    protected override void Opened()
    {
        base.Opened();

        var system = _entMan.System<GhostOrbitSystem>();
        system.TargetsReceived -= OnTargetsReceived;
        system.TargetsReceived += OnTargetsReceived;
        RequestTargets();
        SearchBar.GrabKeyboardFocus();
    }

    public override void Close()
    {
        base.Close();

        if (_entMan.EntitySysManager.TryGetEntitySystem<GhostOrbitSystem>(out var system))
            system.TargetsReceived -= OnTargetsReceived;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (IsOpen && AutoRefreshBox.Pressed && _timing.RealTime >= _nextRefresh)
            RequestTargets();
    }

    private void RequestTargets()
    {
        _nextRefresh = _timing.RealTime + RefreshInterval;
        _entMan.System<GhostOrbitSystem>().RequestTargets();
    }

    private void OnTargetsReceived(GhostOrbitTargetsEvent ev)
    {
        _entMan.System<Content.Client._WF.NpcCrew.WFCrewUiDiagnosticsSystem>().DisplayGhost(ev.Targets.Count, IsOpen);
        // Live refresh would otherwise rebuild every tile and drop the hovered tooltip for nothing.
        if (_targets.SequenceEqual(ev.Targets) && _encounters.SequenceEqual(ev.Encounters))
            return;

        _targets = ev.Targets;
        _encounters = ev.Encounters;
        Rebuild();
    }

    private void Rebuild()
    {
        Sections.RemoveAllChildren();
        _sections.Clear();

        var skin = WolfgateSkins.Get(_cfg.GetCVar(WolfgateCVars.UiStyle));
        var sprite = _entMan.System<SpriteSystem>();

        // Encounter ships sit in a section of their own among the rest, each in its side's colour.
        var colors = new Dictionary<NetEntity, Color>();
        var all = new List<GhostOrbitTarget>(_targets);
        foreach (var ship in _encounters
                     .OrderBy(s => s.Encounter, StringComparer.CurrentCultureIgnoreCase)
                     .ThenBy(s => s.Ship, StringComparer.CurrentCultureIgnoreCase))
        {
            colors[ship.Grid] = ship.Color ?? WFEncounterColors.Category(ship.Category);
            all.Add(new GhostOrbitTarget
            {
                Entity = ship.Grid,
                Name = ship.Ship,
                Category = GhostOrbitCategory.Encounter,
                Detail = Loc.GetString(ship.Hidden ? "wf-ghost-orbit-encounter-detail-hidden" : "wf-ghost-orbit-encounter-detail",
                    ("encounter", ship.Encounter), ("side", ship.Side)),
                Followers = ship.Followers,
            });
        }

        foreach (var group in all.GroupBy(t => t.Category).OrderBy(g => g.Key))
        {
            var accent = CategoryColor(group.Key, skin);
            var section = new Section(group.Key, accent, skin);
            section.Header.OnPressed += _ => ToggleSection(section);

            // Encounter ships keep the order they were given: by encounter, then by ship.
            var ordered = group.Key == GhostOrbitCategory.Encounter
                ? group.AsEnumerable()
                : group.OrderBy(t => t.Name, StringComparer.CurrentCultureIgnoreCase);
            foreach (var target in ordered)
            {
                var color = group.Key == GhostOrbitCategory.Encounter && colors.TryGetValue(target.Entity, out var side) ? side : accent;
                var tile = new GhostOrbitTile(target, GetIcon(target, sprite), color, skin);
                tile.OnPressed += _ => Orbit(target.Entity);
                section.Tiles.Add(tile);
                section.Body.AddChild(tile);
            }

            _sections.Add(section);
            Sections.AddChild(section.Root);
        }

        UpdateSummary();
        ApplyFilter();
    }

    private void ApplyFilter()
    {
        var searching = _search.Length > 0;
        foreach (var section in _sections)
        {
            var matches = 0;
            foreach (var tile in section.Tiles)
            {
                tile.Visible = !searching || tile.SearchText.Contains(_search);
                if (tile.Visible)
                    matches++;
            }

            // A search looks through collapsed sections too.
            var expanded = searching || !Collapsed.Contains(section.Category);
            section.Root.Visible = !searching || matches > 0;
            section.Body.Visible = expanded;
            section.SetHeader(expanded, searching ? $"{matches}/{section.Tiles.Count}" : $"{section.Tiles.Count}");
        }
    }

    private void ToggleSection(Section section)
    {
        if (_search.Length > 0)
            return;

        if (!Collapsed.Remove(section.Category))
            Collapsed.Add(section.Category);

        ApplyFilter();
    }

    private void OrbitFirstMatch()
    {
        foreach (var section in _sections)
        {
            if (!section.Root.Visible || !section.Body.Visible)
                continue;

            if (section.Tiles.FirstOrDefault(t => t.Visible) is { } tile)
            {
                Orbit(tile.Target.Entity);
                return;
            }
        }
    }

    private void Orbit(NetEntity target)
    {
        _entMan.System<GhostOrbitSystem>().Orbit(target);
    }

    private void UpdateSummary()
    {
        int Count(GhostOrbitCategory category) => _targets.Count(t => t.Category == category);

        SummaryLabel.Text = Loc.GetString("wf-ghost-orbit-summary",
            ("players", Count(GhostOrbitCategory.Alive) + Count(GhostOrbitCategory.Critical) + Count(GhostOrbitCategory.Antagonist)),
            ("ssd", Count(GhostOrbitCategory.Disconnected)),
            ("dead", Count(GhostOrbitCategory.Dead)),
            ("ghosts", Count(GhostOrbitCategory.Ghost)),
            ("npcs", Count(GhostOrbitCategory.Npc)));
    }

    /// <summary>
    /// Job icon for crew, the prototype's icon for everything else, a stock glyph for warp points.
    /// </summary>
    private Texture? GetIcon(GhostOrbitTarget target, SpriteSystem sprite)
    {
        if (target.JobIcon is { } job && _proto.TryIndex(job, out var jobIcon))
            return sprite.Frame0(jobIcon.Icon);

        if (target.Prototype is { } proto && _proto.HasIndex<EntityPrototype>(proto))
            return sprite.GetPrototypeIcon(proto).Default;

        return target.Category switch
        {
            GhostOrbitCategory.Ship or GhostOrbitCategory.Encounter => sprite.Frame0(ShipIcon),
            GhostOrbitCategory.Location => sprite.Frame0(LocationIcon),
            _ => null,
        };
    }

    private static Color CategoryColor(GhostOrbitCategory category, WolfgateSkin skin)
    {
        return category switch
        {
            GhostOrbitCategory.Interest => skin.Accent,
            GhostOrbitCategory.Antagonist => skin.Danger,
            GhostOrbitCategory.Critical => Color.FromHex("#FF8A3D"),
            GhostOrbitCategory.Alive => skin.Good,
            GhostOrbitCategory.Disconnected => Color.FromHex("#A98BFF"),
            GhostOrbitCategory.Dead => skin.TextMuted,
            GhostOrbitCategory.Ghost => Color.FromHex("#BFD3FF"),
            GhostOrbitCategory.Location => skin.Caution,
            GhostOrbitCategory.Ship => Color.FromHex("#5FA8FF"),
            GhostOrbitCategory.Encounter => Color.FromHex("#FFAE3D"),
            GhostOrbitCategory.Npc => Color.FromHex("#C8B27A"),
            _ => skin.Text,
        };
    }

    /// <summary>
    /// A collapsible header over a wrapping grid of tiles.
    /// </summary>
    private sealed class Section
    {
        public readonly GhostOrbitCategory Category;
        public readonly BoxContainer Root;
        public readonly ContainerButton Header;
        public readonly WrapContainer Body;
        public readonly List<GhostOrbitTile> Tiles = new();

        private readonly Label _title;
        private readonly Label _count;
        private readonly string _name;

        public Section(GhostOrbitCategory category, Color accent, WolfgateSkin skin)
        {
            Category = category;
            _name = Loc.GetString($"wf-ghost-orbit-category-{category.ToString().ToLowerInvariant()}");

            Root = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 4 };

            Header = new ContainerButton { MinHeight = 26 };
            Header.AddStyleClass(ContainerButton.StyleClassButton);
            Root.AddChild(Header);

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8 };
            Header.AddChild(row);

            row.AddChild(new PanelContainer { SetWidth = 4, PanelOverride = new StyleBoxFlat(accent) });
            _title = new Label
            {
                StyleClasses = { StyleNano.StyleClassLabelHeading },
                FontColorOverride = accent,
                VerticalAlignment = VAlignment.Center,
            };
            row.AddChild(_title);
            _count = new Label
            {
                FontColorOverride = skin.TextMuted,
                VerticalAlignment = VAlignment.Center,
                HorizontalExpand = true,
            };
            row.AddChild(_count);

            Body = new WrapContainer
            {
                SeparationOverride = 4,
                CrossSeparationOverride = 4,
                Margin = new Thickness(8, 0, 0, 6),
            };
            Root.AddChild(Body);
        }

        public void SetHeader(bool expanded, string count)
        {
            _title.Text = $"{(expanded ? "▼" : "▶")} {_name}";
            _count.Text = count;
        }
    }
}
