using System.Linq;
using System.Numerics;
using Content.Shared._WF.Administration;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Roles;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._WF.Administration.UI.SpawnOutfit;

/// <summary>
/// Picks a starting gear outfit, grouped by department, to spawn a humanoid with at the target entity.
/// In ghost mode the target is a ghost whose player gets spawned as their own character and put in control.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SpawnOutfitMenu : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IClientConsoleHost _consoleHost = default!;
    [Dependency] private IEntitySystemManager _entitySystem = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    /// <summary>
    /// Gear IDs containing one of these belong to no job and get filed under Antagonists.
    /// </summary>
    private static readonly string[] AntagKeywords =
    {
        "Syndicate", "Nukie", "Nuclear", "Pirate", "Wizard", "Ninja", "Traitor", "Cult", "Zombie", "Heretic", "Thief", "Changeling",
    };

    private static readonly SpawnOutfitBody[] Bodies = { SpawnOutfitBody.Random, SpawnOutfitBody.Default, SpawnOutfitBody.Own };

    private readonly NetEntity _target;
    private readonly bool _forGhost;
    private readonly SpriteSystem _sprites;
    private readonly List<OutfitEntry> _entries = new();
    private readonly List<OutfitCategory> _categories = new();
    private readonly ButtonGroup _rowGroup = new();
    private OutfitEntry? _selected;
    private OutfitCategory? _categoryFilter;

    public SpawnOutfitMenu(NetEntity target, bool forGhost = false)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _target = target;
        _forGhost = forGhost;
        _sprites = _entitySystem.GetEntitySystem<SpriteSystem>();

        BuildEntries();
        PopulateCategories();
        PopulateBodies();
        if (forGhost)
            SetupGhostMode();

        SearchBar.OnTextChanged += _ => PopulateOutfits();
        CategoryFilter.OnItemSelected += OnCategorySelected;
        BodySelect.OnItemSelected += args => BodySelect.SelectId(args.Id);
        ConfirmButton.OnPressed += _ => Confirm();

        PopulateOutfits();
        UpdateDetails();
    }

    /// <summary>
    /// Body and control are fixed in ghost mode: the ghost's player, as their own character.
    /// </summary>
    private void SetupGhostMode()
    {
        var name = _entityManager.TryGetEntity(_target, out var ghost)
            ? _entityManager.GetComponent<MetaDataComponent>(ghost.Value).EntityName
            : _target.ToString();

        Title = Loc.GetString("wf-spawn-outfit-ghost-title");
        GhostInfo.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("wf-spawn-outfit-ghost-info", ("name", FormattedMessage.EscapeText(name)))));
        GhostInfo.Visible = true;
        BodySelect.Visible = false;
        ControlCheck.Visible = false;
        ConfirmButton.Text = Loc.GetString("wf-spawn-outfit-ghost-confirm", ("name", name));
    }

    /// <summary>
    /// One selectable outfit: the gear plus the job it belongs to, if any.
    /// </summary>
    private sealed record OutfitEntry(StartingGearPrototype Gear, JobPrototype? Job, OutfitCategory Category)
    {
        public string Name => Job?.LocalizedName ?? Gear.ID;
    }

    /// <summary>
    /// A list section: a department, or a synthetic bucket like Antagonists or Other.
    /// </summary>
    private sealed record OutfitCategory(string Id, string Name, Color Color, int Order);

    /// <summary>
    /// Pairs every non-loadout gear with its job and department. Job-less gear lands in Antagonists or Other.
    /// </summary>
    private void BuildEntries()
    {
        _entries.Clear();
        _categories.Clear();

        var loadoutGears = _prototypeManager.EnumeratePrototypes<LoadoutPrototype>()
            .Select(loadout => loadout.StartingGear.ToString())
            .ToHashSet();
        var gears = _prototypeManager.EnumeratePrototypes<StartingGearPrototype>()
            .Where(gear => !gear.Abstract && !loadoutGears.Contains(gear.ID))
            .ToDictionary(gear => gear.ID);

        // First department to claim a job's gear owns it; primary departments get first pick.
        var departments = _prototypeManager.EnumeratePrototypes<DepartmentPrototype>().ToArray();
        Array.Sort(departments, DepartmentUIComparer.Instance);
        var order = 0;
        var claimed = new Dictionary<string, (JobPrototype Job, OutfitCategory Category)>();
        foreach (var department in departments.Where(d => d.Primary).Concat(departments.Where(d => !d.Primary)))
        {
            OutfitCategory? category = null;
            foreach (var jobId in department.Roles)
            {
                if (!_prototypeManager.TryIndex(jobId, out var job)
                    || job.StartingGear is not { } gearId
                    || !gears.ContainsKey(gearId.Id)
                    || claimed.ContainsKey(gearId.Id))
                    continue;

                category ??= new OutfitCategory(department.ID, Loc.GetString(department.Name), department.Color, order++);
                claimed[gearId.Id] = (job, category);
            }

            if (category != null)
                _categories.Add(category);
        }

        var antagonists = new OutfitCategory("Antagonists", Loc.GetString("wf-spawn-outfit-category-antagonists"), Color.FromHex("#C83737"), order++);
        var other = new OutfitCategory("Other", Loc.GetString("wf-spawn-outfit-category-other"), Color.FromHex("#7A7A7A"), order++);

        foreach (var gear in gears.Values)
        {
            if (claimed.TryGetValue(gear.ID, out var owner))
                _entries.Add(new OutfitEntry(gear, owner.Job, owner.Category));
            else
                _entries.Add(new OutfitEntry(gear, null, IsAntagGear(gear.ID) ? antagonists : other));
        }

        if (_entries.Any(entry => entry.Category == antagonists))
            _categories.Add(antagonists);
        if (_entries.Any(entry => entry.Category == other))
            _categories.Add(other);

        _entries.Sort((a, b) =>
        {
            var byCategory = a.Category.Order.CompareTo(b.Category.Order);
            return byCategory != 0 ? byCategory : string.Compare(a.Name, b.Name, StringComparison.CurrentCultureIgnoreCase);
        });
    }

    private static bool IsAntagGear(string gearId)
    {
        return AntagKeywords.Any(keyword => gearId.Contains(keyword, StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Fills the category filter with "All" plus every used category. Id 0 is all, id n is _categories[n - 1].
    /// </summary>
    private void PopulateCategories()
    {
        CategoryFilter.Clear();
        CategoryFilter.AddItem(Loc.GetString("wf-spawn-outfit-category-all"), 0);
        for (var i = 0; i < _categories.Count; i++)
        {
            CategoryFilter.AddItem(_categories[i].Name, i + 1);
        }
    }

    private void PopulateBodies()
    {
        BodySelect.Clear();
        for (var i = 0; i < Bodies.Length; i++)
        {
            BodySelect.AddItem(Loc.GetString($"wf-spawn-outfit-body-{Bodies[i]}"), i);
        }

        BodySelect.SelectId(Array.IndexOf(Bodies, SpawnOutfitBody.Own));
    }

    private void OnCategorySelected(OptionButton.ItemSelectedEventArgs args)
    {
        CategoryFilter.SelectId(args.Id);
        _categoryFilter = args.Id == 0 ? null : _categories[args.Id - 1];
        PopulateOutfits();
    }

    /// <summary>
    /// Rebuilds the section headers and rows using the current search text and category filter.
    /// </summary>
    private void PopulateOutfits()
    {
        Outfits.RemoveAllChildren();

        var search = SearchBar.Text.Trim().ToLowerInvariant();
        var shown = 0;
        OutfitCategory? currentCategory = null;

        foreach (var entry in _entries)
        {
            if (_categoryFilter != null && entry.Category != _categoryFilter)
                continue;
            if (search.Length > 0 && !Matches(entry, search))
                continue;

            if (entry.Category != currentCategory)
            {
                currentCategory = entry.Category;
                Outfits.AddChild(MakeHeader(entry.Category));
            }

            Outfits.AddChild(MakeRow(entry));
            shown++;
        }

        CountLabel.Text = Loc.GetString("wf-spawn-outfit-count", ("shown", shown), ("total", _entries.Count));
    }

    private static bool Matches(OutfitEntry entry, string search)
    {
        return entry.Name.ToLowerInvariant().Contains(search)
               || entry.Gear.ID.ToLowerInvariant().Contains(search);
    }

    private static Control MakeHeader(OutfitCategory category)
    {
        return new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat { BackgroundColor = category.Color.WithAlpha(0.35f) },
            Children =
            {
                new Label
                {
                    Text = category.Name,
                    StyleClasses = { "LabelKeyText" },
                    Margin = new Thickness(6, 2),
                },
            },
        };
    }

    /// <summary>
    /// A toggle row: department colour bar, job icon, name and gear ID. Rows share one group so only one is pressed.
    /// </summary>
    private Control MakeRow(OutfitEntry entry)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            Margin = new Thickness(4, 2),
        };

        row.AddChild(new PanelContainer
        {
            MinWidth = 4,
            VerticalExpand = true,
            Margin = new Thickness(0, 0, 6, 0),
            PanelOverride = new StyleBoxFlat { BackgroundColor = entry.Category.Color },
        });

        if (entry.Job != null && _prototypeManager.TryIndex(entry.Job.Icon, out var jobIcon))
        {
            row.AddChild(new TextureRect
            {
                Texture = _sprites.Frame0(jobIcon.Icon),
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(0, 0, 6, 0),
            });
        }

        var labels = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };
        labels.AddChild(new Label { Text = entry.Name });
        if (entry.Job != null)
            labels.AddChild(new Label { Text = entry.Gear.ID, StyleClasses = { "LabelSubText" } });
        row.AddChild(labels);

        var button = new ContainerButton
        {
            ToggleMode = true,
            Group = _rowGroup,
            Pressed = entry == _selected,
            HorizontalExpand = true,
            StyleClasses = { ContainerButton.StyleClassButton, "ButtonSquare" },
        };
        button.AddChild(row);
        button.OnPressed += _ => Select(entry);
        return button;
    }

    private void Select(OutfitEntry entry)
    {
        _selected = entry;
        UpdateDetails();
    }

    /// <summary>
    /// Shows the selected outfit's job, description and every item it equips.
    /// </summary>
    private void UpdateDetails()
    {
        Contents.RemoveAllChildren();
        ConfirmButton.Disabled = _selected == null;

        if (_selected == null)
        {
            SelectedName.Text = Loc.GetString("wf-spawn-outfit-none-selected");
            SelectedId.Text = string.Empty;
            SelectedCategory.Text = string.Empty;
            SelectedDescription.Visible = false;
            return;
        }

        SelectedName.Text = _selected.Name;
        SelectedId.Text = _selected.Gear.ID;
        SelectedCategory.Text = _selected.Category.Name;

        var description = _selected.Job?.LocalizedDescription ?? string.Empty;
        SelectedDescription.Text = description;
        SelectedDescription.Visible = description.Length > 0;

        foreach (var (slot, proto) in _selected.Gear.Equipment.OrderBy(pair => pair.Key))
        {
            Contents.AddChild(ContentLine(slot, proto));
        }

        foreach (var proto in _selected.Gear.Inhand)
        {
            Contents.AddChild(ContentLine(Loc.GetString("wf-spawn-outfit-in-hand"), proto));
        }

        foreach (var (slot, protos) in _selected.Gear.Storage)
        {
            foreach (var proto in protos)
            {
                Contents.AddChild(ContentLine(Loc.GetString("wf-spawn-outfit-storage", ("slot", slot)), proto));
            }
        }
    }

    private Label ContentLine(string slot, EntProtoId proto)
    {
        var name = _prototypeManager.TryIndex(proto, out var entity) ? entity.Name : proto.Id;
        return new Label { Text = $"{slot}: {name}", StyleClasses = { "LabelSubText" } };
    }

    private void Confirm()
    {
        if (_selected == null)
            return;

        if (_forGhost)
        {
            _consoleHost.ExecuteCommand($"{WolfgateAdminCommands.SpawnOutfitGhost} {_target} \"{_selected.Gear.ID}\"");
            Close();
            return;
        }

        var body = Bodies[BodySelect.SelectedId];
        _consoleHost.ExecuteCommand($"{WolfgateAdminCommands.SpawnOutfit} {_target} \"{_selected.Gear.ID}\" {ControlCheck.Pressed} {body}");
        Close();
    }
}
