using Content.Shared._WF.Shuttles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._WF.Shuttles.UI;

/// <summary>
/// The collision warning strip across the top of the shuttle console. Blank until the ship's grid
/// carries a <see cref="CollisionWarningComponent"/>, then flashes with the countdown to contact.
/// The control itself stays visible because the engine does not tick hidden controls; only its
/// contents are shown and hidden.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CollisionWarningBanner : PanelContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IGameTiming _timing = default!;

    /// <summary>The warning is a component on the grid rather than console state, so it is polled.</summary>
    private const float PollInterval = 0.2f;

    /// <summary>Flashes per second while a warning is up.</summary>
    private const float FlashRate = 2f;

    private static readonly Color AdvisoryColor = Color.FromHex("#ffa020");
    private static readonly Color ImminentColor = Color.FromHex("#ff4040");

    /// <summary>The strip stays up in this colour whenever the warning is switched off.</summary>
    private static readonly Color DisabledColor = Color.FromHex("#8a8a8a");

    private readonly StyleBoxFlat _background = new();

    private EntityUid? _grid;
    private CollisionWarningLevel _level;
    private TimeSpan _impactTime;
    private string? _threatName;
    private float _bearing;
    private float _closingSpeed;
    private bool _disabled;
    private float _pollAccumulator;
    private float _flashAccumulator;

    public CollisionWarningBanner()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PanelOverride = _background;
        Refresh(null);
    }

    /// <summary>
    /// Points the banner at a ship, or nothing.
    /// </summary>
    public void SetShuttle(EntityUid? grid)
    {
        _grid = grid;
        Poll();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _pollAccumulator += args.DeltaSeconds;

        if (_pollAccumulator >= PollInterval)
            Poll();

        if (!ContentBox.Visible || _disabled)
            return;

        // Advisories hold steady; only the imminent stage flashes.
        if (_level == CollisionWarningLevel.Imminent)
        {
            _flashAccumulator += args.DeltaSeconds * FlashRate;
            Modulate = Color.White.WithAlpha(MathF.Abs(MathF.Sin(_flashAccumulator * MathF.PI)) * 0.55f + 0.45f);
        }
        else
        {
            Modulate = Color.White;
        }

        UpdateCountdown();
    }

    private void Poll()
    {
        _pollAccumulator = 0f;

        // Off is a state worth showing: a blank strip would look the same as a clear scope.
        if (_entManager.HasComponent<CollisionWarningDisabledComponent>(_grid))
        {
            ShowDisabled();
            return;
        }

        Refresh(_entManager.TryGetComponent<CollisionWarningComponent>(_grid, out var warning) ? warning : null);
    }

    private void ShowDisabled()
    {
        ContentBox.Visible = true;
        Modulate = Color.White;
        _level = CollisionWarningLevel.Advisory;
        _disabled = true;
        _flashAccumulator = 0f;

        _background.BorderThickness = new Thickness(2);
        _background.BorderColor = DisabledColor;
        _background.BackgroundColor = DisabledColor.WithAlpha(0.12f);

        WarningLabel.Text = Loc.GetString("collision-warning-disabled");
        WarningLabel.FontColorOverride = DisabledColor;
        DetailLabel.Text = string.Empty;
    }

    private void Refresh(CollisionWarningComponent? warning)
    {
        _disabled = false;

        if (warning == null)
        {
            ContentBox.Visible = false;
            Modulate = Color.White;
            _background.BackgroundColor = Color.Transparent;
            _background.BorderThickness = new Thickness(0);
            _flashAccumulator = 0f;
            return;
        }

        if (!ContentBox.Visible)
            _flashAccumulator = 0f;

        ContentBox.Visible = true;
        _level = warning.Level;

        var imminent = warning.Level == CollisionWarningLevel.Imminent;
        var color = imminent ? ImminentColor : AdvisoryColor;

        _background.BorderThickness = new Thickness(2);
        _background.BorderColor = color;
        _background.BackgroundColor = color.WithAlpha(0.18f);

        WarningLabel.Text = Loc.GetString(imminent ? "collision-warning-imminent" : "collision-warning-advisory");
        WarningLabel.FontColorOverride = color;
        DetailLabel.FontColorOverride = color;

        _impactTime = warning.ImpactTime;
        _threatName = warning.ThreatName;
        _bearing = warning.Bearing;
        _closingSpeed = warning.ClosingSpeed;

        UpdateCountdown();
    }

    /// <summary>
    /// Counts down locally between polls so the readout runs smoothly.
    /// </summary>
    private void UpdateCountdown()
    {
        var seconds = MathF.Max((float) (_impactTime - _timing.CurTime).TotalSeconds, 0f);

        DetailLabel.Text = Loc.GetString("collision-warning-detail",
            ("threat", _threatName ?? Loc.GetString("collision-warning-unknown-threat")),
            ("bearing", MathF.Round(_bearing).ToString("000")),
            ("seconds", seconds.ToString("0.0")),
            ("speed", MathF.Round(_closingSpeed).ToString()));
    }
}
