using System.Linq;
using Content.Shared._WF.Shuttles;
using Content.Shared.Pinpointer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map.Components;
using Robust.Shared.Timing;

namespace Content.Client._WF.Shuttles.UI;

/// <summary>
/// Console screen showing the whole hull at once, so damage is visible without flying around.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ShipScreen : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;

    /// <summary>
    /// Counting tiles walks every chunk, so it's not worth doing per frame.
    /// </summary>
    private const float StatsInterval = 2f;

    private readonly SharedMapSystem _maps;

    private EntityUid? _shuttle;
    private float _statsAccumulator = StatsInterval;

    public ShipScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _maps = _entManager.System<SharedMapSystem>();

        // A LayoutContainer parks loose children in its top left corner otherwise.
        LayoutContainer.SetAnchorPreset(NoDataLabel, LayoutContainer.LayoutPreset.Center);

        FitButton.OnPressed += _ => ShipView.FitToShip();

        AlarmPanel.CodeRequested += code => CodeRequested?.Invoke(code);
        AlarmPanel.GeneralQuartersRequested += active => GeneralQuartersRequested?.Invoke(active);
        AlarmPanel.AnnounceRequested += text => AnnounceRequested?.Invoke(text);
        AlarmPanel.SoundRequested += url => SoundRequested?.Invoke(url);
        AlarmPanel.SoundStopRequested += () => SoundStopRequested?.Invoke();
        AlarmPanel.CollisionAlertRequested += enabled => CollisionAlertRequested?.Invoke(enabled);

        DamageToggle.OnToggled += args => SetOverlay(() => ShipView.ShowDamage = args.Pressed);
        FireToggle.OnToggled += args => SetOverlay(() => ShipView.ShowFire = args.Pressed);
        PressureToggle.OnToggled += args => SetOverlay(() => ShipView.ShowPressure = args.Pressed);
        PowerToggle.OnToggled += args => SetOverlay(() => ShipView.ShowPower = args.Pressed);

        DamageToggle.Pressed = ShipView.ShowDamage;
        FireToggle.Pressed = ShipView.ShowFire;
        PressureToggle.Pressed = ShipView.ShowPressure;
        PowerToggle.Pressed = ShipView.ShowPower;
    }

    /// <summary>
    /// Raised when the drawn overlays change, so the console can tell the server what to bother sending.
    /// </summary>
    public event Action? OverlaysChanged;

    /// <summary>
    /// The pilot picked a situation code on the PA panel.
    /// </summary>
    public event Action<string>? CodeRequested;

    /// <summary>
    /// The pilot sounded or secured general quarters.
    /// </summary>
    public event Action<bool>? GeneralQuartersRequested;

    /// <summary>
    /// The pilot wants a line read out over the PA.
    /// </summary>
    public event Action<string>? AnnounceRequested;
    public event Action<string>? SoundRequested;
    public event Action? SoundStopRequested;

    /// <summary>
    /// The pilot switched the collision warning on or off.
    /// </summary>
    public event Action<bool>? CollisionAlertRequested;

    public ShipOverlays Overlays => ShipView.Overlays;

    private void SetOverlay(Action apply)
    {
        apply();
        OverlaysChanged?.Invoke();
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttle = shuttle;
        ShipView.SetGrid(shuttle);
        AlarmPanel.SetGrid(shuttle);
        _statsAccumulator = StatsInterval;
    }

    public void SetConsole(EntityUid? console)
    {
        ShipView.SetConsole(console);
    }

    /// <summary>
    /// Applies a telemetry sweep from the server.
    /// </summary>
    public void UpdateStatus(ShipStatusMessage message)
    {
        ShipView.SetStatus(message.Tiles);

        var summary = message.Summary;

        IntegrityLabel.Text = Loc.GetString("shuttle-console-ship-percent",
            ("value", $"{summary.WorstIntegrity * 100f:0}"));
        DamagedLabel.Text = summary.DamagedTiles.ToString();
        FiresLabel.Text = summary.FireTiles.ToString();
        VentedLabel.Text = summary.VentedTiles.ToString();
        UnpoweredLabel.Text = summary.UnpoweredTiles.ToString();
        TruncatedLabel.Visible = summary.Truncated;
    }

    /// <summary>
    /// Drops stale telemetry when the view leaves the screen, so reopening it doesn't flash old readings.
    /// </summary>
    public void ClearStatus()
    {
        ShipView.ClearStatus();

        IntegrityLabel.Text = "-";
        DamagedLabel.Text = "-";
        FiresLabel.Text = "-";
        VentedLabel.Text = "-";
        UnpoweredLabel.Text = "-";
        TruncatedLabel.Visible = false;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _statsAccumulator += args.DeltaSeconds;

        if (_statsAccumulator < StatsInterval)
            return;

        _statsAccumulator = 0f;
        UpdateStats();
    }

    private void UpdateStats()
    {
        if (!_entManager.TryGetComponent<MapGridComponent>(_shuttle, out var grid))
        {
            ShipNameLabel.Text = Loc.GetString("shuttle-console-ship-name-unknown");
            ShipTilesLabel.Text = "-";
            NoDataLabel.Visible = true;
            return;
        }

        // The hull only draws if the grid carries nav map data, which the server attaches to any grid
        // with a shuttle console.
        NoDataLabel.Visible = !_entManager.HasComponent<NavMapComponent>(_shuttle);

        ShipNameLabel.Text = _entManager.GetComponent<MetaDataComponent>(_shuttle!.Value).EntityName;
        ShipTilesLabel.Text = _maps.GetAllTiles(_shuttle.Value, grid).Count().ToString();
    }
}
