using System.Linq;
using Content.Shared._WF.ShipPa;
using Content.Shared._WF.Shuttles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._WF.Shuttles.UI;

/// <summary>
/// Console panel for the ship's PA: the situation code, the general quarters alarm and free-text announcements.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ShipAlarmPanel : BoxContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPrototypeManager _protoManager = default!;

    /// <summary>
    /// The alert state changes rarely, so it's polled instead of being pushed at the console.
    /// </summary>
    private const float PollInterval = 0.25f;

    private static readonly Color ReadoutColor = Color.FromHex("#00ff2a");
    private static readonly Color OfflineColor = Color.FromHex("#ff4040");
    private static readonly Color AlarmColor = Color.FromHex("#ff8080");

    private readonly Dictionary<string, Button> _codeButtons = new();

    private EntityUid? _grid;
    private bool _generalQuarters;
    private bool _collisionAlertOff;
    private float _pollAccumulator;

    public ShipAlarmPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        BuildCodeButtons();

        GeneralQuartersButton.OnPressed += _ => GeneralQuartersRequested?.Invoke(!_generalQuarters);
        CollisionAlertButton.OnPressed += _ => CollisionAlertRequested?.Invoke(_collisionAlertOff);
        AnnounceButton.OnPressed += _ => Announce();
        AnnounceEdit.OnTextEntered += _ => Announce();
        AnnounceEdit.OnTextChanged += args => AnnounceButton.Disabled = string.IsNullOrWhiteSpace(args.Text);
        AnnounceButton.Disabled = true;

        SoundButton.OnPressed += _ => QueueSound();
        SoundEdit.OnTextEntered += _ => QueueSound();
        SoundEdit.OnTextChanged += args => SoundButton.Disabled = string.IsNullOrWhiteSpace(args.Text);
        SoundButton.Disabled = true;
        SoundStopButton.OnPressed += _ => SoundStopRequested?.Invoke();

        Refresh(null);
    }

    /// <summary>
    /// The pilot picked a situation code.
    /// </summary>
    public event Action<string>? CodeRequested;

    /// <summary>
    /// The pilot sounded or secured general quarters.
    /// </summary>
    public event Action<bool>? GeneralQuartersRequested;

    /// <summary>
    /// The pilot wants a line read out over the PA.
    /// </summary>
    public event Action<string>? AnnounceRequested;

    /// <summary>
    /// Pilot pasted a link to play over the ship's speakers.
    /// </summary>
    public event Action<string>? SoundRequested;

    /// <summary>
    /// Pilot cut whatever the ship is playing.
    /// </summary>
    public event Action? SoundStopRequested;

    /// <summary>
    /// The pilot switched the collision warning on or off.
    /// </summary>
    public event Action<bool>? CollisionAlertRequested;

    /// <summary>
    /// Points the panel at a ship, or nothing.
    /// </summary>
    public void SetGrid(EntityUid? grid)
    {
        _grid = grid;
        Poll();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _pollAccumulator += args.DeltaSeconds;

        if (_pollAccumulator < PollInterval)
            return;

        Poll();
    }

    /// <summary>
    /// One button per selectable situation code. Codes are prototypes, so this only runs once.
    /// </summary>
    private void BuildCodeButtons()
    {
        var protos = _protoManager.EnumeratePrototypes<ShipAlertCodePrototype>()
            .Where(proto => proto.Selectable)
            .OrderBy(proto => proto.Order)
            .ThenBy(proto => proto.ID);

        foreach (var proto in protos)
        {
            var button = new Button
            {
                Text = Loc.GetString(proto.Name),
                HorizontalExpand = true,
                MinHeight = 32,
            };

            button.AddStyleClass("ButtonSquare");
            button.Label.FontColorOverride = proto.Color;

            if (proto.Description != null)
                button.ToolTip = Loc.GetString(proto.Description.Value);

            var id = proto.ID;
            button.OnPressed += _ => CodeRequested?.Invoke(id);

            CodeContainer.AddChild(button);
            _codeButtons[id] = button;
        }
    }

    private void Poll()
    {
        _pollAccumulator = 0f;
        Refresh(_entManager.TryGetComponent<ShipAlertComponent>(_grid, out var alert) ? alert : null);
    }

    /// <summary>
    /// Redraws everything the server owns. A null alert means the ship has no PA at all.
    /// </summary>
    private void Refresh(ShipAlertComponent? alert)
    {
        var code = alert?.Code;

        if (_protoManager.TryIndex(code, out var proto))
        {
            ConditionLabel.Text = Loc.GetString(proto.Name);
            ConditionLabel.FontColorOverride = proto.Color;
        }
        else
        {
            ConditionLabel.Text = "-";
            ConditionLabel.FontColorOverride = ReadoutColor;
        }

        foreach (var (id, button) in _codeButtons)
        {
            button.Disabled = code != null && code.Value.Id == id;
        }

        // The collision warning is a grid component rather than console state, so it rides the same poll.
        _collisionAlertOff = _entManager.HasComponent<CollisionWarningDisabledComponent>(_grid);
        CollisionAlertButton.Text = Loc.GetString(_collisionAlertOff
            ? "shuttle-console-ship-collision-alert-off"
            : "shuttle-console-ship-collision-alert-on");
        CollisionAlertButton.Modulate = _collisionAlertOff ? OfflineColor : Color.White;

        _generalQuarters = alert?.GeneralQuarters ?? false;
        GeneralQuartersButton.Text = Loc.GetString(_generalQuarters
            ? "shuttle-console-ship-general-quarters-secure"
            : "shuttle-console-ship-general-quarters-sound");
        GeneralQuartersButton.Modulate = _generalQuarters ? AlarmColor : Color.White;

        SpeakersCaption.Text = Loc.GetString(alert is { SpeakersFallback: true }
            ? "shuttle-console-ship-speakers-fallback"
            : "shuttle-console-ship-speakers");

        if (alert == null)
        {
            SpeakersLabel.Text = "-";
            SpeakersLabel.FontColorOverride = ReadoutColor;
            return;
        }

        if (alert.SpeakersOnline == 0)
        {
            SpeakersLabel.Text = Loc.GetString("shuttle-console-ship-speakers-none");
            SpeakersLabel.FontColorOverride = OfflineColor;
            return;
        }

        SpeakersLabel.Text = Loc.GetString("shuttle-console-ship-speakers-count",
            ("online", alert.SpeakersOnline),
            ("total", alert.SpeakersTotal));
        SpeakersLabel.FontColorOverride = ReadoutColor;
    }

    private void QueueSound()
    {
        var url = SoundEdit.Text.Trim();

        if (string.IsNullOrWhiteSpace(url))
            return;

        SoundRequested?.Invoke(url);

        SoundEdit.Clear();
        SoundButton.Disabled = true;
    }

    private void Announce()
    {
        var text = AnnounceEdit.Text.Trim();

        if (string.IsNullOrEmpty(text))
            return;

        AnnounceRequested?.Invoke(text);

        AnnounceEdit.Clear();
        AnnounceButton.Disabled = true;
    }
}
