using Content.Shared._WF.Shuttles;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._WF.Shuttles.UI;

/// <summary>
/// Strip of hull camera controls: which side of the ship to look from, and how far out.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ShuttleCameraBar : PanelContainer
{
    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IPlayerManager _player = default!;

    private readonly (Button Button, ShuttleCameraView View)[] _views;

    private ShuttleCameraView _view = ShuttleCameraView.Helm;
    private float _zoom = 1.5f;
    private bool _lowLight;

    /// <summary>
    /// Set while the bar is writing to its own controls, so that doesn't echo back as a request.
    /// </summary>
    private bool _syncing;

    /// <summary>
    /// The pilot picked a view, zoom or low-light setting.
    /// </summary>
    public event Action<ShuttleCameraView, float, bool>? CameraRequested;

    public ShuttleCameraBar()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _views = new[]
        {
            (HelmButton, ShuttleCameraView.Helm),
            (FrontButton, ShuttleCameraView.Front),
            (RearButton, ShuttleCameraView.Rear),
            (LeftButton, ShuttleCameraView.Left),
            (RightButton, ShuttleCameraView.Right),
        };

        var group = new ButtonGroup();

        foreach (var (button, view) in _views)
        {
            button.Group = group;
            button.OnPressed += _ => Request(view, _zoom, _lowLight);
        }

        ZoomSlider.MinValue = ShuttleCameraComponent.MinZoom;
        ZoomSlider.MaxValue = ShuttleCameraComponent.MaxZoom;

        ZoomSlider.OnValueChanged += _ =>
        {
            if (!_syncing)
                Request(_view, ZoomSlider.Value, _lowLight);
        };

        ZoomInButton.OnPressed += _ => Request(_view, _zoom - ShuttleCameraComponent.ZoomStep, _lowLight);
        ZoomOutButton.OnPressed += _ => Request(_view, _zoom + ShuttleCameraComponent.ZoomStep, _lowLight);

        LowLightButton.OnToggled += args =>
        {
            if (!_syncing)
                Request(_view, _zoom, args.Pressed);
        };

        Show(_view, _zoom, _lowLight);
    }

    private void Request(ShuttleCameraView view, float zoom, bool lowLight)
    {
        // Snapped so dragging the slider sends a handful of requests rather than one per pixel.
        zoom = MathF.Round(zoom / ShuttleCameraComponent.ZoomStep) * ShuttleCameraComponent.ZoomStep;
        zoom = Math.Clamp(zoom, ShuttleCameraComponent.MinZoom, ShuttleCameraComponent.MaxZoom);

        if (view == _view && MathHelper.CloseTo(zoom, _zoom) && lowLight == _lowLight)
            return;

        Show(view, zoom, lowLight);
        CameraRequested?.Invoke(view, zoom, lowLight);
    }

    private void Show(ShuttleCameraView view, float zoom, bool lowLight)
    {
        _view = view;
        _zoom = zoom;
        _lowLight = lowLight;
        _syncing = true;

        LowLightButton.Pressed = lowLight;

        foreach (var (button, buttonView) in _views)
        {
            button.Pressed = buttonView == view;
        }

        if (!ZoomSlider.Grabbed)
            ZoomSlider.Value = zoom;

        ZoomLabel.Text = Loc.GetString("shuttle-console-camera-zoom-value", ("value", $"{zoom:0.##}"));
        _syncing = false;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // The server has the last word, e.g. when the console restores the view it was left on.
        if (ZoomSlider.Grabbed ||
            !_entManager.TryGetComponent<ShuttleCameraComponent>(_player.LocalEntity, out var camera))
        {
            return;
        }

        if (camera.View != _view || !MathHelper.CloseTo(camera.Zoom, _zoom) || camera.LowLight != _lowLight)
            Show(camera.View, camera.Zoom, camera.LowLight);
    }
}
