using System.Linq;
using Content.Client.Administration.Managers;
using Content.Shared._NF.Bank;
using Content.Shared._NF.Shipyard.Prototypes;
using Content.Shared._WF.Administration;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._WF.Administration.UI.VesselSpawn;

/// <summary>
/// Lists every spawnable vessel prototype grouped by category, previews the selected one and spawns it via the
/// spawnvessel command.
/// </summary>
[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class VesselSpawnWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IClientConsoleHost _consoleHost = default!;
    [Dependency] private IClientAdminManager _adminManager = default!;
    [Dependency] private IPlayerManager _playerManager = default!;

    /// <summary>A vessel plus the bits computed once at load so filtering never redoes them.</summary>
    private sealed record VesselEntry(VesselPrototype Vessel, VesselSpawnCategory Category, string Haystack);

    private readonly List<VesselEntry> _vessels = new();
    private readonly Dictionary<VesselSpawnCategory, List<VesselEntry>> _byCategory = new();
    private readonly Dictionary<VesselSpawnCategory, bool> _expanded = new();
    private readonly Dictionary<VesselPrototype, VesselSpawnRow> _rows = new();
    private readonly ButtonGroup _rowGroup = new();

    private readonly List<VesselSize> _sizes = new();
    private readonly List<VesselSpawnCategory?> _categories = new();
    private readonly List<string> _owners = new();

    private VesselSize? _sizeFilter;
    private VesselSpawnCategory? _categoryFilter;
    private VesselPrototype? _selected;

    public VesselSpawnWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        LoadVessels();
        PopulateSizes();
        PopulateCategories();
        PopulateOwners();

        SearchBar.OnTextChanged += _ => PopulateVessels();
        CategoryFilter.OnItemSelected += OnCategorySelected;
        SizeFilter.OnItemSelected += OnSizeSelected;
        OwnerSelect.OnItemSelected += args => OwnerSelect.SelectId(args.Id);
        ResetViewButton.OnPressed += _ => Preview.FitToGrid();
        SpawnButton.OnPressed += _ => OnSpawnPressed();
        Preview.PreviewUpdated += UpdateGridInfo;

        // Keep the owner picker in step with players joining and leaving.
        _playerManager.PlayerListUpdated += PopulateOwners;
        OnClose += () =>
        {
            _playerManager.PlayerListUpdated -= PopulateOwners;
            Preview.PreviewUpdated -= UpdateGridInfo;
            Preview.Release();
        };

        PopulateVessels();
        UpdateSelection();
    }

    /// <summary>
    /// Collects every non-abstract vessel prototype once, sorted by name, and groups it by category.
    /// </summary>
    private void LoadVessels()
    {
        _vessels.Clear();
        _byCategory.Clear();

        foreach (var vessel in _prototypeManager.EnumeratePrototypes<VesselPrototype>())
        {
            if (vessel.Abstract)
                continue;

            var category = VesselSpawnCategories.Get(vessel);
            var entry = new VesselEntry(vessel, category, BuildHaystack(vessel));
            _vessels.Add(entry);

            if (!_byCategory.TryGetValue(category, out var list))
                _byCategory[category] = list = new List<VesselEntry>();
            list.Add(entry);
        }

        _vessels.Sort((a, b) => string.Compare(a.Vessel.Name, b.Vessel.Name, StringComparison.CurrentCultureIgnoreCase));
        foreach (var list in _byCategory.Values)
        {
            list.Sort((a, b) => string.Compare(a.Vessel.Name, b.Vessel.Name, StringComparison.CurrentCultureIgnoreCase));
        }

        // Expanded by default; collapsing is a per-session UI preference tracked as the user clicks headers.
        foreach (var category in _byCategory.Keys)
        {
            _expanded[category] = true;
        }
    }

    /// <summary>Lower-cased name, ID and class names, built once so search never re-lowers per keystroke.</summary>
    private static string BuildHaystack(VesselPrototype vessel)
    {
        var parts = new List<string> { vessel.Name, vessel.ID };
        parts.AddRange(vessel.Classes.Select(c => Loc.GetString($"shipyard-console-class-{c}")));
        return string.Join(' ', parts).ToLowerInvariant();
    }

    /// <summary>
    /// Fills the size filter with "All" plus every size present in the vessel list.
    /// </summary>
    private void PopulateSizes()
    {
        _sizes.Clear();
        _sizes.Add(VesselSize.All);
        _sizes.AddRange(_vessels.Select(entry => entry.Vessel.Category).Distinct().OrderBy(size => size));

        SizeFilter.Clear();
        for (var i = 0; i < _sizes.Count; i++)
        {
            SizeFilter.AddItem(Loc.GetString($"shipyard-console-category-{_sizes[i]}"), i);
        }
    }

    /// <summary>
    /// Fills the category filter with "All" plus every category actually in use, in display order.
    /// </summary>
    private void PopulateCategories()
    {
        _categories.Clear();
        _categories.Add(null);
        _categories.AddRange(VesselSpawnCategories.DisplayOrder.Where(c => _byCategory.ContainsKey(c)).Select(c => (VesselSpawnCategory?) c));

        CategoryFilter.Clear();
        for (var i = 0; i < _categories.Count; i++)
        {
            var label = _categories[i] is { } category
                ? Loc.GetString($"wf-vessel-spawn-category-{category}")
                : Loc.GetString("wf-vessel-spawn-category-all");
            CategoryFilter.AddItem(label, i);
        }
    }

    /// <summary>
    /// Fills the owner picker with "None" plus every connected player. Id 0 is none, id n is _owners[n - 1].
    /// </summary>
    private void PopulateOwners()
    {
        // Keep the current pick if that player is still connected.
        var selectedId = OwnerSelect.SelectedId;
        var selected = selectedId > 0 && selectedId <= _owners.Count ? _owners[selectedId - 1] : null;

        _owners.Clear();
        _owners.AddRange(_playerManager.Sessions.Select(session => session.Name).OrderBy(name => name));

        OwnerSelect.Clear();
        OwnerSelect.AddItem(Loc.GetString("wf-vessel-spawn-owner-none"), 0);
        for (var i = 0; i < _owners.Count; i++)
        {
            OwnerSelect.AddItem(_owners[i], i + 1);
        }

        var index = selected == null ? -1 : _owners.IndexOf(selected);
        OwnerSelect.SelectId(index >= 0 ? index + 1 : 0);
    }

    private void OnSizeSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SizeFilter.SelectId(args.Id);
        _sizeFilter = args.Id == 0 ? null : _sizes[args.Id];
        PopulateVessels();
    }

    private void OnCategorySelected(OptionButton.ItemSelectedEventArgs args)
    {
        CategoryFilter.SelectId(args.Id);
        _categoryFilter = _categories[args.Id];
        PopulateVessels();
    }

    /// <summary>
    /// Rebuilds the category headers and vessel rows using the current search text, category and size filters.
    /// Selection is preserved and reapplied to whichever new row still represents it.
    /// </summary>
    private void PopulateVessels()
    {
        Vessels.RemoveAllChildren();
        _rows.Clear();

        var search = SearchBar.Text.Trim().ToLowerInvariant();
        var searching = search.Length > 0;
        var shown = 0;

        foreach (var category in VesselSpawnCategories.DisplayOrder)
        {
            if (_categoryFilter != null && _categoryFilter != category)
                continue;
            if (!_byCategory.TryGetValue(category, out var entries))
                continue;

            var matches = entries.Where(entry =>
                (_sizeFilter == null || entry.Vessel.Category == _sizeFilter)
                && (!searching || entry.Haystack.Contains(search))).ToList();

            if (matches.Count == 0)
                continue;

            Vessels.AddChild(BuildCategoryGroup(category, matches, searching));
            shown += matches.Count;
        }

        CountLabel.Text = Loc.GetString("wf-vessel-spawn-count", ("shown", shown), ("total", _vessels.Count));

        if (_selected != null && _rows.TryGetValue(_selected, out var row))
            row.Pressed = true;
    }

    private Control BuildCategoryGroup(VesselSpawnCategory category, List<VesselEntry> matches, bool forceExpanded)
    {
        var heading = new CollapsibleHeading($"{Loc.GetString($"wf-vessel-spawn-category-{category}")} ({matches.Count})");
        heading.AddStyleClass(ContainerButton.StyleClassButton);
        heading.Label.HorizontalExpand = true;

        var body = new CollapsibleBody { Margin = new Thickness(4, 2, 0, 4) };
        var list = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, HorizontalExpand = true };
        body.AddChild(list);

        foreach (var entry in matches)
        {
            var row = new VesselSpawnRow(entry.Vessel) { Group = _rowGroup };
            row.OnPressed += _ => Select(entry.Vessel);
            list.AddChild(row);
            _rows[entry.Vessel] = row;
        }

        var collapsible = new Collapsible(heading, body)
        {
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 2),
            BodyVisible = forceExpanded || _expanded[category],
        };
        heading.OnToggled += args => _expanded[category] = args.Pressed;

        return collapsible;
    }

    private void Select(VesselPrototype vessel)
    {
        _selected = vessel;
        Preview.SetVessel(vessel);
        UpdateSelection();
    }

    /// <summary>
    /// Refreshes the name, details strip and spawn button for the current selection.
    /// </summary>
    private void UpdateSelection()
    {
        var canSpawn = _adminManager.CanCommand(WolfgateAdminCommands.SpawnVessel);
        SpawnButton.Disabled = _selected == null || !canSpawn;
        SpawnButton.ToolTip = _selected == null
            ? Loc.GetString("wf-vessel-spawn-tooltip-none")
            : !canSpawn
                ? Loc.GetString("wf-vessel-spawn-tooltip-denied")
                : null;

        if (_selected is not { } vessel)
        {
            SelectedName.Text = Loc.GetString("wf-vessel-spawn-none-selected");
            SelectedId.Text = string.Empty;
            SelectedCategory.Text = string.Empty;
            SelectedClasses.Text = string.Empty;
            SelectedSize.Text = string.Empty;
            SelectedEngines.Text = string.Empty;
            SelectedPrice.Text = string.Empty;
            SelectedGrid.Text = string.Empty;
            SelectedDescription.Text = string.Empty;
            return;
        }

        var none = Loc.GetString("wf-vessel-spawn-none");

        SelectedName.Text = vessel.Name;
        SelectedId.Text = vessel.ID;
        SelectedCategory.Text = Loc.GetString($"wf-vessel-spawn-category-{VesselSpawnCategories.Get(vessel)}");
        SelectedClasses.Text = vessel.Classes.Count > 0
            ? string.Join(", ", vessel.Classes.Select(c => Loc.GetString($"shipyard-console-class-{c}")))
            : none;
        SelectedSize.Text = Loc.GetString($"shipyard-console-category-{vessel.Category}");
        SelectedEngines.Text = vessel.Engines.Count > 0
            ? string.Join(", ", vessel.Engines.Select(e => Loc.GetString($"shipyard-console-engine-{e}")))
            : none;
        SelectedPrice.Text = BankSystemExtensions.ToSpesoString(vessel.Price);
        SelectedDescription.Text = vessel.Description;
        UpdateGridInfo();
    }

    private void UpdateGridInfo()
    {
        if (_selected == null)
            return;

        SelectedGrid.Text = Preview.HasPreview
            ? Loc.GetString("wf-vessel-spawn-grid-value",
                ("width", Preview.GridSize.X),
                ("height", Preview.GridSize.Y),
                ("count", Preview.TileCount))
            : string.Empty;
    }

    private void OnSpawnPressed()
    {
        if (_selected == null)
            return;

        var owner = OwnerSelect.SelectedId == 0 ? string.Empty : $" \"{_owners[OwnerSelect.SelectedId - 1]}\"";
        _consoleHost.ExecuteCommand($"{WolfgateAdminCommands.SpawnVessel} \"{_selected.ID}\"{owner}");
    }
}
