using Content.Shared._NF.Bank;
using Content.Shared._NF.Shipyard.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Administration.UI.VesselSpawn;

/// <summary>
/// One compact, selectable vessel entry in the grouped list: name, size and price. Toggle-style; the window
/// keeps only one row pressed at a time via a shared <see cref="ButtonGroup"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class VesselSpawnRow : ContainerButton
{
    public VesselPrototype Vessel { get; }

    public VesselSpawnRow(VesselPrototype vessel)
    {
        RobustXamlLoader.Load(this);

        Vessel = vessel;
        NameLabel.Text = vessel.Name;
        SizeLabel.Text = Loc.GetString($"shipyard-console-category-{vessel.Category}");
        PriceLabel.Text = BankSystemExtensions.ToSpesoString(vessel.Price);
    }
}
